//! AUTO-GENERATED headers, schema constants, and SQL-string escaping.

/// SQL generated-file marker — the header's first line, with no trailing
/// newline. The SQL templates emit it (followed by a newline) as line 1, and the
/// writer uses it to recognise files it owns (overwrite/clean safety). Tests that
/// synthesise file bodies append `\n` to form the full header line.
pub(crate) const AUTO_GENERATED_MARKER: &str = "-- AUTOMATICALLY GENERATED FILE.";

/// Rust generated-file marker — the `// @generated` header's first line, with
/// no trailing newline. `bindings::format_rs` prepends it (followed by a
/// newline) as line 1 and then runs `rustfmt` over the whole file (rustfmt
/// preserves a leading line comment), and the writer (`GeneratedKind::Rust`)
/// uses it to recognise files it owns.
pub(crate) const RUST_GENERATED_MARKER: &str =
    "// @generated by eql-codegen from the eql-domains catalog — do not edit";

/// The public `eql_v3` API surface: query operators, index extractors,
/// aggregates, AND the operator-backing comparison **wrappers**
/// (`eq`/`neq`/`lt`/`lte`/`gt`/`gte`/`contains`/`contained_by`). The wrappers
/// are public because they are the function-form equivalent of every supported
/// operator — required on platforms without operator support (Supabase/PostgREST
/// calls functions, not operators). User-column encrypted domains live in
/// `public`; only index-term TYPES and never-invoked plumbing live in
/// `INTERNAL_SCHEMA`.
pub(crate) const SCHEMA: &str = "eql_v3";

/// The schema housing INTERNAL eql_v3 objects only: the SEM index-term types
/// (`hmac_256`, `bloom_filter`, `ore_block_256(_term)`, `ope_cllw`) and their
/// support/constructor/comparator functions, the unsupported-operator
/// **blockers** (anti-functionality that only raises — never a caller
/// entrypoint), and the aggregate **state functions**. Split out of `SCHEMA`
/// so internal index-term TYPES stay out of the Supabase Table Builder type
/// picker. NOTE: the operator-backing comparison *wrappers* are NOT here —
/// they are public in `SCHEMA` (see above) so every operator has a callable
/// function equivalent.
pub(crate) const INTERNAL_SCHEMA: &str = "eql_v3_internal";

/// Always-present payload keys checked for presence in every domain CHECK.
/// Term-specific keys are appended after these by `context::domain_block`.
/// Defined in the catalog (`eql_domains::ENVELOPE_KEYS`) so the CHECKs and
/// the `eql-bindings` payload structs share one envelope definition.
pub(crate) const ENVELOPE_KEYS: &[&str] = eql_domains::ENVELOPE_KEYS;

/// Escape a string for use inside a single-quoted SQL literal by doubling
/// embedded single quotes.
pub(crate) fn sql_str(s: &str) -> String {
    s.replace('\'', "''")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn sql_marker_is_grep_compatible_single_line() {
        // The `^-- AUTOMATICALLY GENERATED FILE` marker is what
        // tasks/docs/validate/{coverage,required-tags}.sh grep on to skip
        // generated SQL — keep this assertion and that grep in lockstep. The
        // marker is a single line with no embedded newline (tests append `\n`).
        assert_eq!(AUTO_GENERATED_MARKER, "-- AUTOMATICALLY GENERATED FILE.");
        assert!(!AUTO_GENERATED_MARKER.contains('\n'));
    }

    #[test]
    fn schema_consts_match_sql_owned_schemas() {
        // The Rust side of the schema split. These literals must equal the SQL
        // `eql_v3_internal.owned_schemas()` array in src/v3/schema.sql; the
        // `mise run test:schemas:parity` gate compares the two (via the
        // `list-schemas` subcommand) so a hand-edit to one side without the
        // other fails CI. Pinning the values here catches a Rust-side rename
        // before the SQL is even consulted.
        assert_eq!(SCHEMA, "eql_v3");
        assert_eq!(INTERNAL_SCHEMA, "eql_v3_internal");
        // `owned_schemas()` (lib.rs) is the public accessor the binary prints;
        // it must derive from these consts, public first.
        assert_eq!(crate::owned_schemas(), [SCHEMA, INTERNAL_SCHEMA]);
    }

    #[test]
    fn sql_str_doubles_single_quotes() {
        assert_eq!(sql_str("o'brien"), "o''brien");
        assert_eq!(sql_str("a'b'c"), "a''b''c");
        assert_eq!(sql_str("integer_eq"), "integer_eq");
        assert_eq!(sql_str("<="), "<=");
    }
}
