// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma-next contract emit'.
// To regenerate, run: prisma-next contract emit
import type { QueryOperationTypes as PgAdapterQueryOps } from '@prisma-next/adapter-postgres/operation-types';
import type { CodecTypes as CipherstashTypes } from '@prisma-next/extension-cipherstash/codec-types';
import type { QueryOperationTypes as CipherstashQueryOperationTypes } from '@prisma-next/extension-cipherstash/operation-types';
import type {
  EncryptedBigInt,
  EncryptedBoolean,
  EncryptedDate,
  EncryptedDouble,
  EncryptedJson,
  EncryptedNumber,
  EncryptedString,
} from '@prisma-next/extension-cipherstash/runtime';
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  Timestamp,
  Timestamptz,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma-next/target-postgres/codec-types';

import type {
  ContractWithTypeMaps,
  TypeMaps as TypeMapsType,
} from '@prisma-next/sql-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma-next/contract/types';

export type StorageHash =
  StorageHashBase<'sha256:deb36a1ab7e51717f5ca822a32ff09a18cf3a0aaf1189262852c8953adba1720'>;
export type ExecutionHash = ExecutionHashBase<string>;
export type ProfileHash =
  ProfileHashBase<'sha256:9c8aa3114e84ed3b7ea2bd57526d9c2e1bf7c5292be694e9d3801f566fda7ccb'>;

export type CodecTypes = PgTypes & CipherstashTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes> &
  CipherstashQueryOperationTypes<CodecTypes>;
type DefaultLiteralValue<CodecId extends string, _Encoded> = CodecId extends keyof CodecTypes
  ? CodecTypes[CodecId]['output']
  : _Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly User: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly email: CodecTypes['cipherstash/eql-v3/eql_v3_text_search@1']['output'];
      readonly salary: CodecTypes['cipherstash/eql-v3/eql_v3_double_ord@1']['output'];
      readonly accountId: CodecTypes['cipherstash/eql-v3/eql_v3_bigint_ord@1']['output'];
      readonly birthday: CodecTypes['cipherstash/eql-v3/eql_v3_date_ord@1']['output'];
      readonly emailVerified: CodecTypes['cipherstash/eql-v3/eql_v3_boolean@1']['output'];
      readonly preferences: CodecTypes['cipherstash/eql-v3/eql_v3_json@1']['output'];
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly User: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly email: CodecTypes['cipherstash/eql-v3/eql_v3_text_search@1']['input'];
      readonly salary: CodecTypes['cipherstash/eql-v3/eql_v3_double_ord@1']['input'];
      readonly accountId: CodecTypes['cipherstash/eql-v3/eql_v3_bigint_ord@1']['input'];
      readonly birthday: CodecTypes['cipherstash/eql-v3/eql_v3_date_ord@1']['input'];
      readonly emailVerified: CodecTypes['cipherstash/eql-v3/eql_v3_boolean@1']['input'];
      readonly preferences: CodecTypes['cipherstash/eql-v3/eql_v3_json@1']['input'];
    };
  };
};
export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'sql-namespace';
        readonly entries: {
          readonly table: {
            readonly users: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly email: {
                  readonly nativeType: 'public.eql_v3_text_search';
                  readonly codecId: 'cipherstash/eql-v3/eql_v3_text_search@1';
                  readonly nullable: false;
                  readonly typeParams: {
                    readonly castAs: 'string';
                    readonly capabilities: {
                      readonly equality: true;
                      readonly orderAndRange: true;
                      readonly freeTextSearch: true;
                    };
                  };
                };
                readonly salary: {
                  readonly nativeType: 'public.eql_v3_double_ord';
                  readonly codecId: 'cipherstash/eql-v3/eql_v3_double_ord@1';
                  readonly nullable: false;
                  readonly typeParams: {
                    readonly castAs: 'number';
                    readonly capabilities: {
                      readonly equality: true;
                      readonly orderAndRange: true;
                      readonly freeTextSearch: false;
                    };
                  };
                };
                readonly accountid: {
                  readonly nativeType: 'public.eql_v3_bigint_ord';
                  readonly codecId: 'cipherstash/eql-v3/eql_v3_bigint_ord@1';
                  readonly nullable: false;
                  readonly typeParams: {
                    readonly castAs: 'bigint';
                    readonly capabilities: {
                      readonly equality: true;
                      readonly orderAndRange: true;
                      readonly freeTextSearch: false;
                    };
                  };
                };
                readonly birthday: {
                  readonly nativeType: 'public.eql_v3_date_ord';
                  readonly codecId: 'cipherstash/eql-v3/eql_v3_date_ord@1';
                  readonly nullable: false;
                  readonly typeParams: {
                    readonly castAs: 'date';
                    readonly capabilities: {
                      readonly equality: true;
                      readonly orderAndRange: true;
                      readonly freeTextSearch: false;
                    };
                  };
                };
                readonly emailverified: {
                  readonly nativeType: 'public.eql_v3_boolean';
                  readonly codecId: 'cipherstash/eql-v3/eql_v3_boolean@1';
                  readonly nullable: false;
                  readonly typeParams: {
                    readonly castAs: 'boolean';
                    readonly capabilities: {
                      readonly equality: false;
                      readonly orderAndRange: false;
                      readonly freeTextSearch: false;
                    };
                  };
                };
                readonly preferences: {
                  readonly nativeType: 'public.eql_v3_json';
                  readonly codecId: 'cipherstash/eql-v3/eql_v3_json@1';
                  readonly nullable: false;
                  readonly typeParams: {
                    readonly castAs: 'json';
                    readonly capabilities: {
                      readonly equality: false;
                      readonly orderAndRange: false;
                      readonly freeTextSearch: false;
                      readonly searchableJson: true;
                    };
                  };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly users: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly User: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly email: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'cipherstash/eql-v3/eql_v3_text_search@1';
                  readonly typeParams: {
                    readonly castAs: 'string';
                    readonly capabilities: {
                      readonly equality: true;
                      readonly orderAndRange: true;
                      readonly freeTextSearch: true;
                    };
                  };
                };
              };
              readonly salary: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'cipherstash/eql-v3/eql_v3_double_ord@1';
                  readonly typeParams: {
                    readonly castAs: 'number';
                    readonly capabilities: {
                      readonly equality: true;
                      readonly orderAndRange: true;
                      readonly freeTextSearch: false;
                    };
                  };
                };
              };
              readonly accountId: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'cipherstash/eql-v3/eql_v3_bigint_ord@1';
                  readonly typeParams: {
                    readonly castAs: 'bigint';
                    readonly capabilities: {
                      readonly equality: true;
                      readonly orderAndRange: true;
                      readonly freeTextSearch: false;
                    };
                  };
                };
              };
              readonly birthday: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'cipherstash/eql-v3/eql_v3_date_ord@1';
                  readonly typeParams: {
                    readonly castAs: 'date';
                    readonly capabilities: {
                      readonly equality: true;
                      readonly orderAndRange: true;
                      readonly freeTextSearch: false;
                    };
                  };
                };
              };
              readonly emailVerified: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'cipherstash/eql-v3/eql_v3_boolean@1';
                  readonly typeParams: {
                    readonly castAs: 'boolean';
                    readonly capabilities: {
                      readonly equality: false;
                      readonly orderAndRange: false;
                      readonly freeTextSearch: false;
                    };
                  };
                };
              };
              readonly preferences: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'cipherstash/eql-v3/eql_v3_json@1';
                  readonly typeParams: {
                    readonly castAs: 'json';
                    readonly capabilities: {
                      readonly equality: false;
                      readonly orderAndRange: false;
                      readonly freeTextSearch: false;
                      readonly searchableJson: true;
                    };
                  };
                };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'users';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly email: { readonly column: 'email' };
                readonly salary: { readonly column: 'salary' };
                readonly accountId: { readonly column: 'accountid' };
                readonly birthday: { readonly column: 'birthday' };
                readonly emailVerified: { readonly column: 'emailverified' };
                readonly preferences: { readonly column: 'preferences' };
              };
            };
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly lateral: true;
      readonly returning: true;
    };
  };
  readonly extensionPacks: {
    readonly cipherstash: {
      readonly familyId: 'sql';
      readonly id: 'cipherstash';
      readonly kind: 'extension';
      readonly targetId: 'postgres';
      readonly types: {
        readonly codecTypes: {
          readonly codecInstances: readonly [
            {
              readonly descriptor: {
                readonly codecId: 'cipherstash/string@1';
                readonly factory: unknown;
                readonly isParameterized: false;
                readonly meta: {
                  readonly db: {
                    readonly sql: {
                      readonly postgres: { readonly nativeType: 'eql_v2_encrypted' };
                    };
                  };
                };
                readonly paramsSchema: {
                  readonly '~standard': {
                    readonly validate: unknown;
                    readonly vendor: 'cipherstash';
                    readonly version: 1;
                  };
                };
                readonly renderOutputType: unknown;
                readonly targetTypes: readonly ['eql_v2_encrypted'];
                readonly traits: readonly [
                  'cipherstash:equality',
                  'cipherstash:free-text-search',
                  'cipherstash:order-and-range',
                ];
              };
            },
            {
              readonly descriptor: {
                readonly codecId: 'cipherstash/double@1';
                readonly factory: unknown;
                readonly isParameterized: false;
                readonly meta: {
                  readonly db: {
                    readonly sql: {
                      readonly postgres: { readonly nativeType: 'eql_v2_encrypted' };
                    };
                  };
                };
                readonly paramsSchema: {
                  readonly '~standard': {
                    readonly validate: unknown;
                    readonly vendor: 'cipherstash';
                    readonly version: 1;
                  };
                };
                readonly renderOutputType: unknown;
                readonly targetTypes: readonly ['eql_v2_encrypted'];
                readonly traits: readonly ['cipherstash:equality', 'cipherstash:order-and-range'];
              };
            },
            {
              readonly descriptor: {
                readonly codecId: 'cipherstash/bigint@1';
                readonly factory: unknown;
                readonly isParameterized: false;
                readonly meta: {
                  readonly db: {
                    readonly sql: {
                      readonly postgres: { readonly nativeType: 'eql_v2_encrypted' };
                    };
                  };
                };
                readonly paramsSchema: {
                  readonly '~standard': {
                    readonly validate: unknown;
                    readonly vendor: 'cipherstash';
                    readonly version: 1;
                  };
                };
                readonly renderOutputType: unknown;
                readonly targetTypes: readonly ['eql_v2_encrypted'];
                readonly traits: readonly ['cipherstash:equality', 'cipherstash:order-and-range'];
              };
            },
            {
              readonly descriptor: {
                readonly codecId: 'cipherstash/date@1';
                readonly factory: unknown;
                readonly isParameterized: false;
                readonly meta: {
                  readonly db: {
                    readonly sql: {
                      readonly postgres: { readonly nativeType: 'eql_v2_encrypted' };
                    };
                  };
                };
                readonly paramsSchema: {
                  readonly '~standard': {
                    readonly validate: unknown;
                    readonly vendor: 'cipherstash';
                    readonly version: 1;
                  };
                };
                readonly renderOutputType: unknown;
                readonly targetTypes: readonly ['eql_v2_encrypted'];
                readonly traits: readonly ['cipherstash:equality', 'cipherstash:order-and-range'];
              };
            },
            {
              readonly descriptor: {
                readonly codecId: 'cipherstash/boolean@1';
                readonly factory: unknown;
                readonly isParameterized: false;
                readonly meta: {
                  readonly db: {
                    readonly sql: {
                      readonly postgres: { readonly nativeType: 'eql_v2_encrypted' };
                    };
                  };
                };
                readonly paramsSchema: {
                  readonly '~standard': {
                    readonly validate: unknown;
                    readonly vendor: 'cipherstash';
                    readonly version: 1;
                  };
                };
                readonly renderOutputType: unknown;
                readonly targetTypes: readonly ['eql_v2_encrypted'];
                readonly traits: readonly ['cipherstash:equality'];
              };
            },
            {
              readonly descriptor: {
                readonly codecId: 'cipherstash/json@1';
                readonly factory: unknown;
                readonly isParameterized: false;
                readonly meta: {
                  readonly db: {
                    readonly sql: {
                      readonly postgres: { readonly nativeType: 'eql_v2_encrypted' };
                    };
                  };
                };
                readonly paramsSchema: {
                  readonly '~standard': {
                    readonly validate: unknown;
                    readonly vendor: 'cipherstash';
                    readonly version: 1;
                  };
                };
                readonly renderOutputType: unknown;
                readonly targetTypes: readonly ['eql_v2_encrypted'];
                readonly traits: readonly ['cipherstash:searchable-json'];
              };
            },
            {
              readonly descriptor: {
                readonly codecId: 'cipherstash/eql-v3/eql_v3_integer@1';
                readonly factory: unknown;
                readonly isParameterized: true;
                readonly meta: {
                  readonly db: {
                    readonly sql: {
                      readonly postgres: { readonly nativeType: 'public.eql_v3_integer' };
                    };
                  };
                };
                readonly paramsSchema: {
                  readonly '~standard': {
                    readonly validate: unknown;
                    readonly vendor: 'cipherstash';
                    readonly version: 1;
                  };
                };
                readonly renderOutputType: unknown;
                readonly targetTypes: readonly ['public.eql_v3_integer'];
                readonly traits: readonly [];
              };
            },
            {
              readonly descriptor: {
                readonly codecId: 'cipherstash/eql-v3/eql_v3_integer_eq@1';
                readonly factory: unknown;
                readonly isParameterized: true;
                readonly meta: {
                  readonly db: {
                    readonly sql: {
                      readonly postgres: { readonly nativeType: 'public.eql_v3_integer_eq' };
                    };
                  };
                };
                readonly paramsSchema: {
                  readonly '~standard': {
                    readonly validate: unknown;
                    readonly vendor: 'cipherstash';
                    readonly version: 1;
                  };
                };
                readonly renderOutputType: unknown;
                readonly targetTypes: readonly ['public.eql_v3_integer_eq'];
                readonly traits: readonly ['cipherstash:equality'];
              };
            },
            {
              readonly descriptor: {
                readonly codecId: 'cipherstash/eql-v3/eql_v3_integer_ord_ore@1';
                readonly factory: unknown;
                readonly isParameterized: true;
                readonly meta: {
                  readonly db: {
                    readonly sql: {
                      readonly postgres: { readonly nativeType: 'public.eql_v3_integer_ord_ore' };
                    };
                  };
                };
                readonly paramsSchema: {
                  readonly '~standard': {
                    readonly validate: unknown;
                    readonly vendor: 'cipherstash';
                    readonly version: 1;
                  };
                };
                readonly renderOutputType: unknown;
                readonly targetTypes: readonly ['public.eql_v3_integer_ord_ore'];
                readonly traits: readonly ['cipherstash:equality', 'cipherstash:order-and-range'];
              };
            },
            {
              readonly descriptor: {
                readonly codecId: 'cipherstash/eql-v3/eql_v3_integer_ord@1';
                readonly factory: unknown;
                readonly isParameterized: true;
                readonly meta: {
                  readonly db: {
                    readonly sql: {
                      readonly postgres: { readonly nativeType: 'public.eql_v3_integer_ord' };
                    };
                  };
                };
                readonly paramsSchema: {
                  readonly '~standard': {
                    readonly validate: unknown;
                    readonly vendor: 'cipherstash';
                    readonly version: 1;
                  };
                };
                readonly renderOutputType: unknown;
                readonly targetTypes: readonly ['public.eql_v3_integer_ord'];
                readonly traits: readonly ['cipherstash:equality', 'cipherstash:order-and-range'];
              };
            },
            {
              readonly descriptor: {
                readonly codecId: 'cipherstash/eql-v3/eql_v3_smallint@1';
                readonly factory: unknown;
                readonly isParameterized: true;
                readonly meta: {
                  readonly db: {
                    readonly sql: {
                      readonly postgres: { readonly nativeType: 'public.eql_v3_smallint' };
                    };
                  };
                };
                readonly paramsSchema: {
                  readonly '~standard': {
                    readonly validate: unknown;
                    readonly vendor: 'cipherstash';
                    readonly version: 1;
                  };
                };
                readonly renderOutputType: unknown;
                readonly targetTypes: readonly ['public.eql_v3_smallint'];
                readonly traits: readonly [];
              };
            },
            {
              readonly descriptor: {
                readonly codecId: 'cipherstash/eql-v3/eql_v3_smallint_eq@1';
                readonly factory: unknown;
                readonly isParameterized: true;
                readonly meta: {
                  readonly db: {
                    readonly sql: {
                      readonly postgres: { readonly nativeType: 'public.eql_v3_smallint_eq' };
                    };
                  };
                };
                readonly paramsSchema: {
                  readonly '~standard': {
                    readonly validate: unknown;
                    readonly vendor: 'cipherstash';
                    readonly version: 1;
                  };
                };
                readonly renderOutputType: unknown;
                readonly targetTypes: readonly ['public.eql_v3_smallint_eq'];
                readonly traits: readonly ['cipherstash:equality'];
              };
            },
            {
              readonly descriptor: {
                readonly codecId: 'cipherstash/eql-v3/eql_v3_smallint_ord_ore@1';
                readonly factory: unknown;
                readonly isParameterized: true;
                readonly meta: {
                  readonly db: {
                    readonly sql: {
                      readonly postgres: { readonly nativeType: 'public.eql_v3_smallint_ord_ore' };
                    };
                  };
                };
                readonly paramsSchema: {
                  readonly '~standard': {
                    readonly validate: unknown;
                    readonly vendor: 'cipherstash';
                    readonly version: 1;
                  };
                };
                readonly renderOutputType: unknown;
                readonly targetTypes: readonly ['public.eql_v3_smallint_ord_ore'];
                readonly traits: readonly ['cipherstash:equality', 'cipherstash:order-and-range'];
              };
            },
            {
              readonly descriptor: {
                readonly codecId: 'cipherstash/eql-v3/eql_v3_smallint_ord@1';
                readonly factory: unknown;
                readonly isParameterized: true;
                readonly meta: {
                  readonly db: {
                    readonly sql: {
                      readonly postgres: { readonly nativeType: 'public.eql_v3_smallint_ord' };
                    };
                  };
                };
                readonly paramsSchema: {
                  readonly '~standard': {
                    readonly validate: unknown;
                    readonly vendor: 'cipherstash';
                    readonly version: 1;
                  };
                };
                readonly renderOutputType: unknown;
                readonly targetTypes: readonly ['public.eql_v3_smallint_ord'];
                readonly traits: readonly ['cipherstash:equality', 'cipherstash:order-and-range'];
              };
            },
            {
              readonly descriptor: {
                readonly codecId: 'cipherstash/eql-v3/eql_v3_bigint@1';
                readonly factory: unknown;
                readonly isParameterized: true;
                readonly meta: {
                  readonly db: {
                    readonly sql: {
                      readonly postgres: { readonly nativeType: 'public.eql_v3_bigint' };
                    };
                  };
                };
                readonly paramsSchema: {
                  readonly '~standard': {
                    readonly validate: unknown;
                    readonly vendor: 'cipherstash';
                    readonly version: 1;
                  };
                };
                readonly renderOutputType: unknown;
                readonly targetTypes: readonly ['public.eql_v3_bigint'];
                readonly traits: readonly [];
              };
            },
            {
              readonly descriptor: {
                readonly codecId: 'cipherstash/eql-v3/eql_v3_bigint_eq@1';
                readonly factory: unknown;
                readonly isParameterized: true;
                readonly meta: {
                  readonly db: {
                    readonly sql: {
                      readonly postgres: { readonly nativeType: 'public.eql_v3_bigint_eq' };
                    };
                  };
                };
                readonly paramsSchema: {
                  readonly '~standard': {
                    readonly validate: unknown;
                    readonly vendor: 'cipherstash';
                    readonly version: 1;
                  };
                };
                readonly renderOutputType: unknown;
                readonly targetTypes: readonly ['public.eql_v3_bigint_eq'];
                readonly traits: readonly ['cipherstash:equality'];
              };
            },
            {
              readonly descriptor: {
                readonly codecId: 'cipherstash/eql-v3/eql_v3_bigint_ord_ore@1';
                readonly factory: unknown;
                readonly isParameterized: true;
                readonly meta: {
                  readonly db: {
                    readonly sql: {
                      readonly postgres: { readonly nativeType: 'public.eql_v3_bigint_ord_ore' };
                    };
                  };
                };
                readonly paramsSchema: {
                  readonly '~standard': {
                    readonly validate: unknown;
                    readonly vendor: 'cipherstash';
                    readonly version: 1;
                  };
                };
                readonly renderOutputType: unknown;
                readonly targetTypes: readonly ['public.eql_v3_bigint_ord_ore'];
                readonly traits: readonly ['cipherstash:equality', 'cipherstash:order-and-range'];
              };
            },
            {
              readonly descriptor: {
                readonly codecId: 'cipherstash/eql-v3/eql_v3_bigint_ord@1';
                readonly factory: unknown;
                readonly isParameterized: true;
                readonly meta: {
                  readonly db: {
                    readonly sql: {
                      readonly postgres: { readonly nativeType: 'public.eql_v3_bigint_ord' };
                    };
                  };
                };
                readonly paramsSchema: {
                  readonly '~standard': {
                    readonly validate: unknown;
                    readonly vendor: 'cipherstash';
                    readonly version: 1;
                  };
                };
                readonly renderOutputType: unknown;
                readonly targetTypes: readonly ['public.eql_v3_bigint_ord'];
                readonly traits: readonly ['cipherstash:equality', 'cipherstash:order-and-range'];
              };
            },
            {
              readonly descriptor: {
                readonly codecId: 'cipherstash/eql-v3/eql_v3_date@1';
                readonly factory: unknown;
                readonly isParameterized: true;
                readonly meta: {
                  readonly db: {
                    readonly sql: {
                      readonly postgres: { readonly nativeType: 'public.eql_v3_date' };
                    };
                  };
                };
                readonly paramsSchema: {
                  readonly '~standard': {
                    readonly validate: unknown;
                    readonly vendor: 'cipherstash';
                    readonly version: 1;
                  };
                };
                readonly renderOutputType: unknown;
                readonly targetTypes: readonly ['public.eql_v3_date'];
                readonly traits: readonly [];
              };
            },
            {
              readonly descriptor: {
                readonly codecId: 'cipherstash/eql-v3/eql_v3_date_eq@1';
                readonly factory: unknown;
                readonly isParameterized: true;
                readonly meta: {
                  readonly db: {
                    readonly sql: {
                      readonly postgres: { readonly nativeType: 'public.eql_v3_date_eq' };
                    };
                  };
                };
                readonly paramsSchema: {
                  readonly '~standard': {
                    readonly validate: unknown;
                    readonly vendor: 'cipherstash';
                    readonly version: 1;
                  };
                };
                readonly renderOutputType: unknown;
                readonly targetTypes: readonly ['public.eql_v3_date_eq'];
                readonly traits: readonly ['cipherstash:equality'];
              };
            },
            {
              readonly descriptor: {
                readonly codecId: 'cipherstash/eql-v3/eql_v3_date_ord_ore@1';
                readonly factory: unknown;
                readonly isParameterized: true;
                readonly meta: {
                  readonly db: {
                    readonly sql: {
                      readonly postgres: { readonly nativeType: 'public.eql_v3_date_ord_ore' };
                    };
                  };
                };
                readonly paramsSchema: {
                  readonly '~standard': {
                    readonly validate: unknown;
                    readonly vendor: 'cipherstash';
                    readonly version: 1;
                  };
                };
                readonly renderOutputType: unknown;
                readonly targetTypes: readonly ['public.eql_v3_date_ord_ore'];
                readonly traits: readonly ['cipherstash:equality', 'cipherstash:order-and-range'];
              };
            },
            {
              readonly descriptor: {
                readonly codecId: 'cipherstash/eql-v3/eql_v3_date_ord@1';
                readonly factory: unknown;
                readonly isParameterized: true;
                readonly meta: {
                  readonly db: {
                    readonly sql: {
                      readonly postgres: { readonly nativeType: 'public.eql_v3_date_ord' };
                    };
                  };
                };
                readonly paramsSchema: {
                  readonly '~standard': {
                    readonly validate: unknown;
                    readonly vendor: 'cipherstash';
                    readonly version: 1;
                  };
                };
                readonly renderOutputType: unknown;
                readonly targetTypes: readonly ['public.eql_v3_date_ord'];
                readonly traits: readonly ['cipherstash:equality', 'cipherstash:order-and-range'];
              };
            },
            {
              readonly descriptor: {
                readonly codecId: 'cipherstash/eql-v3/eql_v3_timestamp@1';
                readonly factory: unknown;
                readonly isParameterized: true;
                readonly meta: {
                  readonly db: {
                    readonly sql: {
                      readonly postgres: { readonly nativeType: 'public.eql_v3_timestamp' };
                    };
                  };
                };
                readonly paramsSchema: {
                  readonly '~standard': {
                    readonly validate: unknown;
                    readonly vendor: 'cipherstash';
                    readonly version: 1;
                  };
                };
                readonly renderOutputType: unknown;
                readonly targetTypes: readonly ['public.eql_v3_timestamp'];
                readonly traits: readonly [];
              };
            },
            {
              readonly descriptor: {
                readonly codecId: 'cipherstash/eql-v3/eql_v3_timestamp_eq@1';
                readonly factory: unknown;
                readonly isParameterized: true;
                readonly meta: {
                  readonly db: {
                    readonly sql: {
                      readonly postgres: { readonly nativeType: 'public.eql_v3_timestamp_eq' };
                    };
                  };
                };
                readonly paramsSchema: {
                  readonly '~standard': {
                    readonly validate: unknown;
                    readonly vendor: 'cipherstash';
                    readonly version: 1;
                  };
                };
                readonly renderOutputType: unknown;
                readonly targetTypes: readonly ['public.eql_v3_timestamp_eq'];
                readonly traits: readonly ['cipherstash:equality'];
              };
            },
            {
              readonly descriptor: {
                readonly codecId: 'cipherstash/eql-v3/eql_v3_timestamp_ord_ore@1';
                readonly factory: unknown;
                readonly isParameterized: true;
                readonly meta: {
                  readonly db: {
                    readonly sql: {
                      readonly postgres: { readonly nativeType: 'public.eql_v3_timestamp_ord_ore' };
                    };
                  };
                };
                readonly paramsSchema: {
                  readonly '~standard': {
                    readonly validate: unknown;
                    readonly vendor: 'cipherstash';
                    readonly version: 1;
                  };
                };
                readonly renderOutputType: unknown;
                readonly targetTypes: readonly ['public.eql_v3_timestamp_ord_ore'];
                readonly traits: readonly ['cipherstash:equality', 'cipherstash:order-and-range'];
              };
            },
            {
              readonly descriptor: {
                readonly codecId: 'cipherstash/eql-v3/eql_v3_timestamp_ord@1';
                readonly factory: unknown;
                readonly isParameterized: true;
                readonly meta: {
                  readonly db: {
                    readonly sql: {
                      readonly postgres: { readonly nativeType: 'public.eql_v3_timestamp_ord' };
                    };
                  };
                };
                readonly paramsSchema: {
                  readonly '~standard': {
                    readonly validate: unknown;
                    readonly vendor: 'cipherstash';
                    readonly version: 1;
                  };
                };
                readonly renderOutputType: unknown;
                readonly targetTypes: readonly ['public.eql_v3_timestamp_ord'];
                readonly traits: readonly ['cipherstash:equality', 'cipherstash:order-and-range'];
              };
            },
            {
              readonly descriptor: {
                readonly codecId: 'cipherstash/eql-v3/eql_v3_numeric@1';
                readonly factory: unknown;
                readonly isParameterized: true;
                readonly meta: {
                  readonly db: {
                    readonly sql: {
                      readonly postgres: { readonly nativeType: 'public.eql_v3_numeric' };
                    };
                  };
                };
                readonly paramsSchema: {
                  readonly '~standard': {
                    readonly validate: unknown;
                    readonly vendor: 'cipherstash';
                    readonly version: 1;
                  };
                };
                readonly renderOutputType: unknown;
                readonly targetTypes: readonly ['public.eql_v3_numeric'];
                readonly traits: readonly [];
              };
            },
            {
              readonly descriptor: {
                readonly codecId: 'cipherstash/eql-v3/eql_v3_numeric_eq@1';
                readonly factory: unknown;
                readonly isParameterized: true;
                readonly meta: {
                  readonly db: {
                    readonly sql: {
                      readonly postgres: { readonly nativeType: 'public.eql_v3_numeric_eq' };
                    };
                  };
                };
                readonly paramsSchema: {
                  readonly '~standard': {
                    readonly validate: unknown;
                    readonly vendor: 'cipherstash';
                    readonly version: 1;
                  };
                };
                readonly renderOutputType: unknown;
                readonly targetTypes: readonly ['public.eql_v3_numeric_eq'];
                readonly traits: readonly ['cipherstash:equality'];
              };
            },
            {
              readonly descriptor: {
                readonly codecId: 'cipherstash/eql-v3/eql_v3_numeric_ord_ore@1';
                readonly factory: unknown;
                readonly isParameterized: true;
                readonly meta: {
                  readonly db: {
                    readonly sql: {
                      readonly postgres: { readonly nativeType: 'public.eql_v3_numeric_ord_ore' };
                    };
                  };
                };
                readonly paramsSchema: {
                  readonly '~standard': {
                    readonly validate: unknown;
                    readonly vendor: 'cipherstash';
                    readonly version: 1;
                  };
                };
                readonly renderOutputType: unknown;
                readonly targetTypes: readonly ['public.eql_v3_numeric_ord_ore'];
                readonly traits: readonly ['cipherstash:equality', 'cipherstash:order-and-range'];
              };
            },
            {
              readonly descriptor: {
                readonly codecId: 'cipherstash/eql-v3/eql_v3_numeric_ord@1';
                readonly factory: unknown;
                readonly isParameterized: true;
                readonly meta: {
                  readonly db: {
                    readonly sql: {
                      readonly postgres: { readonly nativeType: 'public.eql_v3_numeric_ord' };
                    };
                  };
                };
                readonly paramsSchema: {
                  readonly '~standard': {
                    readonly validate: unknown;
                    readonly vendor: 'cipherstash';
                    readonly version: 1;
                  };
                };
                readonly renderOutputType: unknown;
                readonly targetTypes: readonly ['public.eql_v3_numeric_ord'];
                readonly traits: readonly ['cipherstash:equality', 'cipherstash:order-and-range'];
              };
            },
            {
              readonly descriptor: {
                readonly codecId: 'cipherstash/eql-v3/eql_v3_text@1';
                readonly factory: unknown;
                readonly isParameterized: true;
                readonly meta: {
                  readonly db: {
                    readonly sql: {
                      readonly postgres: { readonly nativeType: 'public.eql_v3_text' };
                    };
                  };
                };
                readonly paramsSchema: {
                  readonly '~standard': {
                    readonly validate: unknown;
                    readonly vendor: 'cipherstash';
                    readonly version: 1;
                  };
                };
                readonly renderOutputType: unknown;
                readonly targetTypes: readonly ['public.eql_v3_text'];
                readonly traits: readonly [];
              };
            },
            {
              readonly descriptor: {
                readonly codecId: 'cipherstash/eql-v3/eql_v3_text_eq@1';
                readonly factory: unknown;
                readonly isParameterized: true;
                readonly meta: {
                  readonly db: {
                    readonly sql: {
                      readonly postgres: { readonly nativeType: 'public.eql_v3_text_eq' };
                    };
                  };
                };
                readonly paramsSchema: {
                  readonly '~standard': {
                    readonly validate: unknown;
                    readonly vendor: 'cipherstash';
                    readonly version: 1;
                  };
                };
                readonly renderOutputType: unknown;
                readonly targetTypes: readonly ['public.eql_v3_text_eq'];
                readonly traits: readonly ['cipherstash:equality'];
              };
            },
            {
              readonly descriptor: {
                readonly codecId: 'cipherstash/eql-v3/eql_v3_text_match@1';
                readonly factory: unknown;
                readonly isParameterized: true;
                readonly meta: {
                  readonly db: {
                    readonly sql: {
                      readonly postgres: { readonly nativeType: 'public.eql_v3_text_match' };
                    };
                  };
                };
                readonly paramsSchema: {
                  readonly '~standard': {
                    readonly validate: unknown;
                    readonly vendor: 'cipherstash';
                    readonly version: 1;
                  };
                };
                readonly renderOutputType: unknown;
                readonly targetTypes: readonly ['public.eql_v3_text_match'];
                readonly traits: readonly ['cipherstash:free-text-search'];
              };
            },
            {
              readonly descriptor: {
                readonly codecId: 'cipherstash/eql-v3/eql_v3_text_ord_ore@1';
                readonly factory: unknown;
                readonly isParameterized: true;
                readonly meta: {
                  readonly db: {
                    readonly sql: {
                      readonly postgres: { readonly nativeType: 'public.eql_v3_text_ord_ore' };
                    };
                  };
                };
                readonly paramsSchema: {
                  readonly '~standard': {
                    readonly validate: unknown;
                    readonly vendor: 'cipherstash';
                    readonly version: 1;
                  };
                };
                readonly renderOutputType: unknown;
                readonly targetTypes: readonly ['public.eql_v3_text_ord_ore'];
                readonly traits: readonly ['cipherstash:equality', 'cipherstash:order-and-range'];
              };
            },
            {
              readonly descriptor: {
                readonly codecId: 'cipherstash/eql-v3/eql_v3_text_ord@1';
                readonly factory: unknown;
                readonly isParameterized: true;
                readonly meta: {
                  readonly db: {
                    readonly sql: {
                      readonly postgres: { readonly nativeType: 'public.eql_v3_text_ord' };
                    };
                  };
                };
                readonly paramsSchema: {
                  readonly '~standard': {
                    readonly validate: unknown;
                    readonly vendor: 'cipherstash';
                    readonly version: 1;
                  };
                };
                readonly renderOutputType: unknown;
                readonly targetTypes: readonly ['public.eql_v3_text_ord'];
                readonly traits: readonly ['cipherstash:equality', 'cipherstash:order-and-range'];
              };
            },
            {
              readonly descriptor: {
                readonly codecId: 'cipherstash/eql-v3/eql_v3_text_search@1';
                readonly factory: unknown;
                readonly isParameterized: true;
                readonly meta: {
                  readonly db: {
                    readonly sql: {
                      readonly postgres: { readonly nativeType: 'public.eql_v3_text_search' };
                    };
                  };
                };
                readonly paramsSchema: {
                  readonly '~standard': {
                    readonly validate: unknown;
                    readonly vendor: 'cipherstash';
                    readonly version: 1;
                  };
                };
                readonly renderOutputType: unknown;
                readonly targetTypes: readonly ['public.eql_v3_text_search'];
                readonly traits: readonly [
                  'cipherstash:equality',
                  'cipherstash:order-and-range',
                  'cipherstash:free-text-search',
                ];
              };
            },
            {
              readonly descriptor: {
                readonly codecId: 'cipherstash/eql-v3/eql_v3_boolean@1';
                readonly factory: unknown;
                readonly isParameterized: true;
                readonly meta: {
                  readonly db: {
                    readonly sql: {
                      readonly postgres: { readonly nativeType: 'public.eql_v3_boolean' };
                    };
                  };
                };
                readonly paramsSchema: {
                  readonly '~standard': {
                    readonly validate: unknown;
                    readonly vendor: 'cipherstash';
                    readonly version: 1;
                  };
                };
                readonly renderOutputType: unknown;
                readonly targetTypes: readonly ['public.eql_v3_boolean'];
                readonly traits: readonly [];
              };
            },
            {
              readonly descriptor: {
                readonly codecId: 'cipherstash/eql-v3/eql_v3_real@1';
                readonly factory: unknown;
                readonly isParameterized: true;
                readonly meta: {
                  readonly db: {
                    readonly sql: {
                      readonly postgres: { readonly nativeType: 'public.eql_v3_real' };
                    };
                  };
                };
                readonly paramsSchema: {
                  readonly '~standard': {
                    readonly validate: unknown;
                    readonly vendor: 'cipherstash';
                    readonly version: 1;
                  };
                };
                readonly renderOutputType: unknown;
                readonly targetTypes: readonly ['public.eql_v3_real'];
                readonly traits: readonly [];
              };
            },
            {
              readonly descriptor: {
                readonly codecId: 'cipherstash/eql-v3/eql_v3_real_eq@1';
                readonly factory: unknown;
                readonly isParameterized: true;
                readonly meta: {
                  readonly db: {
                    readonly sql: {
                      readonly postgres: { readonly nativeType: 'public.eql_v3_real_eq' };
                    };
                  };
                };
                readonly paramsSchema: {
                  readonly '~standard': {
                    readonly validate: unknown;
                    readonly vendor: 'cipherstash';
                    readonly version: 1;
                  };
                };
                readonly renderOutputType: unknown;
                readonly targetTypes: readonly ['public.eql_v3_real_eq'];
                readonly traits: readonly ['cipherstash:equality'];
              };
            },
            {
              readonly descriptor: {
                readonly codecId: 'cipherstash/eql-v3/eql_v3_real_ord_ore@1';
                readonly factory: unknown;
                readonly isParameterized: true;
                readonly meta: {
                  readonly db: {
                    readonly sql: {
                      readonly postgres: { readonly nativeType: 'public.eql_v3_real_ord_ore' };
                    };
                  };
                };
                readonly paramsSchema: {
                  readonly '~standard': {
                    readonly validate: unknown;
                    readonly vendor: 'cipherstash';
                    readonly version: 1;
                  };
                };
                readonly renderOutputType: unknown;
                readonly targetTypes: readonly ['public.eql_v3_real_ord_ore'];
                readonly traits: readonly ['cipherstash:equality', 'cipherstash:order-and-range'];
              };
            },
            {
              readonly descriptor: {
                readonly codecId: 'cipherstash/eql-v3/eql_v3_real_ord@1';
                readonly factory: unknown;
                readonly isParameterized: true;
                readonly meta: {
                  readonly db: {
                    readonly sql: {
                      readonly postgres: { readonly nativeType: 'public.eql_v3_real_ord' };
                    };
                  };
                };
                readonly paramsSchema: {
                  readonly '~standard': {
                    readonly validate: unknown;
                    readonly vendor: 'cipherstash';
                    readonly version: 1;
                  };
                };
                readonly renderOutputType: unknown;
                readonly targetTypes: readonly ['public.eql_v3_real_ord'];
                readonly traits: readonly ['cipherstash:equality', 'cipherstash:order-and-range'];
              };
            },
            {
              readonly descriptor: {
                readonly codecId: 'cipherstash/eql-v3/eql_v3_double@1';
                readonly factory: unknown;
                readonly isParameterized: true;
                readonly meta: {
                  readonly db: {
                    readonly sql: {
                      readonly postgres: { readonly nativeType: 'public.eql_v3_double' };
                    };
                  };
                };
                readonly paramsSchema: {
                  readonly '~standard': {
                    readonly validate: unknown;
                    readonly vendor: 'cipherstash';
                    readonly version: 1;
                  };
                };
                readonly renderOutputType: unknown;
                readonly targetTypes: readonly ['public.eql_v3_double'];
                readonly traits: readonly [];
              };
            },
            {
              readonly descriptor: {
                readonly codecId: 'cipherstash/eql-v3/eql_v3_double_eq@1';
                readonly factory: unknown;
                readonly isParameterized: true;
                readonly meta: {
                  readonly db: {
                    readonly sql: {
                      readonly postgres: { readonly nativeType: 'public.eql_v3_double_eq' };
                    };
                  };
                };
                readonly paramsSchema: {
                  readonly '~standard': {
                    readonly validate: unknown;
                    readonly vendor: 'cipherstash';
                    readonly version: 1;
                  };
                };
                readonly renderOutputType: unknown;
                readonly targetTypes: readonly ['public.eql_v3_double_eq'];
                readonly traits: readonly ['cipherstash:equality'];
              };
            },
            {
              readonly descriptor: {
                readonly codecId: 'cipherstash/eql-v3/eql_v3_double_ord_ore@1';
                readonly factory: unknown;
                readonly isParameterized: true;
                readonly meta: {
                  readonly db: {
                    readonly sql: {
                      readonly postgres: { readonly nativeType: 'public.eql_v3_double_ord_ore' };
                    };
                  };
                };
                readonly paramsSchema: {
                  readonly '~standard': {
                    readonly validate: unknown;
                    readonly vendor: 'cipherstash';
                    readonly version: 1;
                  };
                };
                readonly renderOutputType: unknown;
                readonly targetTypes: readonly ['public.eql_v3_double_ord_ore'];
                readonly traits: readonly ['cipherstash:equality', 'cipherstash:order-and-range'];
              };
            },
            {
              readonly descriptor: {
                readonly codecId: 'cipherstash/eql-v3/eql_v3_double_ord@1';
                readonly factory: unknown;
                readonly isParameterized: true;
                readonly meta: {
                  readonly db: {
                    readonly sql: {
                      readonly postgres: { readonly nativeType: 'public.eql_v3_double_ord' };
                    };
                  };
                };
                readonly paramsSchema: {
                  readonly '~standard': {
                    readonly validate: unknown;
                    readonly vendor: 'cipherstash';
                    readonly version: 1;
                  };
                };
                readonly renderOutputType: unknown;
                readonly targetTypes: readonly ['public.eql_v3_double_ord'];
                readonly traits: readonly ['cipherstash:equality', 'cipherstash:order-and-range'];
              };
            },
            {
              readonly descriptor: {
                readonly codecId: 'cipherstash/eql-v3/eql_v3_json@1';
                readonly factory: unknown;
                readonly isParameterized: true;
                readonly meta: {
                  readonly db: {
                    readonly sql: {
                      readonly postgres: { readonly nativeType: 'public.eql_v3_json' };
                    };
                  };
                };
                readonly paramsSchema: {
                  readonly '~standard': {
                    readonly validate: unknown;
                    readonly vendor: 'cipherstash';
                    readonly version: 1;
                  };
                };
                readonly renderOutputType: unknown;
                readonly targetTypes: readonly ['public.eql_v3_json'];
                readonly traits: readonly ['cipherstash:searchable-json'];
              };
            },
          ];
          readonly import: {
            readonly alias: 'CipherstashTypes';
            readonly named: 'CodecTypes';
            readonly package: '@prisma-next/extension-cipherstash/codec-types';
          };
          readonly typeImports: readonly [
            {
              readonly alias: 'EncryptedString';
              readonly named: 'EncryptedString';
              readonly package: '@prisma-next/extension-cipherstash/runtime';
            },
            {
              readonly alias: 'EncryptedDouble';
              readonly named: 'EncryptedDouble';
              readonly package: '@prisma-next/extension-cipherstash/runtime';
            },
            {
              readonly alias: 'EncryptedBigInt';
              readonly named: 'EncryptedBigInt';
              readonly package: '@prisma-next/extension-cipherstash/runtime';
            },
            {
              readonly alias: 'EncryptedDate';
              readonly named: 'EncryptedDate';
              readonly package: '@prisma-next/extension-cipherstash/runtime';
            },
            {
              readonly alias: 'EncryptedBoolean';
              readonly named: 'EncryptedBoolean';
              readonly package: '@prisma-next/extension-cipherstash/runtime';
            },
            {
              readonly alias: 'EncryptedJson';
              readonly named: 'EncryptedJson';
              readonly package: '@prisma-next/extension-cipherstash/runtime';
            },
            {
              readonly alias: 'EncryptedNumber';
              readonly named: 'EncryptedNumber';
              readonly package: '@prisma-next/extension-cipherstash/runtime';
            },
          ];
        };
        readonly queryOperationTypes: {
          readonly import: {
            readonly alias: 'CipherstashQueryOperationTypes';
            readonly named: 'QueryOperationTypes';
            readonly package: '@prisma-next/extension-cipherstash/operation-types';
          };
        };
        readonly storage: readonly [
          {
            readonly familyId: 'sql';
            readonly nativeType: 'eql_v2_encrypted';
            readonly targetId: 'postgres';
            readonly typeId: 'cipherstash/string@1';
          },
          {
            readonly familyId: 'sql';
            readonly nativeType: 'eql_v2_encrypted';
            readonly targetId: 'postgres';
            readonly typeId: 'cipherstash/double@1';
          },
          {
            readonly familyId: 'sql';
            readonly nativeType: 'eql_v2_encrypted';
            readonly targetId: 'postgres';
            readonly typeId: 'cipherstash/bigint@1';
          },
          {
            readonly familyId: 'sql';
            readonly nativeType: 'eql_v2_encrypted';
            readonly targetId: 'postgres';
            readonly typeId: 'cipherstash/date@1';
          },
          {
            readonly familyId: 'sql';
            readonly nativeType: 'eql_v2_encrypted';
            readonly targetId: 'postgres';
            readonly typeId: 'cipherstash/boolean@1';
          },
          {
            readonly familyId: 'sql';
            readonly nativeType: 'eql_v2_encrypted';
            readonly targetId: 'postgres';
            readonly typeId: 'cipherstash/json@1';
          },
          {
            readonly familyId: 'sql';
            readonly nativeType: 'public.eql_v3_integer';
            readonly targetId: 'postgres';
            readonly typeId: 'cipherstash/eql-v3/eql_v3_integer@1';
          },
          {
            readonly familyId: 'sql';
            readonly nativeType: 'public.eql_v3_integer_eq';
            readonly targetId: 'postgres';
            readonly typeId: 'cipherstash/eql-v3/eql_v3_integer_eq@1';
          },
          {
            readonly familyId: 'sql';
            readonly nativeType: 'public.eql_v3_integer_ord_ore';
            readonly targetId: 'postgres';
            readonly typeId: 'cipherstash/eql-v3/eql_v3_integer_ord_ore@1';
          },
          {
            readonly familyId: 'sql';
            readonly nativeType: 'public.eql_v3_integer_ord';
            readonly targetId: 'postgres';
            readonly typeId: 'cipherstash/eql-v3/eql_v3_integer_ord@1';
          },
          {
            readonly familyId: 'sql';
            readonly nativeType: 'public.eql_v3_smallint';
            readonly targetId: 'postgres';
            readonly typeId: 'cipherstash/eql-v3/eql_v3_smallint@1';
          },
          {
            readonly familyId: 'sql';
            readonly nativeType: 'public.eql_v3_smallint_eq';
            readonly targetId: 'postgres';
            readonly typeId: 'cipherstash/eql-v3/eql_v3_smallint_eq@1';
          },
          {
            readonly familyId: 'sql';
            readonly nativeType: 'public.eql_v3_smallint_ord_ore';
            readonly targetId: 'postgres';
            readonly typeId: 'cipherstash/eql-v3/eql_v3_smallint_ord_ore@1';
          },
          {
            readonly familyId: 'sql';
            readonly nativeType: 'public.eql_v3_smallint_ord';
            readonly targetId: 'postgres';
            readonly typeId: 'cipherstash/eql-v3/eql_v3_smallint_ord@1';
          },
          {
            readonly familyId: 'sql';
            readonly nativeType: 'public.eql_v3_bigint';
            readonly targetId: 'postgres';
            readonly typeId: 'cipherstash/eql-v3/eql_v3_bigint@1';
          },
          {
            readonly familyId: 'sql';
            readonly nativeType: 'public.eql_v3_bigint_eq';
            readonly targetId: 'postgres';
            readonly typeId: 'cipherstash/eql-v3/eql_v3_bigint_eq@1';
          },
          {
            readonly familyId: 'sql';
            readonly nativeType: 'public.eql_v3_bigint_ord_ore';
            readonly targetId: 'postgres';
            readonly typeId: 'cipherstash/eql-v3/eql_v3_bigint_ord_ore@1';
          },
          {
            readonly familyId: 'sql';
            readonly nativeType: 'public.eql_v3_bigint_ord';
            readonly targetId: 'postgres';
            readonly typeId: 'cipherstash/eql-v3/eql_v3_bigint_ord@1';
          },
          {
            readonly familyId: 'sql';
            readonly nativeType: 'public.eql_v3_date';
            readonly targetId: 'postgres';
            readonly typeId: 'cipherstash/eql-v3/eql_v3_date@1';
          },
          {
            readonly familyId: 'sql';
            readonly nativeType: 'public.eql_v3_date_eq';
            readonly targetId: 'postgres';
            readonly typeId: 'cipherstash/eql-v3/eql_v3_date_eq@1';
          },
          {
            readonly familyId: 'sql';
            readonly nativeType: 'public.eql_v3_date_ord_ore';
            readonly targetId: 'postgres';
            readonly typeId: 'cipherstash/eql-v3/eql_v3_date_ord_ore@1';
          },
          {
            readonly familyId: 'sql';
            readonly nativeType: 'public.eql_v3_date_ord';
            readonly targetId: 'postgres';
            readonly typeId: 'cipherstash/eql-v3/eql_v3_date_ord@1';
          },
          {
            readonly familyId: 'sql';
            readonly nativeType: 'public.eql_v3_timestamp';
            readonly targetId: 'postgres';
            readonly typeId: 'cipherstash/eql-v3/eql_v3_timestamp@1';
          },
          {
            readonly familyId: 'sql';
            readonly nativeType: 'public.eql_v3_timestamp_eq';
            readonly targetId: 'postgres';
            readonly typeId: 'cipherstash/eql-v3/eql_v3_timestamp_eq@1';
          },
          {
            readonly familyId: 'sql';
            readonly nativeType: 'public.eql_v3_timestamp_ord_ore';
            readonly targetId: 'postgres';
            readonly typeId: 'cipherstash/eql-v3/eql_v3_timestamp_ord_ore@1';
          },
          {
            readonly familyId: 'sql';
            readonly nativeType: 'public.eql_v3_timestamp_ord';
            readonly targetId: 'postgres';
            readonly typeId: 'cipherstash/eql-v3/eql_v3_timestamp_ord@1';
          },
          {
            readonly familyId: 'sql';
            readonly nativeType: 'public.eql_v3_numeric';
            readonly targetId: 'postgres';
            readonly typeId: 'cipherstash/eql-v3/eql_v3_numeric@1';
          },
          {
            readonly familyId: 'sql';
            readonly nativeType: 'public.eql_v3_numeric_eq';
            readonly targetId: 'postgres';
            readonly typeId: 'cipherstash/eql-v3/eql_v3_numeric_eq@1';
          },
          {
            readonly familyId: 'sql';
            readonly nativeType: 'public.eql_v3_numeric_ord_ore';
            readonly targetId: 'postgres';
            readonly typeId: 'cipherstash/eql-v3/eql_v3_numeric_ord_ore@1';
          },
          {
            readonly familyId: 'sql';
            readonly nativeType: 'public.eql_v3_numeric_ord';
            readonly targetId: 'postgres';
            readonly typeId: 'cipherstash/eql-v3/eql_v3_numeric_ord@1';
          },
          {
            readonly familyId: 'sql';
            readonly nativeType: 'public.eql_v3_text';
            readonly targetId: 'postgres';
            readonly typeId: 'cipherstash/eql-v3/eql_v3_text@1';
          },
          {
            readonly familyId: 'sql';
            readonly nativeType: 'public.eql_v3_text_eq';
            readonly targetId: 'postgres';
            readonly typeId: 'cipherstash/eql-v3/eql_v3_text_eq@1';
          },
          {
            readonly familyId: 'sql';
            readonly nativeType: 'public.eql_v3_text_match';
            readonly targetId: 'postgres';
            readonly typeId: 'cipherstash/eql-v3/eql_v3_text_match@1';
          },
          {
            readonly familyId: 'sql';
            readonly nativeType: 'public.eql_v3_text_ord_ore';
            readonly targetId: 'postgres';
            readonly typeId: 'cipherstash/eql-v3/eql_v3_text_ord_ore@1';
          },
          {
            readonly familyId: 'sql';
            readonly nativeType: 'public.eql_v3_text_ord';
            readonly targetId: 'postgres';
            readonly typeId: 'cipherstash/eql-v3/eql_v3_text_ord@1';
          },
          {
            readonly familyId: 'sql';
            readonly nativeType: 'public.eql_v3_text_search';
            readonly targetId: 'postgres';
            readonly typeId: 'cipherstash/eql-v3/eql_v3_text_search@1';
          },
          {
            readonly familyId: 'sql';
            readonly nativeType: 'public.eql_v3_boolean';
            readonly targetId: 'postgres';
            readonly typeId: 'cipherstash/eql-v3/eql_v3_boolean@1';
          },
          {
            readonly familyId: 'sql';
            readonly nativeType: 'public.eql_v3_real';
            readonly targetId: 'postgres';
            readonly typeId: 'cipherstash/eql-v3/eql_v3_real@1';
          },
          {
            readonly familyId: 'sql';
            readonly nativeType: 'public.eql_v3_real_eq';
            readonly targetId: 'postgres';
            readonly typeId: 'cipherstash/eql-v3/eql_v3_real_eq@1';
          },
          {
            readonly familyId: 'sql';
            readonly nativeType: 'public.eql_v3_real_ord_ore';
            readonly targetId: 'postgres';
            readonly typeId: 'cipherstash/eql-v3/eql_v3_real_ord_ore@1';
          },
          {
            readonly familyId: 'sql';
            readonly nativeType: 'public.eql_v3_real_ord';
            readonly targetId: 'postgres';
            readonly typeId: 'cipherstash/eql-v3/eql_v3_real_ord@1';
          },
          {
            readonly familyId: 'sql';
            readonly nativeType: 'public.eql_v3_double';
            readonly targetId: 'postgres';
            readonly typeId: 'cipherstash/eql-v3/eql_v3_double@1';
          },
          {
            readonly familyId: 'sql';
            readonly nativeType: 'public.eql_v3_double_eq';
            readonly targetId: 'postgres';
            readonly typeId: 'cipherstash/eql-v3/eql_v3_double_eq@1';
          },
          {
            readonly familyId: 'sql';
            readonly nativeType: 'public.eql_v3_double_ord_ore';
            readonly targetId: 'postgres';
            readonly typeId: 'cipherstash/eql-v3/eql_v3_double_ord_ore@1';
          },
          {
            readonly familyId: 'sql';
            readonly nativeType: 'public.eql_v3_double_ord';
            readonly targetId: 'postgres';
            readonly typeId: 'cipherstash/eql-v3/eql_v3_double_ord@1';
          },
          {
            readonly familyId: 'sql';
            readonly nativeType: 'public.eql_v3_json';
            readonly targetId: 'postgres';
            readonly typeId: 'cipherstash/eql-v3/eql_v3_json@1';
          },
        ];
      };
      readonly version: '0.0.1';
    };
  };
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
