package stashgen

import (
	"fmt"
	"go/format"
	"strings"
)

// emit writes the generated file from the model. It writes gofmt-ready Go and
// runs go/format over it, so a formatting mistake is a build error here, not
// a diff in the user's repository.
func emit(f *genFile) ([]byte, error) {
	if f.imports.err != nil {
		return nil, f.imports.err
	}
	for _, g := range f.fields {
		for _, idx := range g.Indexes {
			if len(idx.Options) > 0 {
				return nil, fieldErr(f.typeName, g.GoName, "index %s: index options have no Go form yet", idx)
			}
		}
	}
	w := &writer{}
	w.header(f)
	w.encryptedType(f)
	w.printMethods(f)
	w.shape(f)
	w.opaqueShape(f)
	w.declaration(f)
	w.codec(f)
	w.functions(f)
	w.fieldEntries(f)
	for i := range f.models {
		w.model(f, &f.models[i])
	}
	src, err := format.Source(w.bytes())
	if err != nil {
		return nil, fmt.Errorf("stashgen: the generated file does not format: %w\n%s", err, w.bytes())
	}
	return src, nil
}

type writer struct {
	b strings.Builder
}

func (w *writer) bytes() []byte { return []byte(w.b.String()) }

func (w *writer) p(format string, args ...any) {
	fmt.Fprintf(&w.b, format, args...)
	w.b.WriteByte('\n')
}

func (w *writer) nl() { w.b.WriteByte('\n') }

func (w *writer) header(f *genFile) {
	w.p("// Code generated by stashgen. DO NOT EDIT.")
	w.nl()
	w.p("package %s", f.pkgName)
	w.nl()
	w.b.WriteString(f.imports.block())
	w.nl()
	w.p("// Stops compiling when the library does not accept this version of generated file.")
	w.p("const _ = gensupport.GeneratedVersion1")
	for _, n := range f.notices {
		w.nl()
		w.b.WriteString(wrapComment(n, 80))
	}
}

func tagSuffix(tags string) string {
	if tags == "" {
		return ""
	}
	return " `" + tags + "`"
}

func (w *writer) encryptedType(f *genFile) {
	w.nl()
	w.p("type %s struct {", f.encName)
	for _, m := range f.members {
		if m.embedded {
			w.p("\t%s%s", m.typeExpr, tagSuffix(m.tags))
			continue
		}
		w.p("\t%s %s%s", m.name, m.typeExpr, tagSuffix(m.tags))
	}
	w.p("}")
	for _, g := range f.fields {
		if g.Verb == VerbPassthrough || g.Verb == VerbEncryptInto {
			continue
		}
		w.nl()
		w.p("type %s struct {", g.outputType)
		for _, o := range g.outputs {
			w.p("\t%s %s", o.name, o.typeExpr)
		}
		w.p("}")
	}
}

// shownAndHidden are the arguments of Redacted: the passthrough members by
// Go name, and the sealed fields' Go names.
func shownAndHidden(f *genFile, recv string) (shown string, hidden string) {
	var entries, hiddenNames []string
	for _, m := range f.members {
		if m.embedded {
			entries = append(entries, fmt.Sprintf("%q: %s.%s", m.name, recv, m.name))
		}
	}
	for _, g := range f.fields {
		if g.via != "" {
			continue
		}
		if g.Verb == VerbPassthrough {
			entries = append(entries, fmt.Sprintf("%q: %s.%s", g.GoName, recv, g.GoName))
		} else {
			hiddenNames = append(hiddenNames, fmt.Sprintf("%q", g.GoName))
		}
	}
	if f.decl.Opaque {
		hiddenNames = []string{`"Sealed"`}
	}
	shown = "nil"
	if len(entries) > 0 {
		shown = "map[string]any{" + strings.Join(entries, ", ") + "}"
	}
	return shown, ", " + strings.Join(hiddenNames, ", ")
}

func (w *writer) printMethods(f *genFile) {
	shown, hidden := shownAndHidden(f, "e")
	w.nl()
	w.p("func (e %s) String() string {", f.encName)
	w.p("\treturn gensupport.Redacted(%q, %s%s)", f.encName, shown, hidden)
	w.p("}")
	w.nl()
	w.p("func (e %s) LogValue() slog.Value {", f.encName)
	w.p("\treturn gensupport.RedactedLog(%s%s)", shown, hidden)
	w.p("}")
	if !f.redact {
		return
	}
	r := f.redactRecv
	// On the plaintext struct the passthrough fields are the same, and the
	// sealed fields are read from the struct itself.
	shown, hidden = shownAndHidden(f, r)
	w.nl()
	w.p("// Written because of -redact: %s no longer prints its sealed fields.", f.typeName)
	w.p("func (%s %s) String() string {", r, f.typeName)
	w.p("\treturn gensupport.Redacted(%q, %s%s)", f.typeName, shown, hidden)
	w.p("}")
	w.nl()
	w.p("func (%s %s) LogValue() slog.Value {", r, f.typeName)
	w.p("\treturn gensupport.RedactedLog(%s%s)", shown, hidden)
	w.p("}")
	w.nl()
	w.p("// GoString is what %%#v prints; without it %%#v prints every field.")
	w.p("func (%s %s) GoString() string {", r, f.typeName)
	w.p("\treturn gensupport.Redacted(%q, %s%s)", f.typeName, shown, hidden)
	w.p("}")
}

// opaqueShape writes the struct an opaque value crosses the binding as: the
// struct's fields by their declared names, as one JSON document.
func (w *writer) opaqueShape(f *genFile) {
	if !f.decl.Opaque {
		return
	}
	w.nl()
	w.p("// The opaque value as it crosses the binding: one JSON document of the")
	w.p("// struct's fields, by their declared names.")
	w.p("type %s struct {", f.opaqueShape)
	for _, g := range f.opaque {
		w.p("\t%s %s `json:%q`", g.GoName, g.typeExpr, g.Name)
	}
	w.p("}")
}

func (w *writer) shape(f *genFile) {
	if f.shapeName == "" {
		return
	}
	w.nl()
	w.p("// Stops compiling when %s gains, loses, reorders or retypes a field.", f.typeName)
	w.p("var _ = %s(%s)", f.shapeName, f.shapeSource)
	w.nl()
	w.shapeStruct(f.shapeName, f.shapeFields)
	for _, e := range f.embeddedShapes {
		w.nl()
		w.p("// Stops compiling when the embedded %s gains, loses, reorders or retypes a field.", strings.TrimSuffix(e.source, "{}"))
		w.p("var _ = %s(%s)", e.name, e.source)
		w.nl()
		w.shapeStruct(e.name, e.fields)
	}
}

func (w *writer) shapeStruct(name string, fields []shapeField) {
	w.p("type %s struct {", name)
	for _, s := range fields {
		if s.embedded {
			w.p("\t%s", s.typeExpr)
		} else {
			w.p("\t%s %s", s.name, s.typeExpr)
		}
	}
	w.p("}")
}

// kindExpr is the gensupport kind of a Go type: the wire type the field
// seals as. The mapping is vcffi's: int8, int16 and int32 travel as int32,
// int and int64 as int64, the unsigned ones likewise, []byte as bytes. A
// composite is untyped and seals as one self-describing value.
func kindExpr(t GoType) string {
	switch t.Kind {
	case KindString:
		return "gensupport.String"
	case KindBool:
		return "gensupport.Bool"
	case KindBytes:
		return "gensupport.Bytes"
	case KindInt:
		switch t.Basic {
		case "int8", "int16", "int32":
			return "gensupport.Int32"
		}
		return "gensupport.Int64"
	case KindUint:
		switch t.Basic {
		case "uint8", "uint16", "uint32", "byte":
			return "gensupport.Uint32"
		}
		return "gensupport.Uint64"
	case KindFloat:
		if t.Basic == "float32" {
			return "gensupport.Float32"
		}
		return "gensupport.Float64"
	}
	return "gensupport.Untyped"
}

func indexExpr(idx Index) string {
	switch idx.Name {
	case IndexMatch, IndexJSON:
		return "encrypt." + idx.Name.GoName() + "()"
	}
	return "encrypt." + idx.Name.GoName()
}

func (w *writer) declaration(f *genFile) {
	w.nl()
	if f.decl.Opaque {
		w.p("var %s = gensupport.DeclareOpaque(%q)", f.declVar, f.decl.Context)
		return
	}
	w.p("var %s = gensupport.Declare(%q).", f.declVar, f.decl.Context)
	for i, fld := range f.decl.Fields {
		end := "."
		if i == len(f.decl.Fields)-1 && fld.Identity == "" {
			end = ""
		}
		switch fld.Verb {
		case VerbOmit:
			w.p("\tOmit(%q)%s", fld.Name, end)
		case VerbPassthrough:
			w.p("\tPassthrough(%q)%s", fld.Name, end)
		case VerbEncrypt:
			w.p("\tEncrypt(%q, %s)%s", fld.Name, kindExpr(fld.GoType), end)
		case VerbEncryptInto:
			w.p("\tEncryptInto(%q, %s, %q)%s", fld.Name, kindExpr(fld.GoType), fld.EQLType, end)
		case VerbEncryptIndex, VerbIndex:
			call := "EncryptIndex"
			if fld.Verb == VerbIndex {
				call = "Index"
			}
			args := make([]string, len(fld.Indexes))
			for n, idx := range fld.Indexes {
				args[n] = indexExpr(idx)
			}
			w.p("\t%s(%q, %s, %s)%s", call, fld.Name, kindExpr(fld.GoType), strings.Join(args, ", "), end)
		}
		if fld.Identity != "" {
			end = "."
			if i == len(f.decl.Fields)-1 {
				end = ""
			}
			w.p("\tIdentity(%q, %q)%s", fld.Name, fld.Identity, end)
		}
	}
}

// literal writes a composite literal: one line with one entry, one entry per
// line otherwise.
func (w *writer) literal(indent, open string, entries []string, close string) {
	if len(entries) <= 1 {
		w.p("%s%s%s%s", indent, open, strings.Join(entries, ""), close)
		return
	}
	w.p("%s%s", indent, open)
	for _, e := range entries {
		w.p("%s\t%s,", indent, e)
	}
	w.p("%s%s", indent, close)
}

func (w *writer) codec(f *genFile) {
	w.nl()
	w.p("var %s = gensupport.New(gensupport.Generated[%s, %s]{", f.codecVar, f.typeExpr, f.encName)
	w.p("\tTypeName: %q,", f.typeName)
	w.p("\tDeclaration: %s,", f.declVar)
	if f.printsPlaintext {
		w.p("\tPrintsPlaintext: true,")
	}
	if len(f.unexported) > 0 {
		quoted := make([]string, len(f.unexported))
		for i, u := range f.unexported {
			quoted[i] = fmt.Sprintf("%q", u)
		}
		w.p("\tUnexported: []string{%s},", strings.Join(quoted, ", "))
	}
	w.source(f)
	w.seal(f)
	w.open(f)
	w.value(f)
	w.p("})")
}

func (w *writer) source(f *genFile) {
	w.p("\tSource: func(v %s) gensupport.Values {", f.typeExpr)
	if f.isPointer {
		// A nil element is reported by Encrypt, not a panic here.
		w.p("\t\tif v == nil {")
		w.p("\t\t\treturn nil")
		w.p("\t\t}")
	}
	if f.decl.Opaque {
		entries := make([]string, len(f.opaque))
		for i, g := range f.opaque {
			entries[i] = fmt.Sprintf("%s: v.%s", g.GoName, g.GoName)
		}
		w.literal("\t\t", "return gensupport.Values{gensupport.OpaqueField: "+f.opaqueShape+"{", entries, "}}")
	} else {
		entries := make([]string, len(f.fields))
		for i, g := range f.fields {
			entries[i] = fmt.Sprintf("%q: v.%s", g.Name, g.GoName)
		}
		w.literal("\t\t", "return gensupport.Values{", entries, "}")
	}
	w.p("\t},")
}

// seal writes Seal: the passthrough fields first, each with its error check,
// then the sealed fields in declared order.
func (w *writer) seal(f *genFile) {
	w.p("\tSeal: func(rec gensupport.Record) (%s, error) {", f.encName)
	if f.decl.Opaque {
		w.p("\t\treturn %s{Sealed: rec[gensupport.OpaqueField].Ciphertext}, nil", f.encName)
		w.p("\t},")
		return
	}
	w.p("\t\tvar e %s", f.encName)
	hasPassthrough := false
	for _, g := range f.fields {
		if g.Verb == VerbPassthrough {
			hasPassthrough = true
		}
	}
	if hasPassthrough {
		w.p("\t\tvar err error")
	}
	for _, g := range f.fields {
		if g.Verb != VerbPassthrough {
			continue
		}
		w.p("\t\tif e.%s, err = gensupport.Passthrough[%s](rec, %q); err != nil {", g.GoName, g.typeExpr, g.Name)
		w.p("\t\t\treturn %s{}, err", f.encName)
		w.p("\t\t}")
	}
	for _, g := range f.fields {
		switch g.Verb {
		case VerbPassthrough:
		case VerbEncryptInto:
			w.p("\t\te.%s = %s(rec[%q].EQL)", g.GoName, g.outputType, g.Name)
		default:
			entries := make([]string, len(g.outputs))
			for i, o := range g.outputs {
				entries[i] = fmt.Sprintf("%s: rec[%q].%s", o.name, g.Name, o.name)
			}
			w.literal("\t\t", fmt.Sprintf("e.%s = %s{", g.GoName, g.outputType), entries, "}")
		}
	}
	w.p("\t\treturn e, nil")
	w.p("\t},")
}

func (w *writer) open(f *genFile) {
	w.p("\tOpen: func(e %s) gensupport.Record {", f.encName)
	if f.decl.Opaque {
		w.p("\t\treturn gensupport.Record{gensupport.OpaqueField: {Ciphertext: e.Sealed}}")
		w.p("\t},")
		return
	}
	entries := make([]string, len(f.fields))
	for i, g := range f.fields {
		switch g.Verb {
		case VerbPassthrough:
			entries[i] = fmt.Sprintf("%q: {Value: e.%s}", g.Name, g.GoName)
		case VerbEncryptInto:
			entries[i] = fmt.Sprintf("%q: {EQL: e.%s}", g.Name, g.GoName)
		default:
			parts := make([]string, len(g.outputs))
			for n, o := range g.outputs {
				parts[n] = fmt.Sprintf("%s: e.%s.%s", o.name, g.GoName, o.name)
			}
			entries[i] = fmt.Sprintf("%q: {%s}", g.Name, strings.Join(parts, ", "))
		}
	}
	w.literal("\t\t", "return gensupport.Record{", entries, "}")
	w.p("\t},")
}

func (w *writer) value(f *genFile) {
	w.p("\tValue: func(e %s, vals gensupport.Values) (%s, error) {", f.encName, f.typeExpr)
	fail := func() { w.p("\t\t\treturn %s, err", f.zeroExpr) }
	switch {
	case f.decl.Opaque:
		w.p("\t\tvar o %s", f.opaqueShape)
		w.p("\t\tif err := gensupport.Opaque(vals, &o); err != nil {")
		fail()
		w.p("\t\t}")
		if f.isPointer {
			w.p("\t\tv := &%s{}", strings.TrimPrefix(f.typeExpr, "*"))
		} else {
			w.p("\t\tvar v %s", f.typeExpr)
		}
		for _, g := range f.opaque {
			w.p("\t\tv.%s = o.%s", g.GoName, g.GoName)
		}
	default:
		if f.isPointer {
			w.p("\t\tv := &%s{}", strings.TrimPrefix(f.typeExpr, "*"))
		} else {
			w.p("\t\tvar v %s", f.typeExpr)
		}
		w.p("\t\tvar err error")
		for _, g := range f.fields {
			if g.Verb == VerbIndex {
				// An index-only field stores no ciphertext, so nothing opens
				// for it: the struct gets the field's zero value.
				continue
			}
			if g.Sealed() && g.definedScalar() {
				// The engine returns the underlying type; the conversion
				// to the defined type is the struct's own.
				w.p("\t\traw%s, err := gensupport.Get[%s](vals, %q)", g.GoName, g.GoType.Basic, g.Name)
				w.p("\t\tif err != nil {")
				fail()
				w.p("\t\t}")
				w.p("\t\tv.%s = %s(raw%s)", g.GoName, g.typeExpr, g.GoName)
				continue
			}
			w.p("\t\tif v.%s, err = gensupport.Get[%s](vals, %q); err != nil {", g.GoName, g.typeExpr, g.Name)
			fail()
			w.p("\t\t}")
		}
	}
	w.p("\t\treturn v, nil")
	w.p("\t},")
}

func (w *writer) functions(f *genFile) {
	w.nl()
	w.b.WriteString(wrapComment(fmt.Sprintf("%s seals each %s, with one ZeroKMS request for each 500 sealed values, plus one the first time a keyset is used. The result has one element for each input, in the same order.", f.encryptFn, f.typeName), 80))
	w.p("func %s(ctx context.Context, cipher *encrypt.Cipher, %s []%s) ([]%s, error) {", f.encryptFn, f.paramName, f.typeExpr, f.encName)
	w.p("\treturn %s.Encrypt(ctx, cipher, %s)", f.codecVar, f.paramName)
	w.p("}")
	w.nl()
	w.b.WriteString(wrapComment(fmt.Sprintf("%s opens each %s, with one ZeroKMS request for each 500 sealed values, plus one the first time a keyset is used.", f.decryptFn, f.encName), 80))
	var indexOnly []string
	for _, g := range f.fields {
		if g.Verb == VerbIndex {
			indexOnly = append(indexOnly, g.GoName)
		}
	}
	if len(indexOnly) > 0 {
		// Read, change and save is the usual update, and it would store the
		// term for zero: say so on the function a program calls.
		w.p("//")
		w.b.WriteString(wrapComment(fmt.Sprintf("%s leaves %s at the zero value: an index-only field stores no ciphertext, so nothing opens for it. Do not pass a decrypted value back to %s to update its row, because %s would then store the term for zero. Derive the index-only terms again from the real values through %s.",
			f.decryptFn, joinNames(indexOnly), f.encryptFn, f.encryptFn, f.fieldsVar), 80))
	}
	w.p("func %s(ctx context.Context, d encrypt.Decrypter, encrypted []%s) ([]%s, error) {", f.decryptFn, f.encName, f.typeExpr)
	w.p("\treturn %s.Decrypt(ctx, d, encrypted)", f.codecVar)
	w.p("}")
}

func (w *writer) fieldEntries(f *genFile) {
	var sealed []genField
	for _, g := range f.fields {
		if g.Sealed() {
			sealed = append(sealed, g)
		}
	}
	if len(sealed) == 0 {
		return
	}
	w.nl()
	w.p("var %s = struct {", f.fieldsVar)
	for _, g := range sealed {
		w.p("\t%s %s", g.GoName, g.fieldType)
	}
	w.p("}{")
	for _, g := range sealed {
		w.p("\t%s: %s{gensupport.NewField[%s](%s, %q)},", g.GoName, g.fieldType, g.typeExpr, f.declVar, g.Name)
	}
	w.p("}")
	for _, g := range sealed {
		w.nl()
		w.p("type %s struct {", g.fieldType)
		w.p("\tfield gensupport.Field[%s]", g.typeExpr)
		w.p("}")
		w.nl()
		w.p("func (f %s) Encrypt(ctx context.Context, c *encrypt.Cipher, v %s) (%s, error) {", g.fieldType, g.typeExpr, g.outputType)
		switch {
		case g.Verb == VerbEncryptInto:
			w.p("\tout, err := f.field.Encrypt(ctx, c, v)")
			w.p("\treturn %s(out.EQL), err", g.outputType)
		case len(g.outputs) == 1:
			w.p("\tout, err := f.field.Encrypt(ctx, c, v)")
			w.p("\treturn %s{%s: out.%s}, err", g.outputType, g.outputs[0].name, g.outputs[0].name)
		default:
			w.p("\tout, err := f.field.Encrypt(ctx, c, v)")
			w.p("\tif err != nil {")
			w.p("\t\treturn %s{}, err", g.outputType)
			w.p("\t}")
			parts := make([]string, len(g.outputs))
			for i, o := range g.outputs {
				parts[i] = fmt.Sprintf("%s: out.%s", o.name, o.name)
			}
			w.p("\treturn %s{%s}, nil", g.outputType, strings.Join(parts, ", "))
		}
		w.p("}")
		if g.queryType != "" {
			w.nl()
			w.p("func (f %s) Query(ctx context.Context, c *encrypt.Cipher, v %s) (%s, error) {", g.fieldType, g.typeExpr, g.queryType)
			w.p("\tout, err := f.field.Query(ctx, c, v)")
			w.p("\treturn %s(out.EQL), err", g.queryType)
			w.p("}")
		}
		for _, o := range g.outputs {
			if o.index == "" {
				continue
			}
			w.nl()
			w.p("func (f %s) %s(ctx context.Context, c *encrypt.Cipher, v %s) (%s, error) {", g.fieldType, o.name, g.typeExpr, o.typeExpr)
			w.p("\treturn f.field.%s(ctx, c, v)", o.name)
			w.p("}")
		}
	}
}

func (w *writer) model(f *genFile, m *genModel) {
	w.nl()
	w.p("// The -model flag: %s converts to and from its shape only while the", m.typeExpr)
	w.p("// two have the same fields, with the same types, in the same order.")
	w.p("type %s struct {", m.shapeName)
	for _, mf := range m.fields {
		w.p("\t%s %s", mf.name, mf.typeExpr)
	}
	w.p("}")
	w.nl()
	w.p("var %s = gensupport.Records(%s,", m.codecVar, f.codecVar)
	w.p("\tfunc(e %s) %s {", f.encName, m.typeExpr)
	var entries []string
	for _, mf := range m.fields {
		if mf.source != "" {
			entries = append(entries, fmt.Sprintf("%s: %s", mf.name, mf.source))
		}
	}
	w.literal("\t\t", fmt.Sprintf("return %s(%s{", m.typeExpr, m.shapeName), entries, "})")
	w.p("\t},")
	w.p("\tfunc(r %s) %s {", m.typeExpr, f.encName)
	w.p("\t\ts := %s(r)", m.shapeName)
	entries = entries[:0]
	for _, g := range f.fields {
		switch g.Verb {
		case VerbPassthrough, VerbEncryptInto:
			entries = append(entries, fmt.Sprintf("%s: s.%s", g.GoName, m.fieldFor(&g, &g.outputs[0])))
		default:
			parts := make([]string, len(g.outputs))
			for i := range g.outputs {
				parts[i] = fmt.Sprintf("%s: s.%s", g.outputs[i].name, m.fieldFor(&g, &g.outputs[i]))
			}
			entries = append(entries, fmt.Sprintf("%s: %s{%s}", g.GoName, g.outputType, strings.Join(parts, ", ")))
		}
	}
	w.literal("\t\t", fmt.Sprintf("return %s{", f.encName), entries, "}")
	w.p("\t},")
	w.p(")")
	w.nl()
	w.p("func %s(ctx context.Context, cipher *encrypt.Cipher, %s []%s) ([]%s, error) {", m.encryptFn, f.paramName, f.typeExpr, m.typeExpr)
	w.p("\treturn %s.Encrypt(ctx, cipher, %s)", m.codecVar, f.paramName)
	w.p("}")
	w.nl()
	w.p("func %s(ctx context.Context, d encrypt.Decrypter, %s []%s) ([]%s, error) {", m.decryptFn, m.paramName, m.typeExpr, f.typeExpr)
	w.p("\treturn %s.Decrypt(ctx, d, %s)", m.codecVar, m.paramName)
	w.p("}")
}

// fieldFor is the model field bound to one output.
func (m *genModel) fieldFor(g *genField, out *output) string {
	for _, mf := range m.fields {
		if mf.field != nil && mf.field.Name == g.Name && mf.output != nil && mf.output.name == out.name {
			return mf.name
		}
	}
	return "/* unbound " + g.Name + " */"
}

// joinNames lists Go names in prose: "A", "A and B", "A, B and C".
func joinNames(names []string) string {
	switch len(names) {
	case 0:
		return ""
	case 1:
		return names[0]
	}
	return strings.Join(names[:len(names)-1], ", ") + " and " + names[len(names)-1]
}
