//! Generator binary that produces `index.d.ts` by combining Specta's structured
//! type information with field-level doc comments extracted from Rust source via
//! `syn`. This produces:
//!
//! - `export class DeviceCodeResult` with `readonly` properties and method
//!   signatures (with JSDoc for `pollForToken()` and `openInBrowser()`)
//! - `export interface TokenResult` with per-field JSDoc
//!
//! Run via: `cargo run --bin generate-types`

use std::collections::HashMap;
use std::fs;
use std::path::Path;

use stack_auth::{PendingDeviceCode, Token};
use regex::Regex;
use specta::ts;
use specta::{DefOpts, NamedType, TypeDefs};

fn main() {
    let manifest_dir = Path::new(env!("CARGO_MANIFEST_DIR"));
    let crate_src = manifest_dir.join("../src");

    // expires_in is u64 in Rust but always a safe integer in practice, so
    // export it as `number` rather than `bigint`.
    let config = ts::ExportConfiguration::default().bigint(ts::BigIntExportBehavior::Number);

    // Parse Rust source files to extract field-level doc comments.
    let device_code_src = fs::read_to_string(crate_src.join("device_code/mod.rs"))
        .expect("Failed to read device_code/mod.rs");
    let lib_src = fs::read_to_string(crate_src.join("lib.rs")).expect("Failed to read lib.rs");

    let device_code_docs = extract_field_docs(&device_code_src, "PendingDeviceCode");
    let token_docs = extract_field_docs(&lib_src, "Token");

    // Build rich TypeScript declarations from Specta metadata + syn doc comments.
    let device_code_class = build_class::<PendingDeviceCode>(&device_code_docs, &config);
    let token_iface = build_interface::<Token>(&token_docs, &config);

    let mut out = String::new();

    out.push_str("// This file is auto-generated by `generate-types`. Do not edit by hand.\n");
    out.push_str("// Regenerate with: npm run generate-types\n\n");

    // -----------------------------------------------------------------------
    // Specta-generated type definitions (from the cts-auth crate)
    // -----------------------------------------------------------------------

    out.push_str(&device_code_class);
    out.push_str("\n\n");
    out.push_str(&token_iface);
    out.push_str("\n\n");

    // -----------------------------------------------------------------------
    // Hand-written error types (better TSDoc control per variant)
    // -----------------------------------------------------------------------

    out.push_str(
        r#"/**
 * Machine-readable error codes attached to {@link AuthError}.
 *
 * - `"REQUEST_ERROR"` — The HTTP request to the auth server failed (network error, timeout, etc.).
 * - `"ACCESS_DENIED"` — The user explicitly denied authorization.
 * - `"EXPIRED_TOKEN"` — The device code expired before the user authorized.
 * - `"INVALID_GRANT"` — The grant type is invalid or the device code was already used.
 * - `"INVALID_CLIENT"` — The `clientId` is not recognized by the auth server.
 * - `"INVALID_URL"` — A URL argument could not be parsed.
 * - `"INVALID_REGION"` — The `region` string does not match a known CipherStash region.
 * - `"SERVER_ERROR"` — The auth server returned an unexpected error.
 */
export type AuthErrorCode =
  | "REQUEST_ERROR"
  | "ACCESS_DENIED"
  | "EXPIRED_TOKEN"
  | "INVALID_GRANT"
  | "INVALID_CLIENT"
  | "INVALID_URL"
  | "INVALID_REGION"
  | "SERVER_ERROR";

/**
 * Error thrown by all functions in this module.
 *
 * Extends the built-in `Error` with a machine-readable {@link AuthErrorCode}
 * so callers can branch on `err.code` without parsing the message string.
 */
export interface AuthError extends Error {
  code: AuthErrorCode;
}
"#,
    );

    out.push('\n');

    // -----------------------------------------------------------------------
    // Function declarations with TSDoc
    // -----------------------------------------------------------------------

    out.push_str(
        r#"/**
 * Begin the OAuth 2.0 Device Authorization flow.
 *
 * Contacts the CipherStash auth server for the given region and returns a
 * {@link DeviceCodeResult} with a user code, verification URL, and methods
 * to complete the authorization flow.
 *
 * @param region - CipherStash region identifier (e.g. `"ap-southeast-2"`).
 * @param clientId - OAuth client ID issued by CipherStash.
 * @returns A promise that resolves with the device code result.
 * @throws {AuthError} `INVALID_REGION` — the region string is not recognized.
 * @throws {AuthError} `INVALID_CLIENT` — the client ID is not recognized.
 * @throws {AuthError} `REQUEST_ERROR` — the HTTP request to the auth server failed.
 * @throws {AuthError} `SERVER_ERROR` — the auth server returned an unexpected error.
 *
 * @example
 * ```ts
 * import { beginDeviceCodeFlow } from "@cipherstash/cts-auth";
 *
 * // 1. Start the flow
 * const result = await beginDeviceCodeFlow("ap-southeast-2", MY_CLIENT_ID);
 * console.log(`Enter code ${result.userCode} at ${result.verificationUri}`);
 *
 * // 2. Optionally open the browser for the user
 * result.openInBrowser();
 *
 * // 3. Poll until the user authorizes (or the code expires)
 * const token = await result.pollForToken();
 * console.log(`Access token: ${token.accessToken}`);
 * ```
 */
export function beginDeviceCodeFlow(
  region: string,
  clientId: string,
): Promise<DeviceCodeResult>;

/**
 * Variant of {@link beginDeviceCodeFlow} that targets a custom auth server URL.
 *
 * Intended for **testing only** — requires the crate to be built with the
 * `test-utils` Cargo feature.
 *
 * @param region - CipherStash region identifier (e.g. `"ap-southeast-2"`).
 * @param clientId - OAuth client ID issued by CipherStash.
 * @param baseUrl - Base URL of the auth server to use instead of the default.
 * @returns A promise that resolves with the device code result.
 * @throws {AuthError} `INVALID_REGION` — the region string is not recognized.
 * @throws {AuthError} `INVALID_URL` — the base URL could not be parsed.
 * @throws {AuthError} `INVALID_CLIENT` — the client ID is not recognized.
 * @throws {AuthError} `REQUEST_ERROR` — the HTTP request to the auth server failed.
 * @throws {AuthError} `SERVER_ERROR` — the auth server returned an unexpected error.
 */
export function beginDeviceCodeFlowWithBaseUrl(
  region: string,
  clientId: string,
  baseUrl: string,
): Promise<DeviceCodeResult>;
"#,
    );

    // -----------------------------------------------------------------------
    // Write to index.d.ts in the package root
    // -----------------------------------------------------------------------

    let dest = manifest_dir.join("index.d.ts");

    fs::write(&dest, &out).unwrap_or_else(|e| panic!("Failed to write {}: {e}", dest.display()));

    println!("Wrote {}", dest.display());
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/// Parse a Rust source file with `syn` and extract doc comments from the fields
/// of the given struct. Returns a map from field name (snake_case) to the
/// trimmed doc comment text.
fn extract_field_docs(source: &str, struct_name: &str) -> HashMap<String, String> {
    let file = syn::parse_file(source).expect("Failed to parse Rust source");
    let mut docs = HashMap::new();

    for item in &file.items {
        let syn::Item::Struct(s) = item else {
            continue;
        };
        if s.ident != struct_name {
            continue;
        }

        let syn::Fields::Named(fields) = &s.fields else {
            continue;
        };
        for field in &fields.named {
            let Some(ident) = &field.ident else {
                continue;
            };

            let doc_lines: Vec<String> = field
                .attrs
                .iter()
                .filter_map(|attr| {
                    if !attr.path().is_ident("doc") {
                        return None;
                    }
                    let syn::Meta::NameValue(nv) = &attr.meta else {
                        return None;
                    };
                    let syn::Expr::Lit(lit) = &nv.value else {
                        return None;
                    };
                    let syn::Lit::Str(s) = &lit.lit else {
                        return None;
                    };
                    Some(s.value())
                })
                .collect();

            if !doc_lines.is_empty() {
                let combined = doc_lines
                    .iter()
                    .map(|l| l.strip_prefix(' ').unwrap_or(l))
                    .collect::<Vec<_>>()
                    .join("\n");
                docs.insert(ident.to_string(), combined.trim().to_string());
            }
        }
        break; // Found the struct, no need to continue.
    }

    docs
}

/// Convert Rust intra-doc links (`` [`text`](Rust::path) ``) to TSDoc
/// `{@link text}` references.
fn convert_rust_doc_links(doc: &str) -> String {
    let re = Regex::new(r"\[`([^`]+)`\]\([^)]+\)").expect("invalid regex");
    re.replace_all(doc, "{@link $1}").to_string()
}

/// Convert `camelCase` to `snake_case`.
fn to_snake_case(s: &str) -> String {
    let mut result = String::new();
    for (i, c) in s.chars().enumerate() {
        if c.is_uppercase() && i > 0 {
            result.push('_');
        }
        result.extend(c.to_lowercase());
    }
    result
}

/// Build a multi-line TypeScript `export class` declaration from Specta
/// metadata and syn-extracted field doc comments. Properties are `readonly`
/// and class methods (`pollForToken`, `openInBrowser`) are appended.
fn build_class<T: NamedType>(
    field_docs: &HashMap<String, String>,
    config: &ts::ExportConfiguration,
) -> String {
    let mut type_defs = TypeDefs::default();
    let named = T::definition_named_data_type(DefOpts {
        parent_inline: false,
        type_map: &mut type_defs,
    })
    .expect("Failed to get named data type");

    let ts_name = named.name;

    let mut out = String::new();

    // Struct-level JSDoc from Specta's comments (originally `///` on the struct).
    if !named.comments.is_empty() {
        out.push_str("/**\n");
        for comment in named.comments {
            let line = comment.strip_prefix(' ').unwrap_or(comment);
            if line.is_empty() {
                out.push_str(" *\n");
            } else {
                let converted = convert_rust_doc_links(line);
                out.push_str(&format!(" * {converted}\n"));
            }
        }
        out.push_str(" */\n");
    }

    out.push_str(&format!("export class {ts_name} {{\n"));

    // Extract object fields.
    let fields = match &named.item {
        specta::NamedDataTypeItem::Object(obj) => &obj.fields,
        _ => panic!("{ts_name} is not an object type"),
    };

    for field in fields {
        let key = field.key;
        let snake_key = to_snake_case(key);

        if let Some(doc) = field_docs.get(&snake_key) {
            let converted = convert_rust_doc_links(doc);
            out.push_str(&format!("  /** {converted} */\n"));
        }

        let ts_type = ts::datatype(config, &field.ty)
            .unwrap_or_else(|e| panic!("Failed to convert field {key}: {e}"));

        out.push_str(&format!("  readonly {key}: {ts_type};\n"));
    }

    // Class methods
    out.push_str(
        r#"
  /**
   * Poll the auth server until the user completes authorization.
   *
   * **Consumes** the internal handle — it cannot be reused after this call.
   * If you need to open the browser, call {@link openInBrowser} *before*
   * `pollForToken`.
   *
   * @returns A promise that resolves with the access token details.
   * @throws {AuthError} `EXPIRED_TOKEN` — the device code expired before the user authorized.
   * @throws {AuthError} `ACCESS_DENIED` — the user denied authorization.
   * @throws {AuthError} `INVALID_GRANT` — the grant type is invalid or the code was already used.
   * @throws {AuthError} `REQUEST_ERROR` — the HTTP request to the auth server failed.
   * @throws {AuthError} `SERVER_ERROR` — the auth server returned an unexpected error.
   */
  pollForToken(): Promise<TokenResult>;

  /**
   * Open the verification URI in the user's default browser.
   *
   * Does **not** consume the handle — you can still call {@link pollForToken}
   * afterwards.
   *
   * @returns `true` if the browser was launched successfully, `false` otherwise.
   */
  openInBrowser(): boolean;
"#,
    );

    out.push('}');
    out
}

/// Build a multi-line TypeScript `export interface` declaration from Specta
/// metadata and syn-extracted field doc comments.
fn build_interface<T: NamedType>(
    field_docs: &HashMap<String, String>,
    config: &ts::ExportConfiguration,
) -> String {
    let mut type_defs = TypeDefs::default();
    let named = T::definition_named_data_type(DefOpts {
        parent_inline: false,
        type_map: &mut type_defs,
    })
    .expect("Failed to get named data type");

    let ts_name = named.name;

    let mut out = String::new();

    // Struct-level JSDoc from Specta's comments (originally `///` on the struct).
    if !named.comments.is_empty() {
        out.push_str("/**\n");
        for comment in named.comments {
            let line = comment.strip_prefix(' ').unwrap_or(comment);
            if line.is_empty() {
                out.push_str(" *\n");
            } else {
                let converted = convert_rust_doc_links(line);
                out.push_str(&format!(" * {converted}\n"));
            }
        }
        out.push_str(" */\n");
    }

    out.push_str(&format!("export interface {ts_name} {{\n"));

    // Extract object fields.
    let fields = match &named.item {
        specta::NamedDataTypeItem::Object(obj) => &obj.fields,
        _ => panic!("{ts_name} is not an object type"),
    };

    for field in fields {
        let key = field.key;
        let snake_key = to_snake_case(key);

        if let Some(doc) = field_docs.get(&snake_key) {
            let converted = convert_rust_doc_links(doc);
            out.push_str(&format!("  /** {converted} */\n"));
        }

        let ts_type = ts::datatype(config, &field.ty)
            .unwrap_or_else(|e| panic!("Failed to convert field {key}: {e}"));

        let optional = if field.optional { "?" } else { "" };
        out.push_str(&format!("  {key}{optional}: {ts_type};\n"));
    }

    out.push('}');
    out
}
