import { existsSync } from 'node:fs'
import { readdir, readFile, writeFile } from 'node:fs/promises'
import { join, resolve } from 'node:path'

/**
 * The encrypted column types this rewrite applies to: the single EQL v2 type,
 * and the whole EQL v3 concrete-domain family (`eql_v3_text_search`,
 * `eql_v3_integer_ord`, …). The v3 side is matched by shape rather than by an
 * enumerated list so a newly added domain is covered without touching this file
 * — the `eql_v3_` prefix is unambiguous in a `SET DATA TYPE` position.
 *
 * v2 stays matched even though the wizard now scaffolds v3 exclusively: a user's
 * migration directory can hold files generated against an older stack version,
 * and existing v2 ciphertext stays valid — we still want their ALTER-to-encrypted
 * statements repaired.
 */
const ENCRYPTED_DOMAIN = String.raw`eql_v2_encrypted|eql_v3_[a-z0-9_]+`

/**
 * Extracts the bare domain name out of whichever mangled form matched. Derived
 * from {@link ENCRYPTED_DOMAIN} so the two can never drift out of sync — a new
 * domain added to the alternation is extracted here for free.
 */
const DOMAIN_RE = new RegExp(ENCRYPTED_DOMAIN, 'i')

/**
 * The mangled forms drizzle-kit emits for a customType in an ALTER COLUMN.
 *
 * drizzle-kit's ALTER COLUMN path wraps the customType `dataType()` return
 * value in double-quotes and prepends `"{typeSchema}".`. Custom types have no
 * `typeSchema`, so the emitted SQL depends on BOTH what `dataType()` returned
 * and which drizzle-kit renders it. Verified against 0.24.2, 0.28.1, 0.30.6,
 * 0.31.0, 0.31.1 and 0.31.10 through `drizzle-kit/api`'s `generateMigration`:
 *
 * | `dataType()` returns            | <= 0.30.6                   | >= 0.31.0                          |
 * | ------------------------------- | --------------------------- | ---------------------------------- |
 * | `eql_v3_text_search` (current)  | `eql_v3_text_search`        | `"undefined"."eql_v3_text_search"` |
 * | `public.eql_v3_text_search`     | `public.eql_v3_text_search` | `"undefined"."public.eql_v3_…"`    |
 * | `"public"."eql_v2_encrypted"`   | `"public"."eql_v2_…"`       | `"undefined".""public"."eql_v2_…"` |
 *
 * The `"undefined".` prefix is a **0.31.0-and-later** behaviour — 0.30.6 and
 * earlier emit the plain form. All six forms stay matched because a user's
 * migration directory can hold files generated by any drizzle-kit version
 * against any stack version — including the qualified `public.eql_v3_*` that
 * stack emitted before the unqualified fix.
 *
 * Ordered longest-first so the alternation cannot match a prefix of a longer
 * form and leave a trailing fragment behind.
 *
 * NOTE: this file is the sibling of `packages/cli/src/commands/db/rewrite-migrations.ts`,
 * which cli's `stash eql migration --drizzle` uses. Both are tightly coupled to
 * drizzle-kit's output format — if drizzle-kit changes, both need updating
 * together. Keep them in sync.
 */
const MANGLED_TYPE_FORMS = [
  String.raw`"undefined"\.""public"\."(?:${ENCRYPTED_DOMAIN})""`,
  String.raw`"undefined"\."public\.(?:${ENCRYPTED_DOMAIN})"`,
  String.raw`"undefined"\."(?:${ENCRYPTED_DOMAIN})"`,
  String.raw`"public"\."(?:${ENCRYPTED_DOMAIN})"`,
  String.raw`public\.(?:${ENCRYPTED_DOMAIN})`,
  // Not emitted by any released drizzle-kit ALTER path, but it is the shape the
  // CREATE TABLE path renders — guard it in case ALTER converges on it.
  String.raw`"(?:${ENCRYPTED_DOMAIN})"`,
  String.raw`(?:${ENCRYPTED_DOMAIN})`,
].join('|')

/**
 * Matches drizzle-kit's generated in-place type change to an encrypted column
 * type, in any of the forms above.
 *
 * Captures:
 * - $1: table name, OR the schema when a qualifier follows (both without quotes)
 * - $2: table name when schema-qualified (`"app"."users"`), else undefined
 * - $3: column name (without quotes)
 * - $4: the mangled type blob — feed it to {@link DOMAIN_RE} for the bare name
 *
 * The optional `(?:\."([^"]+)")?` after the first quoted name matches the
 * schema qualifier drizzle-kit emits for a `pgSchema()` table (`"app"."users"`).
 */
const ALTER_COLUMN_TO_ENCRYPTED_RE = new RegExp(
  // `\s*;` — not `[^;]*;` — so the type blob must run straight into the
  // statement terminator. drizzle-kit emits exactly that (no trailing clause),
  // and the tighter tail means a HAND-AUTHORED `SET DATA TYPE … USING <expr>;`
  // is left untouched instead of being silently rewritten (and its USING
  // discarded).
  String.raw`ALTER TABLE "([^"]+)"(?:\."([^"]+)")?\s+ALTER COLUMN "([^"]+)"\s+SET DATA TYPE (${MANGLED_TYPE_FORMS})\s*;`,
  'gi',
)

/**
 * A deliberately BROAD scan for statements that look like an in-place change to
 * an encrypted column but that the strict {@link ALTER_COLUMN_TO_ENCRYPTED_RE}
 * did not rewrite — a hand-authored `SET DATA TYPE … USING …;`, or some future
 * drizzle-kit form the strict matcher doesn't yet cover.
 *
 * It matches any single (`;`-terminated) statement that contains both
 * `SET DATA TYPE` and an `eql_v2`/`eql_v3` domain token at a word boundary (so
 * lookalikes like `eql_v4_…` or `not_eql_v3_…` don't trip it). Run AFTER the
 * strict rewrite so genuinely-rewritten statements — which no longer contain
 * `SET DATA TYPE` — are already gone; whatever this still finds is a near-miss
 * we flag for human review rather than silently ship as broken SQL.
 */
const NEAR_MISS_RE =
  /[^;]*?\bSET\s+DATA\s+TYPE\b[^;]*?\beql_v[23][a-z0-9_]*[^;]*?;/gi

/**
 * Blank lines and `--` line comments (including drizzle-kit's
 * `--> statement-breakpoint`) at the head of a {@link NEAR_MISS_RE} match.
 *
 * That regex opens with a lazy `[^;]*?`, whose only left boundary is the
 * previous `;` — or the start of the file when there is no preceding statement.
 * So the raw match drags in every comment and blank line since then, and a
 * near-miss in a file that opens with a comment block gets reported to the user
 * with that whole block glued to its front. Strip the preamble so the statement
 * we quote back reads as the offending statement alone.
 *
 * Only line comments are handled — `/* … *\/` block comments are not something
 * drizzle-kit emits, and a stray one costs cosmetics, not correctness.
 */
const STATEMENT_PREAMBLE_RE = /^(?:[^\S\n]*(?:--[^\n]*)?\n)+/

/** Drop the leading blank/comment lines a `[^;]*?`-anchored match dragged in. */
function trimStatementPreamble(statement: string): string {
  return statement.replace(STATEMENT_PREAMBLE_RE, '').trim()
}

/** A statement the sweep recognised as ALTER-to-encrypted but did NOT rewrite. */
export interface SkippedAlter {
  /** Absolute path of the migration file the statement lives in. */
  file: string
  /** The offending statement, verbatim (trimmed), for the user to review. */
  statement: string
}

/** Outcome of a sweep: the files rewritten, and near-misses left for review. */
export interface RewriteResult {
  /** Absolute paths of files whose unsafe ALTER COLUMN(s) were rewritten. */
  rewritten: string[]
  /** Near-miss statements the strict matcher passed over — flag, don't guess. */
  skipped: SkippedAlter[]
}

/**
 * Replace in-place `ALTER COLUMN ... SET DATA TYPE <encrypted domain>`
 * statements with an ADD + DROP + RENAME sequence.
 *
 * **Why this exists (CIP-2991, CIP-2994, #693):** Postgres has no implicit cast
 * from `text`/`numeric` to an encrypted domain, so `ALTER COLUMN ... SET DATA
 * TYPE eql_v2_encrypted` (or any `eql_v3_*` domain) fails at migrate time with
 * `cannot cast type ... to <domain>`. This applies equally to the single EQL v2
 * type and the whole EQL v3 concrete-domain family.
 *
 * The rewrite is an ADD+DROP+RENAME, which is **equivalent to DROP+ADD**: it
 * makes the column type valid but does NOT preserve the column's data. It is
 * therefore safe ONLY on an EMPTY table. On a populated table the new column
 * starts NULL and the original is dropped in the same migration, so the
 * plaintext is destroyed. The commented UPDATE is a placeholder that can never
 * become real SQL (the encrypted value is the EQL envelope produced by ZeroKMS
 * via the client — there is no expression Postgres can evaluate to fill it), so
 * a populated table must instead use the staged `stash encrypt` lifecycle
 * (add → backfill via `@cipherstash/stack`'s `encryptModel` → cutover → drop),
 * which keeps both columns alive across deploys. Each rewritten file carries a
 * header comment saying exactly this.
 *
 * Returns {@link RewriteResult}: the files rewritten, plus `skipped` near-misses
 * — statements that look like an ALTER-to-encrypted but fall outside the strict
 * matcher (a hand-authored `SET DATA TYPE … USING …;`, or a future drizzle-kit
 * form). Near-misses are left untouched on disk and surfaced non-fatally so the
 * caller can tell the user to review them, rather than silently shipping broken
 * SQL.
 */
export async function rewriteEncryptedAlterColumns(
  outDir: string,
  options: { skip?: string } = {},
): Promise<RewriteResult> {
  const entries = await readdir(outDir).catch(() => [])
  const rewritten: string[] = []
  const skipped: SkippedAlter[] = []

  for (const entry of entries) {
    if (!entry.endsWith('.sql')) continue
    const filePath = join(outDir, entry)
    if (options.skip && filePath === options.skip) continue

    const original = await readFile(filePath, 'utf-8')

    // Reset the regex's lastIndex — it's stateful on /g
    ALTER_COLUMN_TO_ENCRYPTED_RE.lastIndex = 0

    const updated = original.replace(
      ALTER_COLUMN_TO_ENCRYPTED_RE,
      (
        match: string,
        first: string,
        second: string | undefined,
        column: string,
        mangledType: string,
      ) => {
        // When schema-qualified (`"app"."users"`) the first capture is the
        // schema and the second is the table; otherwise the first is the table.
        const schema = second === undefined ? undefined : first
        const table = second === undefined ? first : second
        const domain = DOMAIN_RE.exec(mangledType)?.[0]?.toLowerCase()
        // Unreachable — the outer regex only matches when a domain is present —
        // but leave the statement alone rather than emit a broken rewrite.
        if (!domain) return match
        return renderSafeAlter(table, column, domain, schema)
      },
    )

    if (updated !== original) {
      await writeFile(filePath, updated, 'utf-8')
      rewritten.push(filePath)
    }

    // Broad secondary scan on the POST-rewrite content: anything still carrying
    // `SET DATA TYPE` near an eql_v2/eql_v3 token slipped past the strict
    // matcher. Flag it — non-fatally — rather than leave the user shipping SQL
    // that fails at migrate time.
    for (const nearMiss of updated.matchAll(NEAR_MISS_RE)) {
      skipped.push({
        file: filePath,
        statement: trimStatementPreamble(nearMiss[0]),
      })
    }
  }

  return { rewritten, skipped }
}

/** One candidate migration directory's outcome from {@link sweepMigrationDirs}. */
export interface DirRewriteResult extends RewriteResult {
  /** The candidate directory as supplied (relative to `cwd`), for reporting. */
  dir: string
  /** Set when this directory's sweep threw; the sweep continues regardless. */
  error?: string
}

/**
 * Sweep every candidate migration directory under `cwd`, rewriting each one's
 * unsafe ALTER-to-encrypted statements. Directories that don't exist are
 * skipped; the returned array carries one entry per directory that did.
 *
 * **Why every directory, not just the first:** a project's drizzle-kit `out`
 * directory is not discoverable from here, so the caller passes a candidate
 * list. Stopping at the first candidate that merely *exists* means an empty or
 * already-rewritten `drizzle/` sitting next to the project's real `migrations/`
 * silently leaves those migrations unrepaired — they then fail at migrate time
 * with the very `cannot cast type ...` error this function exists to prevent.
 *
 * Sweeping all of them is safe because the rewrite is idempotent: a rewritten
 * statement no longer contains `SET DATA TYPE`, so neither
 * {@link ALTER_COLUMN_TO_ENCRYPTED_RE} nor {@link NEAR_MISS_RE} can match it a
 * second time. Two candidates resolving to the same directory (via a symlink)
 * therefore cost a redundant read, not a double transform.
 *
 * A directory that throws mid-sweep is reported via `error` rather than
 * aborting — one unreadable candidate must not strand the others.
 */
export async function sweepMigrationDirs(
  cwd: string,
  dirs: readonly string[],
): Promise<DirRewriteResult[]> {
  const results: DirRewriteResult[] = []

  for (const dir of dirs) {
    const abs = resolve(cwd, dir)
    if (!existsSync(abs)) continue

    try {
      const { rewritten, skipped } = await rewriteEncryptedAlterColumns(abs)
      results.push({ dir, rewritten, skipped })
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err)
      results.push({ dir, rewritten: [], skipped: [], error: message })
    }
  }

  return results
}

/**
 * The rewrite is identical for v2 and v3, and the ADD+DROP+RENAME sequence is
 * equivalent to DROP+ADD: it makes the column type valid but does NOT preserve
 * the column's data. It is therefore safe only on an EMPTY table. On a populated
 * table the new column starts NULL and the old one is dropped in the same
 * migration, so the plaintext is destroyed.
 *
 * The commented UPDATE is only a placeholder — it can never become real SQL. The
 * encrypted value is the EQL envelope produced by ZeroKMS via the client
 * (`encryptModel` / `bulkEncryptModels`); there is no expression Postgres can
 * evaluate to fill it. (v3 stores that envelope as jsonb rather than v2's
 * composite, but this is equally true on both surfaces.)
 *
 * So the guidance does NOT tell the user to backfill and run this migration —
 * that would still lose data on cutover. It points a populated table at the
 * staged `stash encrypt` lifecycle (add → backfill → cutover → drop), which
 * keeps both columns alive across deploys.
 */
function renderSafeAlter(
  table: string,
  column: string,
  domain: string,
  schema?: string,
): string {
  const tmp = `${column}__cipherstash_tmp`
  // Preserve the schema qualifier drizzle-kit emitted for pgSchema() tables so
  // the rewritten statements target the same object.
  const qualifiedTable = schema ? `"${schema}"."${table}"` : `"${table}"`
  return [
    '-- Rewritten by @cipherstash/wizard: in-place ALTER COLUMN cannot cast to',
    `-- ${domain}. This ADD+DROP+RENAME equals DROP+ADD and is safe ONLY if`,
    `-- ${qualifiedTable} is empty. On a populated table it DESTROYS existing "${column}"`,
    '-- data (the new column starts NULL) — do NOT run it there. Use the staged',
    "-- `stash encrypt` path instead: add -> backfill via @cipherstash/stack's",
    '-- encryptModel in application code -> cutover -> drop.',
    '-- NOTE: constraints, defaults, and indexes on the original column are NOT',
    '-- carried over by this ADD/DROP/RENAME — re-add any NOT NULL, DEFAULT,',
    '-- UNIQUE, or index definitions manually.',
    // The domain is emitted as `"public"."<domain>"` unconditionally: EQL
    // installs its domains into `public` (both `stash eql install` and the
    // adapters' baseline migrations do), and the qualifier makes the rewrite
    // independent of the session `search_path`. It is an ASSUMPTION, not
    // something read back from the matched SQL — the `schema` capture above is
    // the TABLE's schema (from a pgSchema() table) and says nothing about where
    // the domain lives. If EQL ever supports installing into a non-`public`
    // schema, this needs the install schema threaded in, here and in the
    // sibling `packages/cli/src/commands/db/rewrite-migrations.ts`.
    `ALTER TABLE ${qualifiedTable} ADD COLUMN "${tmp}" "public"."${domain}";`,
    `-- UPDATE ${qualifiedTable} SET "${tmp}" = /* encrypted value for ${column} */ NULL`,
    '--> statement-breakpoint',
    `ALTER TABLE ${qualifiedTable} DROP COLUMN "${column}";`,
    '--> statement-breakpoint',
    `ALTER TABLE ${qualifiedTable} RENAME COLUMN "${tmp}" TO "${column}";`,
  ].join('\n')
}
