import { existsSync } from 'node:fs'
import { readdir, readFile, writeFile } from 'node:fs/promises'
import { join, resolve } from 'node:path'

/**
 * The encrypted column types this rewrite applies to: the single EQL v2 type,
 * and the whole EQL v3 concrete-domain family (`eql_v3_text_search`,
 * `eql_v3_integer_ord`, …). The v3 side is matched by shape rather than by an
 * enumerated list so a newly added domain is covered without touching this file
 * — the `eql_v3_` prefix is unambiguous in a `SET DATA TYPE` position.
 *
 * v2 stays matched even though the wizard now scaffolds v3 exclusively: a user's
 * migration directory can hold files generated against an older stack version,
 * and existing v2 ciphertext stays valid — we still want their ALTER-to-encrypted
 * statements repaired.
 */
const ENCRYPTED_DOMAIN = String.raw`eql_v2_encrypted|eql_v3_[a-z0-9_]+`

/**
 * Extracts the bare domain name out of whichever mangled form matched. Derived
 * from {@link ENCRYPTED_DOMAIN} so the two can never drift out of sync — a new
 * domain added to the alternation is extracted here for free.
 */
const DOMAIN_RE = new RegExp(ENCRYPTED_DOMAIN, 'i')

/**
 * The mangled forms drizzle-kit emits for a customType in an ALTER COLUMN.
 *
 * drizzle-kit's ALTER COLUMN path wraps the customType `dataType()` return
 * value in double-quotes and prepends `"{typeSchema}".`. Custom types have no
 * `typeSchema`, so the emitted SQL depends on BOTH what `dataType()` returned
 * and which drizzle-kit renders it. Verified against 0.24.2, 0.28.1, 0.30.6,
 * 0.31.0, 0.31.1 and 0.31.10 through `drizzle-kit/api`'s `generateMigration`:
 *
 * | `dataType()` returns            | <= 0.30.6                   | >= 0.31.0                          |
 * | ------------------------------- | --------------------------- | ---------------------------------- |
 * | `eql_v3_text_search` (current)  | `eql_v3_text_search`        | `"undefined"."eql_v3_text_search"` |
 * | `public.eql_v3_text_search`     | `public.eql_v3_text_search` | `"undefined"."public.eql_v3_…"`    |
 * | `"public"."eql_v2_encrypted"`   | `"public"."eql_v2_…"`       | `"undefined".""public"."eql_v2_…"` |
 *
 * The `"undefined".` prefix is a **0.31.0-and-later** behaviour — 0.30.6 and
 * earlier emit the plain form. All six forms stay matched because a user's
 * migration directory can hold files generated by any drizzle-kit version
 * against any stack version — including the qualified `public.eql_v3_*` that
 * stack emitted before the unqualified fix.
 *
 * Ordered longest-first so the alternation cannot match a prefix of a longer
 * form and leave a trailing fragment behind.
 *
 * NOTE: this file is the sibling of `packages/cli/src/commands/db/rewrite-migrations.ts`,
 * which cli's `stash eql migration --drizzle` uses. Both are tightly coupled to
 * drizzle-kit's output format — if drizzle-kit changes, both need updating
 * together. Keep them in sync.
 */
const MANGLED_TYPE_FORMS = [
  String.raw`"undefined"\.""public"\."(?:${ENCRYPTED_DOMAIN})""`,
  String.raw`"undefined"\."public\.(?:${ENCRYPTED_DOMAIN})"`,
  String.raw`"undefined"\."(?:${ENCRYPTED_DOMAIN})"`,
  String.raw`"public"\."(?:${ENCRYPTED_DOMAIN})"`,
  String.raw`public\.(?:${ENCRYPTED_DOMAIN})`,
  // Not emitted by any released drizzle-kit ALTER path, but it is the shape the
  // CREATE TABLE path renders — guard it in case ALTER converges on it.
  String.raw`"(?:${ENCRYPTED_DOMAIN})"`,
  String.raw`(?:${ENCRYPTED_DOMAIN})`,
].join('|')

/**
 * Matches drizzle-kit's generated in-place type change to an encrypted column
 * type, in any of the forms above.
 *
 * Captures:
 * - $1: table name, OR the schema when a qualifier follows (both without quotes)
 * - $2: table name when schema-qualified (`"app"."users"`), else undefined
 * - $3: column name (without quotes)
 * - $4: the mangled type blob — feed it to {@link DOMAIN_RE} for the bare name
 *
 * The optional `(?:\."([^"]+)")?` after the first quoted name matches the
 * schema qualifier drizzle-kit emits for a `pgSchema()` table (`"app"."users"`).
 */
const ALTER_COLUMN_TO_ENCRYPTED_RE = new RegExp(
  // `\s*;` — not `[^;]*;` — so the type blob must run straight into the
  // statement terminator. drizzle-kit emits exactly that (no trailing clause),
  // and the tighter tail means a HAND-AUTHORED `SET DATA TYPE … USING <expr>;`
  // is left untouched instead of being silently rewritten (and its USING
  // discarded).
  String.raw`ALTER TABLE "([^"]+)"(?:\."([^"]+)")?\s+ALTER COLUMN "([^"]+)"\s+SET DATA TYPE (${MANGLED_TYPE_FORMS})\s*;`,
  'gi',
)

/**
 * A deliberately BROAD scan for statements that look like an in-place change to
 * an encrypted column but that the strict {@link ALTER_COLUMN_TO_ENCRYPTED_RE}
 * did not rewrite — a hand-authored `SET DATA TYPE … USING …;`, or some future
 * drizzle-kit form the strict matcher doesn't yet cover.
 *
 * It matches any single (`;`-terminated) statement that contains both
 * `SET DATA TYPE` and an `eql_v2`/`eql_v3` domain token at a word boundary (so
 * lookalikes like `eql_v4_…` or `not_eql_v3_…` don't trip it). Run AFTER the
 * strict rewrite so genuinely-rewritten statements — which no longer contain
 * `SET DATA TYPE` — are already gone; whatever this still finds is a near-miss
 * we flag for human review rather than silently ship as broken SQL.
 */
const NEAR_MISS_RE =
  /[^;]*?\bSET\s+DATA\s+TYPE\b[^;]*?\beql_v[23][a-z0-9_]*[^;]*?;/gi

/**
 * Strips any run of blank lines, `--` line comments (including drizzle-kit's
 * `--> statement-breakpoint`), and `/* … *\/` block comments — in any order,
 * repeated as many times as they occur — from the head of a
 * {@link NEAR_MISS_RE} match.
 *
 * That regex opens with a lazy `[^;]*?`, whose only left boundary is the
 * previous `;` — or the start of the file when there is no preceding statement.
 * So the raw match drags in every comment and blank line since then, and a
 * near-miss preceded by a comment block gets reported to the user with that
 * whole block glued to its front. Strip the preamble so the statement we quote
 * back reads as the offending statement alone.
 *
 * The block comment is matched as its OWN loop alternative rather than a
 * single group anchored ahead of the line-comment loop, because the latter
 * only works when the block comment sits at the very start of the file: in
 * the far more common case — a preceding statement earlier in the same file —
 * the match starts at THAT statement's `;`, so it opens with the newline
 * after it, not with the comment. An anchored `^(?:/\*…\*\/\s*)?` can't match
 * past that newline to reach the comment, so it silently matches nothing and
 * leaves the comment attached to the reported statement. Folding the block
 * comment into the repeating loop lets it match after any number of leading
 * newlines/line-comments, in any interleaving.
 *
 * The block comment strip is NOT cosmetic: a statement the strict
 * {@link ALTER_COLUMN_TO_ENCRYPTED_RE} matched but skipped (`already-encrypted`
 * or `source-unknown`) is left on disk unchanged, so it still contains
 * `SET DATA TYPE` and the broad scan below finds it again. Without stripping
 * the block comment here, that second pass reports a DIFFERENT statement string
 * (comment glued to the front) than the strict pass's `match.trim()`, so
 * {@link rewriteEncryptedAlterColumns}'s dedup key never matches and the same
 * statement is reported twice — once with the correct reason, once as
 * `unrecognised-form`, whose guidance (look for a hand-authored `USING`) is
 * wrong for a statement the strict matcher already matched. Stripping the
 * comment here makes both passes agree on the statement text so the second
 * report collapses into the first.
 *
 * Known residue, accepted rather than fixed: a NESTED closed block comment
 * ahead of a live ALTER (`/* outer /* inner *\/ still *\/`) still
 * double-reports. The block-comment alternative's `*?` is lazy, so it stops
 * at the FIRST `*\/` — consuming only `/* outer /* inner *\/` — and leaves
 * `` still *\/`` glued to the front of the next iteration, which the
 * line-comment alternative doesn't recognise either. That residual text rides
 * along into the `unrecognised-form` report.
 */
const STATEMENT_PREAMBLE_RE =
  /^(?:\s*\/\*[\s\S]*?\*\/|[^\S\n]*(?:--[^\n]*)?\n)*/

/** Drop the leading blank/comment lines a `[^;]*?`-anchored match dragged in. */
function trimStatementPreamble(statement: string): string {
  return statement.replace(STATEMENT_PREAMBLE_RE, '').trim()
}

/**
 * True when the character at `index` is INERT — it sits inside a SQL comment (a
 * `--` line comment, or a nestable block comment) or inside a single-quoted
 * string literal. Either way it is not a statement the database will execute,
 * so the rewrite must leave it exactly as written.
 *
 * **Why the rewrite needs this:** {@link ALTER_COLUMN_TO_ENCRYPTED_RE} is
 * comment-blind and {@link renderSafeAlter} returns MULTIPLE lines. Rewriting a
 * commented-out `-- ALTER TABLE … SET DATA TYPE …;` therefore leaves the
 * author's `-- ` prefix on line 1 only — lines 2+, including `DROP COLUMN`,
 * become live executable SQL and destroy the column. Commented SQL is inert by
 * definition, so the only correct move is to leave it exactly as written.
 *
 * **Why string literals count as inert too:** an ALTER quoted inside an
 * `INSERT … VALUES ('…')` is DATA. Rewriting it splices `--> statement-breakpoint`
 * markers INSIDE the literal, so splitting the file the way drizzle's migrator
 * does yields a bare, live `ALTER TABLE … DROP COLUMN …;` as a chunk of its own.
 * Escaping the injected text's own apostrophe (`@cipherstash/stack's`) would fix
 * only the syntax error, not that live DROP COLUMN — so the statement is left
 * as written, exactly like a commented one.
 *
 * Double-quoted identifiers are tokenised BEFORE `'` is considered: an
 * apostrophe inside `"o'brien_data"` must not open a phantom literal, or the
 * scan runs to the NEXT apostrophe — typically the same identifier in a
 * commented-out ALTER further down — decides that ALTER is live, and rewrites
 * it into a real `DROP COLUMN`. A doubled delimiter (`''` in a literal, `""` in
 * an identifier) is an escape and does not close the token.
 *
 * Dollar-quoted bodies (`$$ … $$`, `$fn$ … $fn$`) are skipped whole, and an
 * `E''` literal gives backslash its escape meaning. Both are quote-PARITY
 * concerns, not merely "we might skip a rewrite": an apostrophe inside an
 * untracked `$$` body, or a `\'` read as a close, ends a literal EARLY, and
 * every token after it is then misread — including a commented-out ALTER, which
 * reads as live and gets rewritten into a live DROP COLUMN. That is the same
 * failure mode as the apostrophe-in-identifier case below, and it is why the
 * earlier reasoning here ("can only make us skip") was wrong: it holds for an
 * UNDER-terminated literal, not an over-terminated one (#772 review, finding 1).
 */
function isInsideCommentOrString(sql: string, index: number): boolean {
  let i = 0
  while (i < index) {
    if (sql.startsWith('--', i)) {
      const eol = sql.indexOf('\n', i)
      if (eol === -1 || eol >= index) return true
      i = eol + 1
    } else if (sql.startsWith('/*', i)) {
      // Postgres block comments nest, so track depth rather than stopping at
      // the first `*/` — a nested close would otherwise end the comment early
      // and let the text after it read as live SQL.
      let depth = 1
      let j = i + 2
      while (j < sql.length && depth > 0) {
        if (sql.startsWith('/*', j)) {
          depth += 1
          j += 2
        } else if (sql.startsWith('*/', j)) {
          depth -= 1
          j += 2
        } else {
          j += 1
        }
      }
      if (j > index) return true
      i = j
    } else if (sql[i] === '$') {
      // A `$tag$ … $tag$` body is opaque: its content is not SQL, so a `'` or
      // `--` inside it means nothing. Skipping the whole body is what keeps the
      // rest of the file's quote parity aligned with Postgres.
      const delimiter = dollarQuoteDelimiter(sql, i)
      if (delimiter === undefined) {
        i += 1
      } else {
        const close = sql.indexOf(delimiter, i + delimiter.length)
        // Unterminated: inert to the end of the file, like the cases below.
        const end = close === -1 ? sql.length : close + delimiter.length
        if (end > index) return true
        i = end
      }
    } else if (sql[i] === '"') {
      // A quoted identifier is live SQL, but its body is not: consuming it here
      // — before the `'` branch below — is what stops an apostrophe inside one
      // from opening a string literal that never really existed.
      const end = endOfQuoted(sql, i, '"')
      // An unterminated identifier swallows the rest of the file, so treat it
      // as inert exactly like the unterminated literal below. Running the
      // cursor to the end instead would exit the loop and report `false` —
      // "live" — which is how the apostrophe bug destroyed a column in the
      // first place, one branch over.
      if (end > index) return true
      i = end
    } else if (sql[i] === "'") {
      const end = endOfQuoted(sql, i, "'", isEscapeStringOpener(sql, i))
      // Unterminated, or the literal runs past `index`: `index` is inside a
      // string literal, which is every bit as inert as a comment.
      if (end > index) return true
      i = end
    } else {
      i += 1
    }
  }
  return false
}

/**
 * The `$tag$` delimiter opening at `open`, or `undefined` when what sits there
 * is just a `$`. The tag is empty (`$$`) or an SQL identifier (`$fn$`); a digit
 * cannot start one, so a positional parameter (`$1`) is never mistaken for a
 * dollar-quote opener.
 */
function dollarQuoteDelimiter(sql: string, open: number): string | undefined {
  DOLLAR_QUOTE_OPEN_RE.lastIndex = open
  return DOLLAR_QUOTE_OPEN_RE.exec(sql)?.[0]
}

/** Sticky, so the scan never has to slice the file to test one position. */
const DOLLAR_QUOTE_OPEN_RE = /\$(?:[A-Za-z_][A-Za-z0-9_]*)?\$/y

/**
 * Whether the `'` at `open` starts an `E''` escape-string, in which a backslash
 * escapes the following character. Plain literals give backslash no special
 * meaning under the default `standard_conforming_strings = on`.
 *
 * The character before the `E` must not be part of an identifier, so a column
 * or type name that merely ends in `e` does not turn the literal after it into
 * an escape-string.
 */
function isEscapeStringOpener(sql: string, open: number): boolean {
  const prefix = sql[open - 1]
  if (prefix !== 'E' && prefix !== 'e') return false
  return !/[A-Za-z0-9_]/.test(sql[open - 2] ?? '')
}

/**
 * The index just past the `quote`-delimited token that opens at `open`, or
 * `sql.length` when it is never closed. A doubled delimiter inside the token is
 * an escaped one (`''`, `""`) and does not end it.
 *
 * With `backslashEscapes`, a `\` also escapes the next character — the `E''`
 * form. Getting this wrong ends the literal EARLY, which shifts quote parity
 * for the whole rest of the file and can make a commented-out ALTER downstream
 * read as live (#772 review, finding 1).
 */
function endOfQuoted(
  sql: string,
  open: number,
  quote: "'" | '"',
  backslashEscapes = false,
): number {
  let i = open + 1
  while (i < sql.length) {
    if (backslashEscapes && sql[i] === '\\') {
      i += 2
    } else if (sql[i] !== quote) {
      i += 1
    } else if (sql[i + 1] === quote) {
      i += 2
    } else {
      return i + 1
    }
  }
  return sql.length
}

/** A table reference, bare (`"users"`) or schema-qualified (`"app"."users"`). */
const TABLE_REF = String.raw`"([^"]+)"(?:\."([^"]+)")?`

/**
 * An encrypted type in any of the {@link MANGLED_TYPE_FORMS}, pinned to end at a
 * delimiter so a bare domain cannot match a prefix of a longer identifier.
 *
 * Two shapes {@link MANGLED_TYPE_FORMS} does not enumerate are folded in here so
 * the encrypted index recognises them and the ADD+DROP+RENAME cannot drop their
 * ciphertext: a domain in ANY quoted schema (`"app"."eql_v3_text_search"`, not
 * just the literal `public` the mangled forms special-case), and a `[` in the
 * trailing lookahead so an ARRAY of the domain (`public.eql_v3_text_search[]`)
 * ends at a delimiter too. Both feed only the encrypted index — never the
 * rewrite matcher — so the worst case of admitting one is a flagged statement,
 * the same safe asymmetry the fail-closed rule already relies on.
 */
const ENCRYPTED_TYPE_REF = String.raw`(?:${MANGLED_TYPE_FORMS}|"[^"]+"\."(?:${ENCRYPTED_DOMAIN})")(?=[\s,;)[]|$)`

/** `ALTER TABLE … ADD COLUMN "col" <encrypted>` — $1/$2 table, $3 column. */
const ADD_ENCRYPTED_COLUMN_RE = new RegExp(
  String.raw`ALTER TABLE\s+${TABLE_REF}\s+ADD COLUMN\s+(?:IF NOT EXISTS\s+)?"([^"]+)"\s+${ENCRYPTED_TYPE_REF}`,
  'gi',
)

/** `ALTER TABLE … RENAME COLUMN "a" TO "b"` — $1/$2 table, $3 from, $4 to. */
const RENAME_COLUMN_RE = new RegExp(
  String.raw`ALTER TABLE\s+${TABLE_REF}\s+RENAME COLUMN\s+"([^"]+)"\s+TO\s+"([^"]+)"`,
  'gi',
)

/** `CREATE TABLE … ( … );` — $1/$2 table, $3 the column-definition body. */
const CREATE_TABLE_RE = new RegExp(
  String.raw`CREATE TABLE\s+(?:IF NOT EXISTS\s+)?${TABLE_REF}\s*\(([\s\S]*?)\)\s*;`,
  'gi',
)

/** `"col" <encrypted>` inside a CREATE TABLE body — $1 column. */
const CREATE_TABLE_ENCRYPTED_COLUMN_RE = new RegExp(
  String.raw`"([^"]+)"\s+${ENCRYPTED_TYPE_REF}`,
  'gi',
)

/**
 * A column name in a DECLARATION position — `"email" text`,
 * `"email" "public"."eql_v3_text_search"`, `"amount" numeric(10, 2)`.
 *
 * The `\s+["a-z]` tail is what separates a declaration from a MENTION. Most
 * mentions are followed by `)`, `,`, or an operator, which the tail alone
 * already rejects:
 *
 * ```sql
 * PRIMARY KEY ("id", "name")
 * FOREIGN KEY ("org_id") REFERENCES "orgs"("id")
 * ```
 *
 * But a mention inside a predicate or a table-level constraint is often
 * followed by whitespace and a SQL KEYWORD — which has exactly the same
 * `\s+[a-z]` shape as a real declaration, and drizzle-kit emits both forms
 * inside a `CREATE TABLE` (a `CONSTRAINT … CHECK (<user sql>)` body is
 * user-authored, so the predicate form is reachable too):
 *
 * ```sql
 * CHECK ("email" IS NOT NULL)
 * CONSTRAINT "users_email_unique" UNIQUE ("email")
 * ```
 *
 * The negative lookahead rejects the keywords reachable this way: predicate
 * keywords (`IS`, `IN`, `NOT`, `LIKE`, `ILIKE`, `BETWEEN`, `AND`, `OR`),
 * ordering/collation (`COLLATE`, `ASC`, `DESC`, `NULLS`), and every
 * table/column-constraint keyword (`UNIQUE`, `PRIMARY`, `FOREIGN`, `CHECK`,
 * `EXCLUDE`, `REFERENCES`, `CONSTRAINT`, `USING`, `WITH`) — the last six also
 * close the constraint-NAME case above, since Postgres always puts one of
 * them immediately after a constraint's name.
 *
 * A real type token still matches because the lookahead is pinned to a word
 * boundary (`\b`) right after each keyword, so it only rejects a keyword when
 * that keyword is the WHOLE next word: `interval` and `inet` both start with
 * `IN`'s letters, but their third character keeps them inside one word, so
 * `\bIN\b` never matches there; the same reasoning clears `int`,
 * `char`/`citext` against `CHECK`, and `eql_v2_encrypted`/`eql_v3_*` against
 * `EXCLUDE`.
 *
 * Deliberately NOT pinned to the encrypted domains. A column the corpus
 * declares but does not give an encrypted type is, by residue, plaintext — so
 * the fail-closed rule needs no type classification and no SQL parsing, only
 * the known encrypted list that {@link ENCRYPTED_TYPE_REF} already provides.
 *
 * **The residue claim depends on {@link ENCRYPTED_TYPE_REF} recognising every
 * encrypted shape.** "By residue, plaintext" is only as good as the encrypted
 * side's coverage: a declaration {@link ENCRYPTED_TYPE_REF} fails to recognise
 * falls to the plaintext residue and gets rewritten. Two such shapes are now
 * covered explicitly by {@link ENCRYPTED_TYPE_REF} — a domain in a non-`public`
 * schema (`"email" "app"."eql_v3_text_search"`) and an array of the domain
 * (`"email" public.eql_v3_text_search[]`) — because both name ciphertext the
 * corpus can see, so rewriting them is the exact drop this rule exists to
 * prevent. The dependency itself remains: any encrypted shape a future EQL
 * install introduces must be added to {@link ENCRYPTED_TYPE_REF} or it too will
 * fall to the plaintext residue.
 *
 * **Residue, accepted.** The lookahead is a fixed keyword list, not a parser:
 * a predicate keyword it does not enumerate (`SIMILAR`, `ISNULL`, `NOTNULL`,
 * `OVERLAPS`, `ON`, …) still lets a bare mention through, e.g.
 * `CHECK ("email" SIMILAR TO '...')`, or a `REFERENCES "email" ON DELETE
 * CASCADE` where `"email"` names the referenced TABLE rather than the column
 * being declared — `"id" integer REFERENCES "email" ON DELETE CASCADE` inside
 * a `CREATE TABLE` body still registers `email` as declared. That one only
 * bites when a column shares a referenced table's name, so like the rest of
 * this residue it is inert unless that mention's name exactly matches a
 * DIFFERENT column that is both encrypted and genuinely undeclared anywhere
 * else in the corpus — contrived, and strictly narrower than the gap this
 * replaces.
 */
const DECLARED_COLUMN_RE =
  /"([^"]+)"\s+(?!(?:IS|IN|NOT|LIKE|ILIKE|BETWEEN|AND|OR|COLLATE|ASC|DESC|NULLS|UNIQUE|PRIMARY|FOREIGN|CHECK|EXCLUDE|REFERENCES|CONSTRAINT|USING|WITH)\b)["a-z]/gi

/**
 * `ALTER TABLE … ADD COLUMN "col" <any type>` — $1/$2 table, $3 column.
 *
 * Needs no {@link DECLARED_COLUMN_RE}-style keyword lookahead: the token
 * right after an ADD COLUMN's column name is always its type, so no SQL
 * keyword can occupy that position.
 */
const ADD_COLUMN_RE = new RegExp(
  String.raw`ALTER TABLE\s+${TABLE_REF}\s+ADD COLUMN\s+(?:IF NOT EXISTS\s+)?"([^"]+)"\s+["a-z]`,
  'gi',
)

/** Splits a `TABLE_REF` capture pair into its schema and table halves. */
function tableOf(
  first: string,
  second: string | undefined,
): { schema?: string; table: string } {
  // When schema-qualified (`"app"."users"`) the first capture is the schema and
  // the second is the table; otherwise the first is the table.
  return second === undefined
    ? { table: first }
    : { schema: first, table: second }
}

/**
 * Identity of a column across the corpus, for {@link indexColumnDeclarations}.
 *
 * `public` and no schema at all are the SAME table: Postgres resolves an
 * unqualified name through `search_path`, which starts at `public`. The two
 * spellings coexist in one corpus routinely — drizzle-kit emits unqualified,
 * while hand-written SQL and this sweep's own {@link renderSafeAlter} output
 * are qualified. Keying on the literal text split one column across two keys,
 * so a column already encrypted under one spelling looked plaintext when
 * altered under the other and the ADD+DROP+RENAME dropped its ciphertext
 * (#772 review, finding 4).
 *
 * Only the IMPLICIT schema collapses. `"app"."users"` is a genuinely different
 * table from `"users"` and keeps its own key. No case folding either:
 * `TABLE_REF` matches quoted identifiers only, and those are case-sensitive in
 * Postgres — `"PUBLIC"` really is a different schema from `"public"`.
 */
function columnKey(table: string, column: string, schema?: string): string {
  return JSON.stringify([
    schema === 'public' ? '' : (schema ?? ''),
    table,
    column,
  ])
}

/** What the migration corpus says about the columns it mentions. */
interface ColumnIndex {
  /** Columns the corpus gives an ENCRYPTED type. Rewriting one drops ciphertext. */
  encrypted: Set<string>
  /** Columns the corpus DECLARES at all, whatever type it gives them. */
  declared: Set<string>
}

/**
 * Index what the migration corpus knows about each column, so the rewrite can
 * tell the change it exists for (plaintext → encrypted) from the two it must
 * never make: encrypted → encrypted, and a change to a column it knows nothing
 * about.
 *
 * **Why `encrypted` (#772 review, W-3):** the strict matcher captures only the
 * TARGET type. A column whose encrypted domain merely changes (`types.TextEq` →
 * `types.TextSearch`) matches just as well as a plaintext column, and the
 * ADD+DROP+RENAME then drops a column full of CIPHERTEXT — with no plaintext
 * left anywhere to backfill from, so unlike the plaintext case the data is not
 * recoverable from the application at all.
 *
 * **Why `declared` (A-2):** absence from `encrypted` is not evidence of
 * plaintext. It is evidence of nothing. The sweep runs per directory, and the
 * shipped wizard default scans three of them, so a column's `CREATE TABLE` can
 * simply live somewhere this sweep never reads — the column is then rewritten
 * on an assumption, and the ADD+DROP+RENAME drops live ciphertext. Requiring a
 * POSITIVE declaration makes the unknown case a flagged statement instead.
 *
 * Because the encrypted side is matched against the known domain list, the
 * plaintext side needs no type classification: a column the corpus declares but
 * does not give an encrypted type is plaintext by residue.
 *
 * The index is corpus-wide rather than ordered by migration: over-detecting
 * "encrypted" costs a flagged statement the user handles by hand, while
 * under-detecting costs irrecoverable ciphertext. That asymmetry is why the
 * two per-column scans inside a `CREATE TABLE` body are deliberately
 * inconsistent about comments (see the comment at the loops themselves) —
 * do not "fix" that inconsistency, it is the point.
 */
function indexColumnDeclarations(contents: readonly string[]): ColumnIndex {
  const encrypted = new Set<string>()
  const declared = new Set<string>()

  for (const sql of contents) {
    for (const created of sql.matchAll(CREATE_TABLE_RE)) {
      if (isInsideCommentOrString(sql, created.index)) continue
      const { schema, table } = tableOf(created[1], created[2])
      const body = created[3]

      // The body is scanned as its own document: a `--` earlier in it comments
      // out the rest of that line, and a CREATE inside a block comment or a
      // string literal was already skipped above.
      //
      // Asymmetric on purpose. ENCRYPTED does NOT re-check comments here: a
      // commented-out encrypted column inside an otherwise live CREATE TABLE
      // still counts, exactly as it did before this sweep learned to declare
      // anything — over-detecting "encrypted" only costs a flagged statement.
      // DECLARED DOES re-check: a commented-out plaintext line never ran, so
      // it must not count as a declaration — over-detecting "declared" is
      // what would put a truly-undeclared, possibly already-encrypted column
      // back on the fail-open path.
      for (const column of body.matchAll(CREATE_TABLE_ENCRYPTED_COLUMN_RE)) {
        encrypted.add(columnKey(table, column[1], schema))
      }

      for (const column of body.matchAll(DECLARED_COLUMN_RE)) {
        if (isInsideCommentOrString(body, column.index)) continue
        declared.add(columnKey(table, column[1], schema))
      }
    }

    for (const added of sql.matchAll(ADD_ENCRYPTED_COLUMN_RE)) {
      if (isInsideCommentOrString(sql, added.index)) continue
      const { schema, table } = tableOf(added[1], added[2])
      encrypted.add(columnKey(table, added[3], schema))
    }

    for (const added of sql.matchAll(ADD_COLUMN_RE)) {
      if (isInsideCommentOrString(sql, added.index)) continue
      const { schema, table } = tableOf(added[1], added[2])
      declared.add(columnKey(table, added[3], schema))
    }

    // A rename carries the column's type with it — and `<col>__cipherstash_tmp`
    // renamed onto the real name is exactly what a previous sweep of this very
    // directory emitted. Run after ADD so that tmp column is already indexed.
    for (const renamed of sql.matchAll(RENAME_COLUMN_RE)) {
      if (isInsideCommentOrString(sql, renamed.index)) continue
      const { schema, table } = tableOf(renamed[1], renamed[2])
      const from = columnKey(table, renamed[3], schema)
      const to = columnKey(table, renamed[4], schema)
      if (encrypted.has(from)) encrypted.add(to)
      if (declared.has(from)) declared.add(to)
    }
  }

  return { encrypted, declared }
}

/** Why a recognised ALTER-to-encrypted statement was left alone. */
export type SkipReason =
  /** Outside the strict matcher — hand-authored `USING`, or an unknown form. */
  | 'unrecognised-form'
  /** The column already holds an encrypted domain; rewriting drops ciphertext. */
  | 'already-encrypted'
  /** The corpus never declares the column, so its current type is unknown. */
  | 'source-unknown'

/** A statement the sweep recognised as ALTER-to-encrypted but did NOT rewrite. */
export interface SkippedAlter {
  /** Absolute path of the migration file the statement lives in. */
  file: string
  /** The offending statement, verbatim (trimmed), for the user to review. */
  statement: string
  /** Why it was left alone — the caller turns this into user-facing guidance. */
  reason: SkipReason
}

/**
 * One-line explanation of a {@link SkipReason}, for the CLI/wizard to print
 * next to the statement. Lives here so every caller says the same thing — the
 * three reasons need very different action from the user, and a single generic
 * "could not rewrite automatically" hides that.
 */
export function describeSkipReason(reason: SkipReason): string {
  switch (reason) {
    case 'already-encrypted':
      return "the column is ALREADY encrypted, so the ADD+DROP+RENAME rewrite would DROP the ciphertext with no plaintext left to backfill from. Changing an encrypted column's domain changes its index terms, so the data must be re-encrypted through the staged `stash encrypt` lifecycle"
    case 'unrecognised-form':
      return 'it falls outside the strict matcher (a hand-authored `SET DATA TYPE ... USING ...`, or a drizzle-kit form the sweep does not recognise) and an in-place cast to an encrypted domain fails at migrate time'
    case 'source-unknown':
      return "the sweep could not find where this column was declared in this migration directory, so it cannot tell a plaintext column (safe to rewrite) from one that already holds ciphertext (where the rewrite would DROP it). Usually the column's `CREATE TABLE` / `ADD COLUMN` lives in a different directory, or the migration history was squashed. Check the column's current type in the database: if it is plaintext and the table is empty, apply the ADD/DROP/RENAME by hand; if it already holds ciphertext, use the staged `stash encrypt` lifecycle instead"
  }
}

/** Outcome of a sweep: the files rewritten, and near-misses left for review. */
export interface RewriteResult {
  /** Absolute paths of files whose unsafe ALTER COLUMN(s) were rewritten. */
  rewritten: string[]
  /** Near-miss statements the strict matcher passed over — flag, don't guess. */
  skipped: SkippedAlter[]
}

/**
 * Replace in-place `ALTER COLUMN ... SET DATA TYPE <encrypted domain>`
 * statements with an ADD + DROP + RENAME sequence.
 *
 * **Why this exists (CIP-2991, CIP-2994, #693):** Postgres has no implicit cast
 * from `text`/`numeric` to an encrypted domain, so `ALTER COLUMN ... SET DATA
 * TYPE eql_v2_encrypted` (or any `eql_v3_*` domain) fails at migrate time with
 * `cannot cast type ... to <domain>`. This applies equally to the single EQL v2
 * type and the whole EQL v3 concrete-domain family.
 *
 * The rewrite is an ADD+DROP+RENAME, which is **equivalent to DROP+ADD**: it
 * makes the column type valid but does NOT preserve the column's data. It is
 * therefore safe ONLY on an EMPTY table. On a populated table the new column
 * starts NULL and the original is dropped in the same migration, so the
 * plaintext is destroyed. The commented UPDATE is a placeholder that can never
 * become real SQL (the encrypted value is the EQL envelope produced by ZeroKMS
 * via the client — there is no expression Postgres can evaluate to fill it), so
 * a populated table must instead use the staged `stash encrypt` lifecycle
 * (add → backfill via `@cipherstash/stack`'s `encryptModel` → cutover → drop),
 * which keeps both columns alive across deploys. Each rewritten file carries a
 * header comment saying exactly this.
 *
 * Returns {@link RewriteResult}: the files rewritten, plus `skipped` statements
 * left for a human — ones outside the strict matcher (a hand-authored
 * `SET DATA TYPE … USING …;`, or a future drizzle-kit form); ones targeting a
 * column that is ALREADY encrypted, where the rewrite would drop ciphertext;
 * and ones targeting a column the corpus never DECLARES anywhere, where the
 * rewrite would be guessing at a type it cannot see (likely the most common
 * skip on a real corpus, since the sweep only ever reads part of the
 * migration history). All three are left untouched on disk and surfaced
 * non-fatally so the caller can tell the user to review them, rather than
 * silently shipping broken SQL or destroying data. Statements sitting inside a
 * SQL comment — or inside a single-quoted string literal, where they are data
 * rather than SQL — are inert and are neither rewritten nor reported.
 */
export async function rewriteEncryptedAlterColumns(
  outDir: string,
  options: { skip?: string } = {},
): Promise<RewriteResult> {
  const entries = await readdir(outDir).catch(
    (error: NodeJS.ErrnoException) => {
      // A missing directory is simply nothing to sweep. Anything else — EACCES
      // above all — is a sweep that did NOT happen, and the caller reports it
      // rather than letting the user believe their migrations were checked.
      if (error.code === 'ENOENT') return [] as string[]
      throw error
    },
  )
  const rewritten: string[] = []
  const skipped: SkippedAlter[] = []
  const seen = new Set<string>()

  /** Record a skip once — the strict pass and the broad scan can both find it. */
  const skip = (file: string, statement: string, reason: SkipReason): void => {
    // Keyed on collapsed whitespace: the two passes trim the same statement
    // by slightly different rules, and the strict pass runs first so its
    // more specific reason is the one kept.
    const key = `${file} :: ${statement.replace(/\s+/g, ' ')}`
    if (seen.has(key)) return
    seen.add(key)
    skipped.push({ file, statement, reason })
  }

  const sqlFiles = entries.filter((entry) => entry.endsWith('.sql')).sort()
  const contents = new Map<string, string>()
  for (const entry of sqlFiles) {
    const filePath = join(outDir, entry)
    contents.set(filePath, await readFile(filePath, 'utf-8'))
  }

  // Built from the WHOLE corpus, including `options.skip`: a column's current
  // type comes from the migrations that ran before this one, not just the files
  // we are allowed to edit.
  const { encrypted: encryptedColumns, declared: declaredColumns } =
    indexColumnDeclarations([...contents.values()])

  for (const [filePath, original] of contents) {
    if (options.skip && filePath === options.skip) continue

    // Reset the regex's lastIndex — it's stateful on /g
    ALTER_COLUMN_TO_ENCRYPTED_RE.lastIndex = 0

    const updated = original.replace(
      ALTER_COLUMN_TO_ENCRYPTED_RE,
      (
        match: string,
        first: string,
        second: string | undefined,
        column: string,
        mangledType: string,
        offset: number,
      ) => {
        // Commented-out SQL never runs, and a multi-line replacement would only
        // inherit the `-- ` on its first line — leaving the rest live.
        if (isInsideCommentOrString(original, offset)) return match

        const { schema, table } = tableOf(first, second)

        // Already encrypted: the ADD+DROP+RENAME would drop the ciphertext and
        // there is no plaintext left to backfill from. Flag, never guess.
        if (encryptedColumns.has(columnKey(table, column, schema))) {
          skip(filePath, match.trim(), 'already-encrypted')
          return match
        }

        // Fail closed. Absence from `declaredColumns` does not mean the column
        // is plaintext — it means the corpus never said. The declaration can
        // sit in a directory this sweep does not read (the wizard ships with
        // three candidates and indexes each separately), so rewriting on the
        // assumption is how a live `DROP COLUMN` reaches a populated — possibly
        // already-encrypted — column. Flag it and let the user look.
        if (!declaredColumns.has(columnKey(table, column, schema))) {
          skip(filePath, match.trim(), 'source-unknown')
          return match
        }

        const domain = DOMAIN_RE.exec(mangledType)?.[0]?.toLowerCase()
        // Unreachable — the outer regex only matches when a domain is present —
        // but leave the statement alone rather than emit a broken rewrite.
        if (!domain) return match

        // This statement converts the column, so from here on in the corpus it
        // holds CIPHERTEXT. `indexColumnDeclarations` cannot know that: it
        // reads CREATE TABLE, ADD COLUMN and RENAME, never the strict matcher's
        // own target. Without this, a corpus carrying an earlier conversion
        // (`... SET DATA TYPE eql_v2_encrypted` from a stack version that
        // predates this sweep) leaves the column looking plaintext, and the
        // NEXT domain change drops the ciphertext — `declared` cannot catch it,
        // because the column really is declared, as plaintext, by the original
        // CREATE TABLE.
        //
        // Recorded here rather than in the corpus-wide index on purpose: the
        // index has no order, so it would flag THIS conversion — the legitimate
        // plaintext -> encrypted one — as already-encrypted too. Files are
        // walked in sorted order and matches within a file in source order, so
        // "already converted" means "converted by a statement that runs before
        // this one".
        encryptedColumns.add(columnKey(table, column, schema))
        return renderSafeAlter(table, column, domain, schema)
      },
    )

    if (updated !== original) {
      await writeFile(filePath, updated, 'utf-8')
      rewritten.push(filePath)
    }

    // Broad secondary scan on the POST-rewrite content: anything still carrying
    // `SET DATA TYPE` near an eql_v2/eql_v3 token slipped past the strict
    // matcher. Flag it — non-fatally — rather than leave the user shipping SQL
    // that fails at migrate time.
    for (const nearMiss of updated.matchAll(NEAR_MISS_RE)) {
      const statement = trimStatementPreamble(nearMiss[0])
      // Anchor the comment test on the `SET DATA TYPE` itself: the match starts
      // at the previous `;`, so its own offset sits before any preamble.
      const keyword = nearMiss[0].search(/\bSET\s+DATA\s+TYPE\b/i)
      if (
        isInsideCommentOrString(updated, nearMiss.index + Math.max(keyword, 0))
      ) {
        continue
      }
      skip(filePath, statement, 'unrecognised-form')
    }
  }

  return { rewritten, skipped }
}

/** One candidate migration directory's outcome from {@link sweepMigrationDirs}. */
export interface DirRewriteResult extends RewriteResult {
  /** The candidate directory as supplied (relative to `cwd`), for reporting. */
  dir: string
  /** Set when this directory's sweep threw; the sweep continues regardless. */
  error?: string
}

/**
 * Sweep every candidate migration directory under `cwd`, rewriting each one's
 * unsafe ALTER-to-encrypted statements. Directories that don't exist are
 * skipped; the returned array carries one entry per directory that did.
 *
 * **Why every directory, not just the first:** a project's drizzle-kit `out`
 * directory is not discoverable from here, so the caller passes a candidate
 * list. Stopping at the first candidate that merely *exists* means an empty or
 * already-rewritten `drizzle/` sitting next to the project's real `migrations/`
 * silently leaves those migrations unrepaired — they then fail at migrate time
 * with the very `cannot cast type ...` error this function exists to prevent.
 *
 * Sweeping all of them is safe because the rewrite is idempotent: a rewritten
 * statement no longer contains `SET DATA TYPE`, so neither
 * {@link ALTER_COLUMN_TO_ENCRYPTED_RE} nor {@link NEAR_MISS_RE} can match it a
 * second time. Two candidates resolving to the same directory (via a symlink)
 * therefore cost a redundant read, not a double transform.
 *
 * A directory that throws mid-sweep is reported via `error` rather than
 * aborting — one unreadable candidate must not strand the others.
 */
export async function sweepMigrationDirs(
  cwd: string,
  dirs: readonly string[],
): Promise<DirRewriteResult[]> {
  const results: DirRewriteResult[] = []

  for (const dir of dirs) {
    const abs = resolve(cwd, dir)
    if (!existsSync(abs)) continue

    try {
      const { rewritten, skipped } = await rewriteEncryptedAlterColumns(abs)
      results.push({ dir, rewritten, skipped })
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err)
      results.push({ dir, rewritten: [], skipped: [], error: message })
    }
  }

  return results
}

/**
 * The rewrite is identical for v2 and v3, and the ADD+DROP+RENAME sequence is
 * equivalent to DROP+ADD: it makes the column type valid but does NOT preserve
 * the column's data. It is therefore safe only on an EMPTY table. On a populated
 * table the new column starts NULL and the old one is dropped in the same
 * migration, so the plaintext is destroyed.
 *
 * The commented UPDATE is only a placeholder — it can never become real SQL. The
 * encrypted value is the EQL envelope produced by ZeroKMS via the client
 * (`encryptModel` / `bulkEncryptModels`); there is no expression Postgres can
 * evaluate to fill it. (v3 stores that envelope as jsonb rather than v2's
 * composite, but this is equally true on both surfaces.)
 *
 * So the guidance does NOT tell the user to backfill and run this migration —
 * that would still lose data on cutover. It points a populated table at the
 * staged `stash encrypt` lifecycle (add → backfill → cutover → drop), which
 * keeps both columns alive across deploys.
 */
function renderSafeAlter(
  table: string,
  column: string,
  domain: string,
  schema?: string,
): string {
  const tmp = `${column}__cipherstash_tmp`
  // Preserve the schema qualifier drizzle-kit emitted for pgSchema() tables so
  // the rewritten statements target the same object.
  const qualifiedTable = schema ? `"${schema}"."${table}"` : `"${table}"`
  return [
    '-- Rewritten by @cipherstash/wizard: in-place ALTER COLUMN cannot cast to',
    `-- ${domain}. This ADD+DROP+RENAME equals DROP+ADD and is safe ONLY if`,
    `-- ${qualifiedTable} is empty. On a populated table it DESTROYS existing "${column}"`,
    '-- data (the new column starts NULL) — do NOT run it there. Use the staged',
    "-- `stash encrypt` path instead: add -> backfill via @cipherstash/stack's",
    '-- encryptModel in application code -> cutover -> drop.',
    '-- NOTE: constraints, defaults, and indexes on the original column are NOT',
    '-- carried over by this ADD/DROP/RENAME — re-add any NOT NULL, DEFAULT,',
    '-- UNIQUE, or index definitions manually.',
    // The domain is emitted as `"public"."<domain>"` unconditionally: EQL
    // installs its domains into `public` (both `stash eql install` and the
    // adapters' baseline migrations do), and the qualifier makes the rewrite
    // independent of the session `search_path`. It is an ASSUMPTION, not
    // something read back from the matched SQL — the `schema` capture above is
    // the TABLE's schema (from a pgSchema() table) and says nothing about where
    // the domain lives. If EQL ever supports installing into a non-`public`
    // schema, this needs the install schema threaded in, here and in the
    // sibling `packages/cli/src/commands/db/rewrite-migrations.ts`.
    `ALTER TABLE ${qualifiedTable} ADD COLUMN "${tmp}" "public"."${domain}";`,
    `-- UPDATE ${qualifiedTable} SET "${tmp}" = /* encrypted value for ${column} */ NULL`,
    '--> statement-breakpoint',
    `ALTER TABLE ${qualifiedTable} DROP COLUMN "${column}";`,
    '--> statement-breakpoint',
    `ALTER TABLE ${qualifiedTable} RENAME COLUMN "${tmp}" TO "${column}";`,
  ].join('\n')
}
