// Code generated by stashgen. DO NOT EDIT.

package documents

import (
	"context"
	"log/slog"

	"github.com/cipherstash/stack/languages/golang/encrypt"
	"github.com/cipherstash/stack/languages/golang/encrypt/gensupport"
)

// Stops compiling when the library does not accept this version of generated file.
const _ = gensupport.GeneratedVersion1

// Document prints its sealed fields in the clear: it has no String or
// LogValue method. Write them, or run stashgen with -redact.

type EncryptedDocument struct {
	Sealed encrypt.Ciphertext
}

func (e EncryptedDocument) String() string {
	return gensupport.Redacted("EncryptedDocument", nil, "Sealed")
}

func (e EncryptedDocument) LogValue() slog.Value {
	return gensupport.RedactedLog(nil, "Sealed")
}

// Stops compiling when Document gains, loses, reorders or retypes a field.
var _ = documentShape(Document{})

type documentShape struct {
	_     struct{}
	Title string
	Body  string
	Tags  []string
}

var declaration = gensupport.DeclareOpaque("documents/v2/body")

var codec = gensupport.New(gensupport.Generated[Document, EncryptedDocument]{
	TypeName:        "Document",
	Declaration:     declaration,
	PrintsPlaintext: true,
	Source: func(v Document) gensupport.Values {
		return gensupport.Values{gensupport.OpaqueField: map[string]any{"title": v.Title, "body": v.Body, "tags": v.Tags}}
	},
	Seal: func(v Document, rec gensupport.Record) EncryptedDocument {
		return EncryptedDocument{Sealed: rec[gensupport.OpaqueField].Ciphertext}
	},
	Open: func(e EncryptedDocument) gensupport.Record {
		return gensupport.Record{gensupport.OpaqueField: {Ciphertext: e.Sealed}}
	},
	Value: func(e EncryptedDocument, vals gensupport.Values) (Document, error) {
		fields, err := gensupport.Get[gensupport.Values](vals, gensupport.OpaqueField)
		if err != nil {
			return Document{}, err
		}
		var v Document
		if v.Title, err = gensupport.Get[string](fields, "title"); err != nil {
			return Document{}, err
		}
		if v.Body, err = gensupport.Get[string](fields, "body"); err != nil {
			return Document{}, err
		}
		if v.Tags, err = gensupport.Get[[]string](fields, "tags"); err != nil {
			return Document{}, err
		}
		return v, nil
	},
})

func Encrypt(ctx context.Context, cipher *encrypt.Cipher, documents []Document) ([]EncryptedDocument, error) {
	return codec.Encrypt(ctx, cipher, documents)
}

func Decrypt(ctx context.Context, d encrypt.Decrypter, encrypted []EncryptedDocument) ([]Document, error) {
	return codec.Decrypt(ctx, d, encrypted)
}
