import { existsSync, readdirSync } from 'node:fs'
import { mkdir, writeFile } from 'node:fs/promises'
import { join } from 'node:path'

/**
 * Suffix every generated Supabase EQL install migration carries.
 *
 * The filename is `<YYYYMMDDHHMMSS>_cipherstash_eql.sql`, so the stem varies
 * per run and only the suffix is stable. {@link findExistingEqlMigration}
 * matches on it — an exact-filename check would miss a file this command
 * itself wrote at a different second, and re-running would silently install
 * EQL a second time in the migration ledger.
 */
export const SUPABASE_EQL_MIGRATION_SUFFIX = '_cipherstash_eql.sql'

/**
 * A Supabase migration version is the leading `YYYYMMDDHHMMSS`. Generating it
 * from the current time (rather than the all-zero prefix the retired EQL v2
 * writer used) keeps the file sorting *after* everything already applied.
 *
 * A lower-sorting version is "out of order" to the Supabase CLI: `supabase db
 * push` skips it unless the user knows to pass `--include-all`. Sorting last
 * costs nothing, because the only ordering that matters is EQL before the
 * user's encrypted-column migrations — and those are written afterwards.
 */
function migrationVersion(now: Date): string {
  return now
    .toISOString()
    .replace(/[-:.TZ]/g, '')
    .slice(0, 14)
}

/**
 * Header prepended to the generated migration, for whoever opens
 * `supabase/migrations/` in six months and finds 4,000 lines of EQL.
 */
function migrationHeader(): string {
  return `-- CipherStash EQL v3 — generated by \`stash eql migration --supabase\`.
--
-- Installs the CipherStash Encrypt Query Language (EQL) types, functions, and
-- operators into the \`eql_v3\` and \`eql_v3_internal\` schemas, grants Supabase's
-- \`anon\`, \`authenticated\`, and \`service_role\` roles access to them, and adds
-- the \`cipherstash.cs_migrations\` tracking schema that \`stash encrypt\` writes
-- its per-column progress into.
--
-- Keeping the install here rather than applying it directly is what makes it
-- survive \`supabase db reset\` — a reset replays this directory, so EQL comes
-- back with everything else.
--
-- Generated file: edit the bundle version by re-running the command with
-- --force rather than hand-editing this SQL.
--
-- Docs: https://cipherstash.com/docs/stack/cipherstash/supabase
`
}

/**
 * Return the path of an EQL install migration already present in
 * `migrationsDir`, or `null`. Lexically last wins, so the reported path is the
 * newest when several exist.
 */
export function findExistingEqlMigration(migrationsDir: string): string | null {
  if (!existsSync(migrationsDir)) return null
  let entries: string[]
  try {
    entries = readdirSync(migrationsDir)
  } catch {
    return null
  }
  const matches = entries
    .filter((entry) => entry.endsWith(SUPABASE_EQL_MIGRATION_SUFFIX))
    .sort()
  return matches.length > 0
    ? join(migrationsDir, matches[matches.length - 1])
    : null
}

export interface WriteSupabaseEqlMigrationOptions {
  /**
   * Absolute path to the directory the migration should be written into.
   * Created recursively when absent — `supabase init` makes it, but a project
   * that has never run a migration may not have it yet.
   */
  migrationsDir: string
  /** The install SQL body (from `buildEqlV3MigrationSql({ supabase: true })`). */
  sql: string
  /**
   * Write even though an EQL install migration is already present. Without
   * this the function throws rather than adding a second one.
   */
  force?: boolean
  /** Injectable clock, so tests can pin the generated filename. */
  now?: Date
}

export interface WriteSupabaseEqlMigrationResult {
  /** Absolute path to the migration written. */
  path: string
  /** Whether this replaced an install migration that was already there. */
  overwritten: boolean
}

/**
 * Write `<migrationsDir>/<version>_cipherstash_eql.sql`.
 *
 * A `force` run overwrites the existing install migration **in place**, keeping
 * its original version. Writing a second, newer-versioned file instead would
 * leave the first one applied and unremovable (deleting an applied migration
 * desyncs `supabase_migrations.schema_migrations`), so the user would end up
 * with two EQL installs in their history. Overwriting keeps it to one.
 *
 * @throws when an EQL install migration already exists and `force` is unset.
 */
export async function writeSupabaseEqlMigration(
  options: WriteSupabaseEqlMigrationOptions,
): Promise<WriteSupabaseEqlMigrationResult> {
  const { migrationsDir, sql, force = false, now = new Date() } = options

  const existing = findExistingEqlMigration(migrationsDir)
  if (existing && !force) {
    throw new Error(
      `An EQL install migration already exists at ${existing}. Re-run with --force to replace it, or delete that file first.`,
    )
  }

  const targetPath =
    existing ??
    join(
      migrationsDir,
      `${migrationVersion(now)}${SUPABASE_EQL_MIGRATION_SUFFIX}`,
    )
  const body = `${migrationHeader()}\n${sql.trimEnd()}\n`

  await mkdir(migrationsDir, { recursive: true })
  await writeFile(targetPath, body, 'utf-8')

  return { path: targetPath, overwritten: existing !== null }
}
