/* tslint:disable */
/* eslint-disable */

/*
 * Hand-written — NOT regenerated by `napi build`.
 *
 * `napi build --dts native.d.ts` writes the generated bindings to `native.d.ts`;
 * this file re-exports them and adds the declarations NAPI-RS can't emit from
 * the Rust types, because they describe *thrown* values rather than function
 * signatures:
 *
 *   - `AuthError` / `AuthErrorCode` — errors thrown by this package are tagged
 *     with a machine-readable `.code` at runtime by `index.js`.
 *   - `OAuthStrategy` — a deprecated alias exported at runtime by `index.js`.
 *
 * `AuthErrorCode` mirrors `AuthError::ERROR_CODES` in
 * `packages/stack-auth/src/lib.rs` (plus `UNKNOWN_ERROR`, the `index.js`
 * fallback). The `stack-auth-node` test `ts_auth_error_code_union_matches_error_codes`
 * guards this union against drift.
 */

export * from "./native";

import type { DeviceSessionStrategy } from "./native";

/** Error codes attached to errors thrown by this package. */
export type AuthErrorCode =
  | 'REQUEST_ERROR'
  | 'ACCESS_DENIED'
  | 'EXPIRED_TOKEN'
  | 'INVALID_GRANT'
  | 'INVALID_CLIENT'
  | 'INVALID_URL'
  | 'INVALID_REGION'
  | 'INVALID_TOKEN'
  | 'SERVER_ERROR'
  | 'STORE_ERROR'
  | 'NOT_AUTHENTICATED'
  | 'MISSING_WORKSPACE_CRN'
  | 'INVALID_ACCESS_KEY'
  | 'INVALID_CRN'
  | 'WORKSPACE_MISMATCH'
  | 'INVALID_WORKSPACE_ID'
  | 'UNKNOWN_ERROR'

/** An error thrown by this package, enriched with a machine-readable `.code`. */
export interface AuthError extends Error {
  code: AuthErrorCode
}

/**
 * Deprecated alias for {@link DeviceSessionStrategy}, exported at runtime as
 * `module.exports.OAuthStrategy = DeviceSessionStrategy`. Kept so existing
 * consumers don't break; will be removed in a future major release.
 *
 * @deprecated Renamed to `DeviceSessionStrategy`.
 */
export declare const OAuthStrategy: typeof DeviceSessionStrategy
