/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface AuthError extends Error {
  /** Machine-readable error code (e.g. `"INVALID_REGION"`, `"ACCESS_DENIED"`). */
  code: string
}
export interface TokenResult {
  /** The OAuth access token. */
  accessToken: string
  /** Token type, typically `"Bearer"`. */
  tokenType: string
  /** Number of seconds before the token expires. */
  expiresIn: number
}
/** Begin the OAuth 2.0 Device Authorization flow. */
export declare function beginDeviceCodeFlow(region: string, clientId: string): Promise<DeviceCodeResult>
/**
 * Variant of `beginDeviceCodeFlow` that targets a custom auth server URL.
 *
 * Intended for **testing only** — requires the crate to be built with the
 * `test-utils` Cargo feature.
 */
export declare function beginDeviceCodeFlowWithBaseUrl(region: string, clientId: string, baseUrl: string): Promise<DeviceCodeResult>
export declare class MockAuthServer {
  /** Start a mock auth server on a random port. */
  static start(): Promise<MockAuthServer>
  /** The base URL of the running mock server (e.g. `http://127.0.0.1:12345`). */
  get baseUrl(): string
  /**
   * Register a mock for `POST /oauth/device/code` that returns a standard
   * device-code JSON response.
   */
  mockDeviceCodeEndpoint(): void
  /**
   * Register a mock for `POST /oauth/device/token` that returns a standard
   * token JSON response.
   */
  mockTokenEndpoint(): void
  /**
   * Register a mock for `POST /oauth/device/token` that returns a 400 error
   * with the given OAuth error code and optional description.
   */
  mockTokenEndpointError(code: string, description?: string | undefined | null): void
  /** Remove all registered mocks. */
  clearMocks(): void
}
export declare class DeviceCodeResult {
  get userCode(): string
  get verificationUri(): string
  get verificationUriComplete(): string
  get expiresIn(): number
  /**
   * Poll the auth server until the user completes authorization.
   *
   * **Consumes** the internal handle — it cannot be reused after this call.
   * If you need to open the browser, call `openInBrowser` *before*
   * `pollForToken`.
   */
  pollForToken(): Promise<TokenResult>
  /**
   * Open the verification URI in the user's default browser.
   *
   * Does **not** consume the handle — you can still call `pollForToken`
   * afterwards.
   */
  openInBrowser(): boolean
}
