/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS, with manual additions for error enrichment */

/** Error codes attached to errors thrown by this package. */
export type AuthErrorCode =
  | 'REQUEST_ERROR'
  | 'ACCESS_DENIED'
  | 'EXPIRED_TOKEN'
  | 'INVALID_GRANT'
  | 'INVALID_CLIENT'
  | 'INVALID_URL'
  | 'INVALID_REGION'
  | 'INVALID_TOKEN'
  | 'SERVER_ERROR'
  | 'STORE_ERROR'
  | 'NOT_AUTHENTICATED'
  | 'MISSING_WORKSPACE_CRN'
  | 'INVALID_ACCESS_KEY'
  | 'INVALID_CRN'
  | 'WORKSPACE_MISMATCH'
  | 'INVALID_WORKSPACE_ID'
  | 'UNKNOWN_ERROR'

/** An error thrown by this package, enriched with a machine-readable `.code`. */
export interface AuthError extends Error {
  code: AuthErrorCode
}

/**
 * The result of a successful `getToken()` call.
 *
 * Contains the bearer credential and decoded JWT claims for service discovery.
 */
export interface TokenResult {
  /** The bearer token string (used as `Authorization: Bearer <token>`). */
  token: string
  /** The subject claim from the JWT (e.g. `"CS|auth0|user123"` or `"CS|CSAKkeyId"`). */
  subject: string
  /** The workspace identifier from the JWT. */
  workspaceId: string
  /** The issuer URL from the JWT `iss` claim (i.e. the CTS host). */
  issuer: string
  /** Service endpoint URLs from the JWT `services` claim (e.g. `{ zerokms: "https://..." }`). */
  services: Record<string, string>
}
/** Options for `AutoStrategy.detect()`. */
export interface AutoStrategyOptions {
  /** An explicit access key (takes precedence over `CS_CLIENT_ACCESS_KEY` env var). */
  accessKey?: string
  /** An explicit workspace CRN (takes precedence over `CS_WORKSPACE_CRN` env var). */
  workspaceCrn?: string
}
/**
 * Metadata returned after a successful device code authentication.
 *
 * The actual token is never exposed to JavaScript — it is saved directly
 * to `~/.cipherstash/auth.json` by the Rust layer.
 */
export interface AuthResult {
  /** Absolute epoch timestamp (seconds) when the token expires. */
  expiresAt: number
  /** Number of seconds before the token expires (computed at time of return). */
  expiresIn: number
}
/**
 * Provision a device client in ZeroKMS after login.
 *
 * Loads the auth token and device identity from `~/.cipherstash/`,
 * creates a client on the workspace's default keyset, and persists the
 * resulting secret key to `~/.cipherstash/secretkey.json`.
 *
 * This is a no-op if the secret key already exists or the server returns
 * 409 (conflict).
 */
export declare function bindClientDevice(): Promise<void>
/** Begin the OAuth 2.0 Device Authorization flow. */
export declare function beginDeviceCodeFlow(region: string, clientId: string): Promise<DeviceCodeResult>
/**
 * Variant of `beginDeviceCodeFlow` that targets a custom auth server URL.
 *
 * Intended for **testing only** — requires the crate to be built with the
 * `test-utils` Cargo feature.
 */
export declare function beginDeviceCodeFlowWithBaseUrl(region: string, clientId: string, baseUrl: string): Promise<DeviceCodeResult>
/**
 * Variant of `provisionDeviceClient` that uses a custom profile directory.
 *
 * Intended for **testing only** — requires the crate to be built with the
 * `test-utils` Cargo feature.
 */
export declare function bindClientDeviceWithProfileDir(profileDir: string): Promise<void>
/**
 * Save a test auth token to the given profile directory with the ZeroKMS
 * service URL set to `zerokms_base_url`.
 *
 * Intended for **testing only** — requires the crate to be built with the
 * `test-utils` Cargo feature.
 */
export declare function saveTestToken(profileDir: string, zerokmsBaseUrl: string): void
export declare class MockAuthServer {
  /** Start a mock auth server on a random port. */
  static start(): Promise<MockAuthServer>
  /** The base URL of the running mock server (e.g. `http://127.0.0.1:12345`). */
  get baseUrl(): string
  /**
   * Register a mock for `POST /oauth/device/code` that returns a standard
   * device-code JSON response.
   */
  mockDeviceCodeEndpoint(): void
  /**
   * Register a mock for `POST /oauth/device/token` that returns a standard
   * token JSON response.
   */
  mockTokenEndpoint(): void
  /**
   * Register a mock for `POST /oauth/device/token` that returns a 400 error
   * with the given OAuth error code and optional description.
   */
  mockTokenEndpointError(code: string, description?: string | undefined | null): void
  /**
   * Register a mock for `POST /api/authorise` that returns a successful
   * federation response (`{ accessToken, expiry }`), as CTS would for an
   * `OidcFederationStrategy` JWT exchange.
   *
   * `expiry` (seconds until the CTS token expires) defaults to 3600. Pass a
   * small value to exercise re-federation on expiry.
   */
  mockAuthorizeEndpoint(expiry?: number | undefined | null): void
  /** Register a mock for `POST /api/authorise` that returns a 500 error. */
  mockAuthorizeEndpointError(): void
  /**
   * Register a mock for `POST /create-client` that returns a successful
   * create-client JSON response (as ZeroKMS would).
   */
  mockCreateClientEndpoint(): void
  /** Register a mock for `POST /create-client` that returns a 409 conflict. */
  mockCreateClientConflict(): void
  /** Remove all registered mocks. */
  clearMocks(): void
}
/**
 * An auth strategy that auto-detects credentials from environment variables
 * and the local profile store.
 *
 * Detection order:
 * 1. `CS_CLIENT_ACCESS_KEY` env var (or explicit `accessKey` option) → access key auth
 * 2. `~/.cipherstash/auth.json` → OAuth token auth
 * 3. Error: not authenticated
 */
export declare class AutoStrategy {
  /**
   * Detect available credentials and return an `AutoStrategy`.
   *
   * Pass options to provide explicit values that take precedence over
   * environment variables.
   */
  static detect(options?: AutoStrategyOptions | undefined | null): AutoStrategy
  /** Retrieve a valid access token, refreshing or re-authenticating as needed. */
  getToken(): Promise<TokenResult>
}
/**
 * An auth strategy that uses a static access key for service-to-service
 * or CI/CD authentication, scoped to a single workspace identified by a
 * CRN. Region is derived from the CRN — there is no separate region
 * argument.
 *
 * Every issued token's `workspace` JWT claim is verified against the
 * CRN. A mismatch fails the `getToken()` call with a
 * `WORKSPACE_MISMATCH` error rather than silently letting a
 * multi-workspace access key operate against the wrong workspace.
 */
export declare class AccessKeyStrategy {
  /**
   * Create a new `AccessKeyStrategy` for the given workspace CRN and
   * access key.
   *
   * The CRN format is `crn:<region>:<workspace-id>` (e.g.
   * `"crn:ap-southeast-2.aws:ZVATKW3VHMFG27DY"`). Region is parsed from
   * the CRN and used for service discovery; the workspace ID is used to
   * verify every issued token belongs to the right workspace. A mismatch
   * fails `getToken()` with `code === "WORKSPACE_MISMATCH"`.
   */
  static create(workspaceCrn: string, accessKey: string): AccessKeyStrategy
  /** Retrieve a valid access token, refreshing or re-authenticating as needed. */
  getToken(): Promise<TokenResult>
}
/**
 * An auth strategy that uses OAuth refresh tokens persisted to disk
 * (`~/.cipherstash/auth.json`).
 */
export declare class DeviceSessionStrategy {
  /** Load credentials from the default profile store and create a `DeviceSessionStrategy`. */
  static fromProfile(): DeviceSessionStrategy
  /** Retrieve a valid access token, refreshing as needed. */
  getToken(): Promise<TokenResult>
}
/**
 * Deprecated alias for {@link DeviceSessionStrategy}, exported at runtime as
 * `module.exports.OAuthStrategy = DeviceSessionStrategy`. Kept so existing
 * consumers don't break; will be removed in a future major release.
 *
 * @deprecated Renamed to `DeviceSessionStrategy`.
 */
export declare const OAuthStrategy: typeof DeviceSessionStrategy
/**
 * An auth strategy that federates a third-party OIDC JWT (Clerk, Supabase, …)
 * into a CipherStash CTS service token via `/api/authorise`.
 */
export declare class OidcFederationStrategy {
  /**
   * Create an `OidcFederationStrategy` for the given region and workspace.
   *
   * `getJwt` is called on every federation — initial auth and every
   * re-federation after the CTS token expires — and must return
   * `Promise<string>` resolving to the *current* third-party OIDC JWT.
   */
  static create(region: string, workspaceId: string, getJwt: () => any): OidcFederationStrategy
  /**
   * Create an `OidcFederationStrategy` backed by external token-store callbacks.
   *
   * Behaves like [`create`](Self::create) but persists the federated CTS
   * token through `loadToken` (`() => Promise<string | null | undefined>`)
   * and `saveToken` (`(json: string) => Promise<void>`) — e.g. an HTTP-only
   * cookie — so a federated token survives across requests without
   * re-federating.
   */
  static createWithStore(region: string, workspaceId: string, getJwt: () => any, loadToken: () => any, saveToken: (arg: string) => any): OidcFederationStrategy
  /** Retrieve a valid CTS service token, federating or re-federating as needed. */
  getToken(): Promise<TokenResult>
}
export declare class DeviceCodeResult {
  get userCode(): string
  get verificationUri(): string
  get verificationUriComplete(): string
  get expiresIn(): number
  /**
   * Poll the auth server until the user completes authorization.
   *
   * **Consumes** the internal handle — it cannot be reused after this call.
   * If you need to open the browser, call `openInBrowser` *before*
   * `pollForToken`.
   */
  pollForToken(): Promise<AuthResult>
  /**
   * Open the verification URI in the user's default browser.
   *
   * Does **not** consume the handle — you can still call `pollForToken`
   * afterwards.
   */
  openInBrowser(): boolean
}
