// Generates the `@cipherstash/auth/wasm-inline` entry from wasm-pack output.
// Required because `--target bundler` emits `import * as wasm from "./*.wasm"`,
// which fails in runtimes that don't auto-bundle sibling `.wasm` assets — see
// README's "Why the explicit sub-path" section for the full rationale.

import { readFile, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const wasmDir = resolve(here, '..', 'wasm')

const wasmBytes = await readFile(resolve(wasmDir, 'stack_auth_wasm_bg.wasm'))
const base64 = wasmBytes.toString('base64')

const shim = `/* @ts-self-types="./stack_auth_wasm.d.ts" */
// Generated by scripts/inline-wasm.mjs — do not edit.

import * as bgImports from "./stack_auth_wasm_bg.js";

const WASM_BYTES_B64 = "${base64}";
const wasmBytes = Uint8Array.from(atob(WASM_BYTES_B64), (c) => c.charCodeAt(0));

const { instance } = await WebAssembly.instantiate(wasmBytes, {
  "./stack_auth_wasm_bg.js": bgImports,
});
bgImports.__wbg_set_wasm(instance.exports);
instance.exports.__wbindgen_start();

export {
    AccessKeyStrategy, OidcFederationStrategy, IntoUnderlyingByteSource, IntoUnderlyingSink, IntoUnderlyingSource, module_init
} from "./stack_auth_wasm_bg.js";
`

const outPath = resolve(wasmDir, 'stack_auth_wasm_inline.js')
await writeFile(outPath, shim)

console.log(
  `inline-wasm: wrote stack_auth_wasm_inline.js (` +
    `${wasmBytes.length} wasm bytes -> ${base64.length} b64 chars)`,
)
