// Postbuild step: emit an inline-bytes variant of the wasm-bindgen JS shim
// alongside the bundler-target output. Wasm-pack's `--target bundler` emits
// `import * as wasm from "./*.wasm"`, which works with Vite/Webpack but
// requires either a wasm-aware bundler or a runtime that auto-bundles the
// sibling `.wasm` asset. Edge runtimes (Supabase Edge, Cloudflare Workers)
// typically need explicit static-asset config to make the `.wasm` available.
//
// The inline variant embeds the wasm bytes as a base64 string inside the JS
// module so it loads with zero runtime config in any wasm-supporting runtime.
// Trade-off: ~30% larger JS payload (~880KB vs ~633KB raw wasm) and ~50ms
// cold-start vs streaming compile.

import { readFile, writeFile } from "node:fs/promises";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const wasmDir = resolve(here, "..", "wasm");

const wasmBytes = await readFile(resolve(wasmDir, "stack_auth_wasm_bg.wasm"));
const base64 = wasmBytes.toString("base64");

const shim = `/* @ts-self-types="./stack_auth_wasm.d.ts" */

// Inline-bytes variant of the wasm-bindgen JS shim. The wasm module is
// embedded as base64 below and instantiated at module load via top-level
// await. Use this entry from runtimes that don't auto-bundle sibling
// \`.wasm\` assets (Supabase Edge, Cloudflare Workers, browsers without a
// wasm-aware bundler). Generated by \`scripts/inline-wasm.mjs\`.

import * as bgImports from "./stack_auth_wasm_bg.js";

const WASM_BYTES_B64 = "${base64}";
const wasmBytes = Uint8Array.from(atob(WASM_BYTES_B64), (c) => c.charCodeAt(0));

const { instance } = await WebAssembly.instantiate(wasmBytes, {
  "./stack_auth_wasm_bg.js": bgImports,
});
bgImports.__wbg_set_wasm(instance.exports);
instance.exports.__wbindgen_start();

export {
    AccessKeyStrategy, IntoUnderlyingByteSource, IntoUnderlyingSink, IntoUnderlyingSource, module_init
} from "./stack_auth_wasm_bg.js";
`;

const outPath = resolve(wasmDir, "stack_auth_wasm_inline.js");
await writeFile(outPath, shim);

console.log(
  `inline-wasm: wrote stack_auth_wasm_inline.js (` +
    `${wasmBytes.length} wasm bytes -> ${base64.length} b64 chars)`,
);
