/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare class ProfileStore {
  /**
   * Create a profile store at the default location (`~/.cipherstash`),
   * or the path specified by the `CS_CONFIG_PATH` environment variable.
   */
  static resolve(): ProfileStore
  /** Create a profile store rooted at the given directory. */
  static withDir(dir: string): ProfileStore
  /** The directory path of this profile store. */
  get dir(): string
  /** Set the current workspace. */
  setCurrentWorkspace(workspaceId: string): void
  /**
   * Return the current workspace ID.
   *
   * Throws if no workspace has been set.
   */
  currentWorkspace(): string
  /** Remove the current workspace selection. */
  clearCurrentWorkspace(): void
  /** List workspace IDs that have profile data on disk. */
  listWorkspaces(): Array<string>
  /** Return a profile store scoped to a specific workspace directory. */
  workspaceStore(workspaceId: string): ProfileStore
  /**
   * Return a profile store scoped to the current workspace.
   *
   * Throws if no workspace has been set.
   */
  currentWorkspaceStore(): ProfileStore
}
