import { readdir, readFile, writeFile } from 'node:fs/promises'
import { join } from 'node:path'

/**
 * The encrypted column types this rewrite applies to: the single EQL v2 type,
 * and the whole EQL v3 concrete-domain family (`eql_v3_text_search`,
 * `eql_v3_integer_ord`, …). The v3 side is matched by shape rather than by an
 * enumerated list so a newly added domain is covered without touching this file
 * — the `eql_v3_` prefix is unambiguous in a `SET DATA TYPE` position.
 */
const ENCRYPTED_DOMAIN = String.raw`eql_v2_encrypted|eql_v3_[a-z0-9_]+`

/**
 * Extracts the bare domain name out of whichever mangled form matched.
 */
const DOMAIN_RE = /eql_v2_encrypted|eql_v3_[a-z0-9_]+/i

/**
 * The mangled forms drizzle-kit emits for a customType in an ALTER COLUMN.
 *
 * drizzle-kit's ALTER COLUMN path wraps the customType `dataType()` return
 * value in double-quotes and prepends `"{typeSchema}".`. Custom types have no
 * `typeSchema`, so the emitted SQL depends on BOTH what `dataType()` returned
 * and which drizzle-kit renders it. Verified against 0.24.2, 0.28.1, 0.30.6,
 * 0.31.0, 0.31.1 and 0.31.10 through `drizzle-kit/api`'s `generateMigration`:
 *
 * | `dataType()` returns            | <= 0.30.6                   | >= 0.31.0                          |
 * | ------------------------------- | --------------------------- | ---------------------------------- |
 * | `eql_v3_text_search` (current)  | `eql_v3_text_search`        | `"undefined"."eql_v3_text_search"` |
 * | `public.eql_v3_text_search`     | `public.eql_v3_text_search` | `"undefined"."public.eql_v3_…"`    |
 * | `"public"."eql_v2_encrypted"`   | `"public"."eql_v2_…"`       | `"undefined".""public"."eql_v2_…"` |
 *
 * The `"undefined".` prefix is a **0.31.0-and-later** behaviour — 0.30.6 and
 * earlier emit the plain form. (Issue #693 and PR #688 both describe it as an
 * artifact of *older* drizzle-kit; that is backwards.) All six forms stay
 * matched because a user's migration directory can hold files generated by any
 * drizzle-kit version against any stack version — including the qualified
 * `public.eql_v3_*` that stack emitted before #688.
 *
 * Ordered longest-first so the alternation cannot match a prefix of a longer
 * form and leave a trailing fragment behind.
 */
const MANGLED_TYPE_FORMS = [
  String.raw`"undefined"\.""public"\."(?:${ENCRYPTED_DOMAIN})""`,
  String.raw`"undefined"\."public\.(?:${ENCRYPTED_DOMAIN})"`,
  String.raw`"undefined"\."(?:${ENCRYPTED_DOMAIN})"`,
  String.raw`"public"\."(?:${ENCRYPTED_DOMAIN})"`,
  String.raw`public\.(?:${ENCRYPTED_DOMAIN})`,
  // Not emitted by any released drizzle-kit ALTER path, but it is the shape the
  // CREATE TABLE path renders — guard it in case ALTER converges on it.
  String.raw`"(?:${ENCRYPTED_DOMAIN})"`,
  String.raw`(?:${ENCRYPTED_DOMAIN})`,
].join('|')

/**
 * Matches drizzle-kit's generated in-place type change to an encrypted column
 * type, in any of the forms above.
 *
 * Captures:
 * - $1: table name (without quotes)
 * - $2: column name (without quotes)
 * - $3: the mangled type blob — feed it to {@link DOMAIN_RE} for the bare name
 */
const ALTER_COLUMN_TO_ENCRYPTED_RE = new RegExp(
  String.raw`ALTER TABLE "([^"]+)"\s+ALTER COLUMN "([^"]+)"\s+SET DATA TYPE (${MANGLED_TYPE_FORMS})[^;]*;`,
  'gi',
)

/**
 * Replace in-place `ALTER COLUMN ... SET DATA TYPE eql_v2_encrypted` statements
 * with an ADD + DROP + RENAME sequence.
 *
 * **Why this exists (CIP-2991, CIP-2994):** Postgres has no implicit cast from
 * `text`/`numeric` to `eql_v2_encrypted`, so `ALTER COLUMN ... SET DATA TYPE
 * eql_v2_encrypted` fails with `cannot cast type ... to eql_v2_encrypted`.
 * The fix that works on both empty and non-empty tables is to add a new
 * encrypted column, backfill it, drop the original, and rename the new
 * column into place. For empty tables the UPDATE is a no-op and the
 * sequence is effectively equivalent to DROP+ADD.
 *
 * We only rewrite the statement — the actual encryption of existing rows has
 * to happen in application code (via `encryptModel` from
 * `@cipherstash/stack`), which is why the UPDATE is emitted as a guidance
 * comment rather than real SQL. Running this migration against a populated
 * table leaves the new column NULL until the app backfills it.
 */
export async function rewriteEncryptedAlterColumns(
  outDir: string,
  options: { skip?: string } = {},
): Promise<string[]> {
  const entries = await readdir(outDir).catch(() => [])
  const rewritten: string[] = []

  for (const entry of entries) {
    if (!entry.endsWith('.sql')) continue
    const filePath = join(outDir, entry)
    if (options.skip && filePath === options.skip) continue

    const original = await readFile(filePath, 'utf-8')
    if (!ALTER_COLUMN_TO_ENCRYPTED_RE.test(original)) continue

    // Reset the regex's lastIndex — it's stateful on /g
    ALTER_COLUMN_TO_ENCRYPTED_RE.lastIndex = 0

    const updated = original.replace(
      ALTER_COLUMN_TO_ENCRYPTED_RE,
      (match: string, table: string, column: string, mangledType: string) => {
        const domain = DOMAIN_RE.exec(mangledType)?.[0]?.toLowerCase()
        // Unreachable — the outer regex only matches when a domain is present —
        // but leave the statement alone rather than emit a broken rewrite.
        if (!domain) return match
        return renderSafeAlter(table, column, domain)
      },
    )

    if (updated !== original) {
      await writeFile(filePath, updated, 'utf-8')
      rewritten.push(filePath)
    }
  }

  return rewritten
}

/**
 * The rewrite is identical for v2 and v3, and so is the backfill guidance.
 *
 * v3 stores the encrypted EQL jsonb envelope rather than v2's composite, which
 * might suggest the UPDATE could become real SQL — it cannot. The envelope is
 * produced by ZeroKMS via the client (`encryptModel` / `bulkEncryptModels`), so
 * there is no expression Postgres can evaluate to fill it, exactly as for v2.
 * The UPDATE therefore stays a guidance comment on both surfaces.
 *
 * What the v3 rollout path does change is the warning worth giving. This
 * sequence DROPS the plaintext column in the same migration; the staged
 * `stash encrypt` lifecycle (add → backfill → cutover → drop) deliberately
 * keeps both columns alive across deploys. On a populated production table that
 * staged path is the right one, so say so instead of implying this migration
 * implements it.
 */
function renderSafeAlter(
  table: string,
  column: string,
  domain: string,
): string {
  const tmp = `${column}__cipherstash_tmp`
  return [
    '-- Rewritten by stash: in-place ALTER COLUMN cannot cast to',
    `-- ${domain}. If "${table}" already has rows, backfill the new`,
    "-- column via @cipherstash/stack's encryptModel in application code BEFORE",
    '-- running this migration in production. Empty tables are safe as-is.',
    `-- This migration DROPS "${column}" — on a populated production table prefer`,
    '-- the staged `stash encrypt` path (add -> backfill -> cutover -> drop).',
    `ALTER TABLE "${table}" ADD COLUMN "${tmp}" "public"."${domain}";`,
    `-- UPDATE "${table}" SET "${tmp}" = /* encrypted value for ${column} */ NULL;`,
    `ALTER TABLE "${table}" DROP COLUMN "${column}";`,
    `ALTER TABLE "${table}" RENAME COLUMN "${tmp}" TO "${column}";`,
  ].join('\n')
}
