import { readdir, readFile, writeFile } from 'node:fs/promises'
import { join } from 'node:path'

/**
 * The encrypted column types this rewrite applies to: the single EQL v2 type,
 * and the whole EQL v3 concrete-domain family (`eql_v3_text_search`,
 * `eql_v3_integer_ord`, …). The v3 side is matched by shape rather than by an
 * enumerated list so a newly added domain is covered without touching this file
 * — the `eql_v3_` prefix is unambiguous in a `SET DATA TYPE` position.
 */
const ENCRYPTED_DOMAIN = String.raw`eql_v2_encrypted|eql_v3_[a-z0-9_]+`

/**
 * Extracts the bare domain name out of whichever mangled form matched. Derived
 * from {@link ENCRYPTED_DOMAIN} so the two can never drift out of sync — a new
 * domain added to the alternation is extracted here for free.
 */
const DOMAIN_RE = new RegExp(ENCRYPTED_DOMAIN, 'i')

/**
 * The mangled forms drizzle-kit emits for a customType in an ALTER COLUMN.
 *
 * drizzle-kit's ALTER COLUMN path wraps the customType `dataType()` return
 * value in double-quotes and prepends `"{typeSchema}".`. Custom types have no
 * `typeSchema`, so the emitted SQL depends on BOTH what `dataType()` returned
 * and which drizzle-kit renders it. Verified against 0.24.2, 0.28.1, 0.30.6,
 * 0.31.0, 0.31.1 and 0.31.10 through `drizzle-kit/api`'s `generateMigration`:
 *
 * | `dataType()` returns            | <= 0.30.6                   | >= 0.31.0                          |
 * | ------------------------------- | --------------------------- | ---------------------------------- |
 * | `eql_v3_text_search` (current)  | `eql_v3_text_search`        | `"undefined"."eql_v3_text_search"` |
 * | `public.eql_v3_text_search`     | `public.eql_v3_text_search` | `"undefined"."public.eql_v3_…"`    |
 * | `"public"."eql_v2_encrypted"`   | `"public"."eql_v2_…"`       | `"undefined".""public"."eql_v2_…"` |
 *
 * The `"undefined".` prefix is a **0.31.0-and-later** behaviour — 0.30.6 and
 * earlier emit the plain form. (Issue #693 and PR #688 both describe it as an
 * artifact of *older* drizzle-kit; that is backwards.) All six forms stay
 * matched because a user's migration directory can hold files generated by any
 * drizzle-kit version against any stack version — including the qualified
 * `public.eql_v3_*` that stack emitted before #688.
 *
 * Ordered longest-first so the alternation cannot match a prefix of a longer
 * form and leave a trailing fragment behind.
 */
const MANGLED_TYPE_FORMS = [
  String.raw`"undefined"\.""public"\."(?:${ENCRYPTED_DOMAIN})""`,
  String.raw`"undefined"\."public\.(?:${ENCRYPTED_DOMAIN})"`,
  String.raw`"undefined"\."(?:${ENCRYPTED_DOMAIN})"`,
  String.raw`"public"\."(?:${ENCRYPTED_DOMAIN})"`,
  String.raw`public\.(?:${ENCRYPTED_DOMAIN})`,
  // Not emitted by any released drizzle-kit ALTER path, but it is the shape the
  // CREATE TABLE path renders — guard it in case ALTER converges on it.
  String.raw`"(?:${ENCRYPTED_DOMAIN})"`,
  String.raw`(?:${ENCRYPTED_DOMAIN})`,
].join('|')

/**
 * Matches drizzle-kit's generated in-place type change to an encrypted column
 * type, in any of the forms above.
 *
 * Captures:
 * - $1: table name, OR the schema when a qualifier follows (both without quotes)
 * - $2: table name when schema-qualified (`"app"."users"`), else undefined
 * - $3: column name (without quotes)
 * - $4: the mangled type blob — feed it to {@link DOMAIN_RE} for the bare name
 *
 * The optional `(?:\."([^"]+)")?` after the first quoted name matches the
 * schema qualifier drizzle-kit emits for a `pgSchema()` table (`"app"."users"`).
 * A plain `\s+` between the two names could never cross the `.`, so those tables
 * were silently passed over.
 */
const ALTER_COLUMN_TO_ENCRYPTED_RE = new RegExp(
  // `\s*;` — not `[^;]*;` — so the type blob must run straight into the
  // statement terminator. drizzle-kit emits exactly that (no trailing clause),
  // and the tighter tail means a HAND-AUTHORED `SET DATA TYPE … USING <expr>;`
  // is left untouched instead of being silently rewritten (and its USING
  // discarded).
  String.raw`ALTER TABLE "([^"]+)"(?:\."([^"]+)")?\s+ALTER COLUMN "([^"]+)"\s+SET DATA TYPE (${MANGLED_TYPE_FORMS})\s*;`,
  'gi',
)

/**
 * A deliberately BROAD scan for statements that look like an in-place change to
 * an encrypted column but that the strict {@link ALTER_COLUMN_TO_ENCRYPTED_RE}
 * did not rewrite — a hand-authored `SET DATA TYPE … USING …;`, or some future
 * drizzle-kit form the strict matcher doesn't yet cover.
 *
 * It matches any single (`;`-terminated) statement that contains both
 * `SET DATA TYPE` and an `eql_v2`/`eql_v3` domain token at a word boundary (so
 * lookalikes like `eql_v4_…` or `not_eql_v3_…` don't trip it). Run AFTER the
 * strict rewrite so genuinely-rewritten statements — which no longer contain
 * `SET DATA TYPE` — are already gone; whatever this still finds is a near-miss
 * we flag for human review rather than silently ship as broken SQL.
 */
const NEAR_MISS_RE =
  /[^;]*?\bSET\s+DATA\s+TYPE\b[^;]*?\beql_v[23][a-z0-9_]*[^;]*?;/gi

/**
 * Blank lines and `--` line comments (including drizzle-kit's
 * `--> statement-breakpoint`) at the head of a {@link NEAR_MISS_RE} match.
 *
 * That regex opens with a lazy `[^;]*?`, whose only left boundary is the
 * previous `;` — or the start of the file when there is no preceding statement.
 * So the raw match drags in every comment and blank line since then, and a
 * near-miss in a file that opens with a comment block gets reported to the user
 * with that whole block glued to its front. Strip the preamble so the statement
 * we quote back reads as the offending statement alone.
 *
 * Only line comments are handled — `/* … *\/` block comments are not something
 * drizzle-kit emits, and a stray one costs cosmetics, not correctness.
 */
const STATEMENT_PREAMBLE_RE = /^(?:[^\S\n]*(?:--[^\n]*)?\n)+/

/** Drop the leading blank/comment lines a `[^;]*?`-anchored match dragged in. */
function trimStatementPreamble(statement: string): string {
  return statement.replace(STATEMENT_PREAMBLE_RE, '').trim()
}

/**
 * True when the character at `index` is INERT — it sits inside a SQL comment (a
 * `--` line comment, or a nestable block comment) or inside a single-quoted
 * string literal. Either way it is not a statement the database will execute,
 * so the rewrite must leave it exactly as written.
 *
 * **Why the rewrite needs this:** {@link ALTER_COLUMN_TO_ENCRYPTED_RE} is
 * comment-blind and {@link renderSafeAlter} returns MULTIPLE lines. Rewriting a
 * commented-out `-- ALTER TABLE … SET DATA TYPE …;` therefore leaves the
 * author's `-- ` prefix on line 1 only — lines 2+, including `DROP COLUMN`,
 * become live executable SQL and destroy the column. Commented SQL is inert by
 * definition, so the only correct move is to leave it exactly as written.
 *
 * **Why string literals count as inert too:** an ALTER quoted inside an
 * `INSERT … VALUES ('…')` is DATA. Rewriting it splices `--> statement-breakpoint`
 * markers INSIDE the literal, so splitting the file the way drizzle's migrator
 * does yields a bare, live `ALTER TABLE … DROP COLUMN …;` as a chunk of its own.
 * Escaping the injected text's own apostrophe (`@cipherstash/stack's`) would fix
 * only the syntax error, not that live DROP COLUMN — so the statement is left
 * as written, exactly like a commented one.
 *
 * Double-quoted identifiers are tokenised BEFORE `'` is considered: an
 * apostrophe inside `"o'brien_data"` must not open a phantom literal, or the
 * scan runs to the NEXT apostrophe — typically the same identifier in a
 * commented-out ALTER further down — decides that ALTER is live, and rewrites
 * it into a real `DROP COLUMN`. A doubled delimiter (`''` in a literal, `""` in
 * an identifier) is an escape and does not close the token.
 *
 * Dollar-quoted bodies are NOT tracked: a `--` or `'` inside one reads as a
 * comment/literal here, which can only make us skip a rewrite (the statement
 * then fails loudly at migrate time), never perform a destructive one.
 */
function isInsideCommentOrString(sql: string, index: number): boolean {
  let i = 0
  while (i < index) {
    if (sql.startsWith('--', i)) {
      const eol = sql.indexOf('\n', i)
      if (eol === -1 || eol >= index) return true
      i = eol + 1
    } else if (sql.startsWith('/*', i)) {
      // Postgres block comments nest, so track depth rather than stopping at
      // the first `*/` — a nested close would otherwise end the comment early
      // and let the text after it read as live SQL.
      let depth = 1
      let j = i + 2
      while (j < sql.length && depth > 0) {
        if (sql.startsWith('/*', j)) {
          depth += 1
          j += 2
        } else if (sql.startsWith('*/', j)) {
          depth -= 1
          j += 2
        } else {
          j += 1
        }
      }
      if (j > index) return true
      i = j
    } else if (sql[i] === '"') {
      // A quoted identifier is live SQL, but its body is not: consuming it here
      // — before the `'` branch below — is what stops an apostrophe inside one
      // from opening a string literal that never really existed.
      const end = endOfQuoted(sql, i, '"')
      // An unterminated identifier swallows the rest of the file, so treat it
      // as inert exactly like the unterminated literal below. Running the
      // cursor to the end instead would exit the loop and report `false` —
      // "live" — which is how the apostrophe bug destroyed a column in the
      // first place, one branch over.
      if (end > index) return true
      i = end
    } else if (sql[i] === "'") {
      const end = endOfQuoted(sql, i, "'")
      // Unterminated, or the literal runs past `index`: `index` is inside a
      // string literal, which is every bit as inert as a comment.
      if (end > index) return true
      i = end
    } else {
      i += 1
    }
  }
  return false
}

/**
 * The index just past the `quote`-delimited token that opens at `open`, or
 * `sql.length` when it is never closed. A doubled delimiter inside the token is
 * an escaped one (`''`, `""`) and does not end it.
 */
function endOfQuoted(sql: string, open: number, quote: "'" | '"'): number {
  let i = open + 1
  while (i < sql.length) {
    if (sql[i] !== quote) {
      i += 1
    } else if (sql[i + 1] === quote) {
      i += 2
    } else {
      return i + 1
    }
  }
  return sql.length
}

/** A table reference, bare (`"users"`) or schema-qualified (`"app"."users"`). */
const TABLE_REF = String.raw`"([^"]+)"(?:\."([^"]+)")?`

/**
 * An encrypted type in any of the {@link MANGLED_TYPE_FORMS}, pinned to end at a
 * delimiter so a bare domain cannot match a prefix of a longer identifier.
 */
const ENCRYPTED_TYPE_REF = String.raw`(?:${MANGLED_TYPE_FORMS})(?=[\s,;)]|$)`

/** `ALTER TABLE … ADD COLUMN "col" <encrypted>` — $1/$2 table, $3 column. */
const ADD_ENCRYPTED_COLUMN_RE = new RegExp(
  String.raw`ALTER TABLE\s+${TABLE_REF}\s+ADD COLUMN\s+(?:IF NOT EXISTS\s+)?"([^"]+)"\s+${ENCRYPTED_TYPE_REF}`,
  'gi',
)

/** `ALTER TABLE … RENAME COLUMN "a" TO "b"` — $1/$2 table, $3 from, $4 to. */
const RENAME_COLUMN_RE = new RegExp(
  String.raw`ALTER TABLE\s+${TABLE_REF}\s+RENAME COLUMN\s+"([^"]+)"\s+TO\s+"([^"]+)"`,
  'gi',
)

/** `CREATE TABLE … ( … );` — $1/$2 table, $3 the column-definition body. */
const CREATE_TABLE_RE = new RegExp(
  String.raw`CREATE TABLE\s+(?:IF NOT EXISTS\s+)?${TABLE_REF}\s*\(([\s\S]*?)\)\s*;`,
  'gi',
)

/** `"col" <encrypted>` inside a CREATE TABLE body — $1 column. */
const CREATE_TABLE_ENCRYPTED_COLUMN_RE = new RegExp(
  String.raw`"([^"]+)"\s+${ENCRYPTED_TYPE_REF}`,
  'gi',
)

/** Splits a `TABLE_REF` capture pair into its schema and table halves. */
function tableOf(
  first: string,
  second: string | undefined,
): { schema?: string; table: string } {
  // When schema-qualified (`"app"."users"`) the first capture is the schema and
  // the second is the table; otherwise the first is the table.
  return second === undefined
    ? { table: first }
    : { schema: first, table: second }
}

/** Identity of a column across the corpus, for {@link indexEncryptedColumns}. */
function columnKey(table: string, column: string, schema?: string): string {
  return JSON.stringify([schema ?? '', table, column])
}

/**
 * Index every column the migration corpus gives an ENCRYPTED type, so the
 * rewrite can tell the change it exists for (plaintext → encrypted) from one it
 * must never touch (encrypted → encrypted).
 *
 * **Why (#772 review, W-3):** the strict matcher captures only the TARGET type.
 * A column whose encrypted domain merely changes (`types.TextEq` →
 * `types.TextSearch`) matches just as well as a plaintext column, and the
 * ADD+DROP+RENAME then drops a column full of CIPHERTEXT — with no plaintext
 * left anywhere to backfill from, so unlike the plaintext case the data is not
 * recoverable from the application at all. Changing an encrypted column's domain
 * changes its index terms, so the data has to be re-encrypted through the client
 * regardless; the sweep flags the statement and leaves it for the user.
 *
 * The index is corpus-wide rather than ordered by migration: over-detecting
 * "encrypted" costs a flagged statement the user must handle by hand, while
 * under-detecting costs irrecoverable ciphertext. Only comment-free statements
 * count, for the same reason {@link isInsideCommentOrString} exists.
 */
function indexEncryptedColumns(contents: readonly string[]): Set<string> {
  const encrypted = new Set<string>()

  for (const sql of contents) {
    for (const created of sql.matchAll(CREATE_TABLE_RE)) {
      if (isInsideCommentOrString(sql, created.index)) continue
      const { schema, table } = tableOf(created[1], created[2])
      for (const column of created[3].matchAll(
        CREATE_TABLE_ENCRYPTED_COLUMN_RE,
      )) {
        encrypted.add(columnKey(table, column[1], schema))
      }
    }

    for (const added of sql.matchAll(ADD_ENCRYPTED_COLUMN_RE)) {
      if (isInsideCommentOrString(sql, added.index)) continue
      const { schema, table } = tableOf(added[1], added[2])
      encrypted.add(columnKey(table, added[3], schema))
    }

    // A rename carries the column's type with it — and `<col>__cipherstash_tmp`
    // renamed onto the real name is exactly what a previous sweep of this very
    // directory emitted. Run after ADD so that tmp column is already indexed.
    for (const renamed of sql.matchAll(RENAME_COLUMN_RE)) {
      if (isInsideCommentOrString(sql, renamed.index)) continue
      const { schema, table } = tableOf(renamed[1], renamed[2])
      if (encrypted.has(columnKey(table, renamed[3], schema))) {
        encrypted.add(columnKey(table, renamed[4], schema))
      }
    }
  }

  return encrypted
}

/** Why a recognised ALTER-to-encrypted statement was left alone. */
export type SkipReason =
  /** Outside the strict matcher — hand-authored `USING`, or an unknown form. */
  | 'unrecognised-form'
  /** The column already holds an encrypted domain; rewriting drops ciphertext. */
  | 'already-encrypted'

/** A statement the sweep recognised as ALTER-to-encrypted but did NOT rewrite. */
export interface SkippedAlter {
  /** Absolute path of the migration file the statement lives in. */
  file: string
  /** The offending statement, verbatim (trimmed), for the user to review. */
  statement: string
  /** Why it was left alone — the caller turns this into user-facing guidance. */
  reason: SkipReason
}

/**
 * One-line explanation of a {@link SkipReason}, for the CLI/wizard to print
 * next to the statement. Lives here so every caller says the same thing — the
 * two reasons need very different action from the user, and a single generic
 * "could not rewrite automatically" hides that.
 */
export function describeSkipReason(reason: SkipReason): string {
  switch (reason) {
    case 'already-encrypted':
      return "the column is ALREADY encrypted, so the ADD+DROP+RENAME rewrite would DROP the ciphertext with no plaintext left to backfill from. Changing an encrypted column's domain changes its index terms, so the data must be re-encrypted through the staged `stash encrypt` lifecycle"
    case 'unrecognised-form':
      return 'it falls outside the strict matcher (a hand-authored `SET DATA TYPE ... USING ...`, or a drizzle-kit form the sweep does not recognise) and an in-place cast to an encrypted domain fails at migrate time'
  }
}

/** Outcome of a sweep: the files rewritten, and near-misses left for review. */
export interface RewriteResult {
  /** Absolute paths of files whose unsafe ALTER COLUMN(s) were rewritten. */
  rewritten: string[]
  /** Near-miss statements the strict matcher passed over — flag, don't guess. */
  skipped: SkippedAlter[]
}

/**
 * Replace in-place `ALTER COLUMN ... SET DATA TYPE <encrypted domain>`
 * statements with an ADD + DROP + RENAME sequence.
 *
 * **Why this exists (CIP-2991, CIP-2994, #693):** Postgres has no implicit cast
 * from `text`/`numeric` to an encrypted domain, so `ALTER COLUMN ... SET DATA
 * TYPE eql_v2_encrypted` (or any `eql_v3_*` domain) fails at migrate time with
 * `cannot cast type ... to <domain>`. This applies equally to the single EQL v2
 * type and the whole EQL v3 concrete-domain family.
 *
 * The rewrite is an ADD+DROP+RENAME, which is **equivalent to DROP+ADD**: it
 * makes the column type valid but does NOT preserve the column's data. It is
 * therefore safe ONLY on an EMPTY table. On a populated table the new column
 * starts NULL and the original is dropped in the same migration, so the
 * plaintext is destroyed. The commented UPDATE is a placeholder that can never
 * become real SQL (the encrypted value is the EQL envelope produced by ZeroKMS
 * via the client — there is no expression Postgres can evaluate to fill it), so
 * a populated table must instead use the staged `stash encrypt` lifecycle
 * (add → backfill via `@cipherstash/stack`'s `encryptModel` → cutover → drop),
 * which keeps both columns alive across deploys. Each rewritten file carries a
 * header comment saying exactly this.
 *
 * Returns {@link RewriteResult}: the files rewritten, plus `skipped` statements
 * left for a human — ones outside the strict matcher (a hand-authored
 * `SET DATA TYPE … USING …;`, or a future drizzle-kit form), and ones targeting
 * a column that is ALREADY encrypted, where the rewrite would drop ciphertext.
 * Both are left untouched on disk and surfaced non-fatally so the caller can
 * tell the user to review them, rather than silently shipping broken SQL or
 * destroying data. Statements sitting inside a SQL comment — or inside a
 * single-quoted string literal, where they are data rather than SQL — are inert
 * and are neither rewritten nor reported.
 */
export async function rewriteEncryptedAlterColumns(
  outDir: string,
  options: { skip?: string } = {},
): Promise<RewriteResult> {
  const entries = await readdir(outDir).catch(
    (error: NodeJS.ErrnoException) => {
      // A missing directory is simply nothing to sweep. Anything else — EACCES
      // above all — is a sweep that did NOT happen, and the caller reports it
      // rather than letting the user believe their migrations were checked.
      if (error.code === 'ENOENT') return [] as string[]
      throw error
    },
  )
  const rewritten: string[] = []
  const skipped: SkippedAlter[] = []
  const seen = new Set<string>()

  /** Record a skip once — the strict pass and the broad scan can both find it. */
  const skip = (file: string, statement: string, reason: SkipReason): void => {
    // Keyed on collapsed whitespace: the two passes trim the same statement
    // by slightly different rules, and the strict pass runs first so its
    // more specific reason is the one kept.
    const key = `${file} :: ${statement.replace(/\s+/g, ' ')}`
    if (seen.has(key)) return
    seen.add(key)
    skipped.push({ file, statement, reason })
  }

  const sqlFiles = entries.filter((entry) => entry.endsWith('.sql')).sort()
  const contents = new Map<string, string>()
  for (const entry of sqlFiles) {
    const filePath = join(outDir, entry)
    contents.set(filePath, await readFile(filePath, 'utf-8'))
  }

  // Built from the WHOLE corpus, including `options.skip`: a column's current
  // type comes from the migrations that ran before this one, not just the files
  // we are allowed to edit.
  const encryptedColumns = indexEncryptedColumns([...contents.values()])

  for (const [filePath, original] of contents) {
    if (options.skip && filePath === options.skip) continue

    // Reset the regex's lastIndex — it's stateful on /g
    ALTER_COLUMN_TO_ENCRYPTED_RE.lastIndex = 0

    const updated = original.replace(
      ALTER_COLUMN_TO_ENCRYPTED_RE,
      (
        match: string,
        first: string,
        second: string | undefined,
        column: string,
        mangledType: string,
        offset: number,
      ) => {
        // Commented-out SQL never runs, and a multi-line replacement would only
        // inherit the `-- ` on its first line — leaving the rest live.
        if (isInsideCommentOrString(original, offset)) return match

        const { schema, table } = tableOf(first, second)

        // Already encrypted: the ADD+DROP+RENAME would drop the ciphertext and
        // there is no plaintext left to backfill from. Flag, never guess.
        if (encryptedColumns.has(columnKey(table, column, schema))) {
          skip(filePath, match.trim(), 'already-encrypted')
          return match
        }

        const domain = DOMAIN_RE.exec(mangledType)?.[0]?.toLowerCase()
        // Unreachable — the outer regex only matches when a domain is present —
        // but leave the statement alone rather than emit a broken rewrite.
        if (!domain) return match
        return renderSafeAlter(table, column, domain, schema)
      },
    )

    if (updated !== original) {
      await writeFile(filePath, updated, 'utf-8')
      rewritten.push(filePath)
    }

    // Broad secondary scan on the POST-rewrite content: anything still carrying
    // `SET DATA TYPE` near an eql_v2/eql_v3 token slipped past the strict
    // matcher. Flag it — non-fatally — rather than leave the user shipping SQL
    // that fails at migrate time.
    for (const nearMiss of updated.matchAll(NEAR_MISS_RE)) {
      const statement = trimStatementPreamble(nearMiss[0])
      // Anchor the comment test on the `SET DATA TYPE` itself: the match starts
      // at the previous `;`, so its own offset sits before any preamble.
      const keyword = nearMiss[0].search(/\bSET\s+DATA\s+TYPE\b/i)
      if (
        isInsideCommentOrString(updated, nearMiss.index + Math.max(keyword, 0))
      ) {
        continue
      }
      skip(filePath, statement, 'unrecognised-form')
    }
  }

  return { rewritten, skipped }
}

/**
 * The rewrite is identical for v2 and v3, and the ADD+DROP+RENAME sequence is
 * equivalent to DROP+ADD: it makes the column type valid but does NOT preserve
 * the column's data. It is therefore safe only on an EMPTY table. On a populated
 * table the new column starts NULL and the old one is dropped in the same
 * migration, so the plaintext is destroyed.
 *
 * The commented UPDATE is only a placeholder — it can never become real SQL. The
 * encrypted value is the EQL envelope produced by ZeroKMS via the client
 * (`encryptModel` / `bulkEncryptModels`); there is no expression Postgres can
 * evaluate to fill it. (v3 stores that envelope as jsonb rather than v2's
 * composite, but this is equally true on both surfaces.)
 *
 * So the guidance does NOT tell the user to backfill and run this migration —
 * that would still lose data on cutover. It points a populated table at the
 * staged `stash encrypt` lifecycle (add → backfill → cutover → drop), which
 * keeps both columns alive across deploys.
 */
function renderSafeAlter(
  table: string,
  column: string,
  domain: string,
  schema?: string,
): string {
  const tmp = `${column}__cipherstash_tmp`
  // Preserve the schema qualifier drizzle-kit emitted for pgSchema() tables so
  // the rewritten statements target the same object.
  const qualifiedTable = schema ? `"${schema}"."${table}"` : `"${table}"`
  return [
    '-- Rewritten by stash: in-place ALTER COLUMN cannot cast to',
    `-- ${domain}. This ADD+DROP+RENAME equals DROP+ADD and is safe ONLY if`,
    `-- ${qualifiedTable} is empty. On a populated table it DESTROYS existing "${column}"`,
    '-- data (the new column starts NULL) — do NOT run it there. Use the staged',
    "-- `stash encrypt` path instead: add -> backfill via @cipherstash/stack's",
    '-- encryptModel in application code -> cutover -> drop.',
    '-- NOTE: constraints, defaults, and indexes on the original column are NOT',
    '-- carried over by this ADD/DROP/RENAME — re-add any NOT NULL, DEFAULT,',
    '-- UNIQUE, or index definitions manually.',
    `ALTER TABLE ${qualifiedTable} ADD COLUMN "${tmp}" "public"."${domain}";`,
    `-- UPDATE ${qualifiedTable} SET "${tmp}" = /* encrypted value for ${column} */ NULL`,
    '--> statement-breakpoint',
    `ALTER TABLE ${qualifiedTable} DROP COLUMN "${column}";`,
    '--> statement-breakpoint',
    `ALTER TABLE ${qualifiedTable} RENAME COLUMN "${tmp}" TO "${column}";`,
  ].join('\n')
}
