//! Per-type "doubles" fixtures: each plaintext encrypted TWICE, so the table
//! carries equal-plaintext / distinct-ciphertext rows.
//!
//! Hand-written and non-catalog (like `v3_numeric_collision`): the catalog
//! `eql_v3_<T>` fixture is the curated `fixture_values()` set exactly (the
//! `scalars::*` matrix asserts that), so it has no room for duplicate
//! plaintexts. These tiny sibling tables (`fixtures.eql_v3_<T>_doubles`) exist
//! only so the credential-free fixture suite can prove "two independent
//! encryptions of one value compare equal" without any fresh test-time
//! encryption. Read ONLY by `property::cross_ciphertext`, never by the matrix.
//!
//! Plaintexts are the FIRST THREE of each type's curated `fixture_values()`
//! (guaranteed catalog-valid: text already excludes the empty string per #262,
//! temporals/numerics are already in-range), each duplicated once → 6 rows, 3
//! equal-plaintext pairs. Each value is encrypted independently by the driver,
//! so a repeated plaintext lands as a distinct ciphertext row.
//!
//! Gitignored output: tests/sqlx/fixtures/eql_v3_<T>_doubles.sql
//! (regenerated by `mise run fixture:generate:all`).

use anyhow::Result;

use crate::fixtures::driver::FixtureValue;
use crate::scalar_domains::ScalarType;

/// The comparison-capable scalar tokens that get a doubles fixture. `bool` is
/// storage-only (no equality domain) and is excluded.
pub const DOUBLES_TOKENS: &[&str] = &[
    "smallint",
    "integer",
    "bigint",
    "date",
    "timestamp",
    "numeric",
    "text",
];

/// How many distinct plaintexts to double. Small on purpose — the test only
/// needs a handful of equal-plaintext pairs.
const DISTINCT: usize = 3;

/// Repeat each value once, preserving order: `[a, b, c] -> [a, a, b, b, c, c]`.
fn doubled<T: Clone>(values: &[T]) -> Vec<T> {
    values.iter().flat_map(|v| [v.clone(), v.clone()]).collect()
}

/// Generate `fixtures.eql_v3_<T>_doubles` — the first `DISTINCT` catalog values,
/// each encrypted twice. Generic over the type: the fixture name, the plaintext
/// source, and the bloom-index decision are all derived from `T` (and the
/// catalog), so there are no per-token strings to keep in sync. Indexes mirror
/// the type's catalog fixture so the payload carries the same terms (`hm`,
/// `ob`, `op`, plus `bf` for `text`) and the doubles cast cleanly to every
/// comparison domain — including `_ord_ope`, whose CLLW-OPE determinism the
/// cross-ciphertext suite pins on these rows.
async fn generate_doubles_for<T>() -> Result<()>
where
    T: ScalarType + FixtureValue,
{
    let name = format!("eql_v3_{}_doubles", T::PG_TYPE);
    let head: Vec<T> = <T as ScalarType>::fixture_values()
        .iter()
        .take(DISTINCT)
        .cloned()
        .collect();
    let sample = doubled(&head);
    let mut spec = super::spec::FixtureSpec::new(&name)
        .with_index(super::index_kind::IndexKind::Unique)
        .with_index(super::index_kind::IndexKind::Ore)
        .with_index(super::index_kind::IndexKind::Ope);
    // text carries the Match (bloom) index too — derived from the catalog, not
    // hardcoded — so its doubles cast to `text_match` / `text_search` as well.
    if crate::scalar_domains::token_has_bloom_term(T::PG_TYPE) {
        spec = spec.with_index(super::index_kind::IndexKind::Match);
    }
    spec.with_column_type("jsonb")
        .with_values(&sample)
        .run()
        .await
}

/// Run the doubles generator for one catalog token. Loud catch-all so an
/// unwired token fails generation rather than silently skipping.
pub async fn generate(token: &str) -> Result<()> {
    match token {
        "smallint" => generate_doubles_for::<i16>().await,
        "integer" => generate_doubles_for::<i32>().await,
        "bigint" => generate_doubles_for::<i64>().await,
        "date" => generate_doubles_for::<chrono::NaiveDate>().await,
        "timestamp" => generate_doubles_for::<chrono::DateTime<chrono::Utc>>().await,
        "numeric" => generate_doubles_for::<rust_decimal::Decimal>().await,
        "text" => generate_doubles_for::<String>().await,
        other => anyhow::bail!(
            "no doubles generator wired for token '{other}'; add it to \
             fixtures::eql_doubles (DOUBLES_TOKENS + the generate dispatch)"
        ),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn doubled_repeats_each_value_once_in_order() {
        let src = [10i32, 20, 30];
        let out = doubled(&src);
        // 3 distinct plaintexts, each appearing exactly twice.
        assert_eq!(out, vec![10, 10, 20, 20, 30, 30]);
        for v in src {
            assert_eq!(out.iter().filter(|&&x| x == v).count(), 2);
        }
    }
}
