//! The `v3_doc_integer` fixture — a SteVec document carrying one integer scalar at
//! `$.field`, one row per `eql_domains::INTEGER_VALUES`. Lets the scalar matrix's
//! behaviour generators run against the entry extracted at that selector
//! (`payload -> SELECTOR`), reusing the integer oracle.
//!
//! Unlike the scalar fixtures (`FixtureSpec<i32>::run()` encrypts bare ints)
//! and `v3_ste_vec` (`FixtureSpec<serde_json::Value>::run()` makes the
//! `plaintext` column jsonb), this fixture is a SPLIT: the encryption input is a
//! `serde_json::Value` document stream while the generated `plaintext` oracle
//! column is bare `integer`. It therefore encrypts the documents directly via
//! `cipherstash::encrypt_store` and stores them through the
//! `FixtureSpec::run_with_payloads` seam, with a `FixtureSpec<i32>` driving the
//! plaintext schema and oracle.
//!
//! Gitignored output: tests/sqlx/fixtures/v3_doc_integer.sql (regenerated by
//! `mise run fixture:generate:all`).

use anyhow::Result;
use serde_json::Value;

use super::index_kind::IndexKind;
use super::spec::FixtureSpec;

/// The generated fixture name → table `fixtures.v3_doc_integer`, script
/// `v3_doc_integer.sql`, SQLx ref `scripts("v3_doc_integer")`.
const NAME: &str = "v3_doc_integer";

/// The generated `payload` column type — the `public.eql_v3_json_search` document DOMAIN, so
/// the domain CHECK runs when the fixture loads.
const PAYLOAD_TYPE: &str = "public.eql_v3_json_search";

/// JSON path encrypted in each document. The SteVec selector hash for this
/// path is pinned in `SELECTOR` below.
const FIELD: &str = "field";

/// The SteVec selector hash for the `$.field` **CLLW-OPE (`op`)** entry,
/// constant across every row (same path + index → same selector). SteVec emits
/// a path entry carrying `op` plus term-less value-selector entries under
/// distinct selectors. The matrix needs the path entry because
/// `eql_v3.ord_term` requires `op`.
///
/// Read from the generated fixture and pinned here so a future selector drift
/// fails loudly: the integration `jsonb_entry` suite extracts the entry at
/// `payload -> SELECTOR` and asserts it is non-NULL and `op`-carrying for every
/// row, which only holds if this matches the emitted selector. The selector is
/// derived from the workspace keyset + the fixed STE_VEC_PREFIX + the `field`
/// path, so it is stable for a given CipherStash workspace; if it drifts,
/// regenerate the fixture and re-pin from the emitted `"s"`.
pub const SELECTOR: &str = "fce8be759db230351b10a058b7ba50a7";

/// Build the plaintext documents: `{"field": <value>}` per integer fixture value,
/// paired with the bare integer oracle value.
fn documents() -> Vec<(i32, Value)> {
    eql_domains::INTEGER_VALUES
        .iter()
        .map(|&v| (v, serde_json::json!({ FIELD: v })))
        .collect()
}

/// Generate `tests/sqlx/fixtures/v3_doc_integer.sql`. Splits the two value
/// streams: the `serde_json::Value` documents are encrypted with
/// `IndexKind::SteVec`, while the `integer` plaintexts drive the fixture-table
/// schema and the generated `plaintext` oracle column. `.run()` is NOT used —
/// it would encrypt bare `i32` values instead of `{"field": int}` documents.
pub async fn generate() -> Result<()> {
    use super::cipherstash;

    let pairs = documents();
    let plaintexts: Vec<i32> = pairs.iter().map(|(v, _)| *v).collect();
    let docs: Vec<Value> = pairs.into_iter().map(|(_, doc)| doc).collect();

    let spec = FixtureSpec::new(NAME)
        .with_index(IndexKind::SteVec)
        .with_column_type(PAYLOAD_TYPE)
        .with_values(&plaintexts);
    let working = spec.working_table();

    // `encrypt_store` builds the SteVec ColumnConfig from the spec's index
    // set + the document CAST, and returns payloads already converted to the
    // v3 envelope (root `{v: 3, k: "sv", i, h, sv}`), emitted natively by the
    // client's v3 assembler.
    let payloads =
        cipherstash::encrypt_store(&working, cipherstash::PAYLOAD_COLUMN, &docs, spec.indexes())
            .await?;
    anyhow::ensure!(
        payloads.len() == plaintexts.len(),
        "encrypt_store returned {} payloads for {} documents",
        payloads.len(),
        plaintexts.len(),
    );

    spec.run_with_payloads(payloads).await
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn documents_are_one_per_integer_fixture_value() {
        let docs = documents();
        assert_eq!(docs.len(), eql_domains::INTEGER_VALUES.len());
        for (v, doc) in &docs {
            assert_eq!(doc[FIELD].as_i64(), Some(*v as i64));
        }
    }

    /// Every integer pivot the scalar matrix sweeps (`min`/`max`/`mid`) must be a
    /// fixture row, since the entry matrix fetches each pivot's entry payload
    /// via `fetch_fixture_payload`.
    #[test]
    fn fixture_covers_the_scalar_pivots() {
        let plaintexts: Vec<i32> = documents().into_iter().map(|(v, _)| v).collect();
        for pivot in [i32::MIN, 0, i32::MAX] {
            assert!(
                plaintexts.contains(&pivot),
                "v3_doc_integer must carry the integer pivot {pivot}",
            );
        }
    }

    #[test]
    fn selector_is_a_32_hex_string() {
        assert_eq!(SELECTOR.len(), 32, "SELECTOR must be a 16-byte hex hash");
        assert!(
            SELECTOR.chars().all(|c| c.is_ascii_hexdigit()),
            "SELECTOR must be lowercase hex: {SELECTOR}",
        );
    }
}
