//! The `v3_numeric_collision` fixture — the scale-equivalence collision pair
//! (`1`, `1.0`) plus a `2` discriminator, encrypted at numeric ORE width.
//!
//! Hand-written, non-catalog (like `v3_ste_vec` / `v3_doc_integer`, hence the
//! `v3_` prefix), because the catalog-driven `eql_v3_numeric` fixture CANNOT
//! carry it: `numeric_value_guards::fixtures_are_distinct_by_value` forbids two
//! fixtures that alias to the same `Decimal`, and `1` / `1.0` are value-equal.
//! So the `1 == 1.0` ORE collision — that scale-equivalent decimals encrypt to
//! comparison-equal ORE terms — has no catalog home. This tiny bespoke fixture
//! is the only place those two representations can coexist.
//!
//! Rows are addressed by `id` (NOT `plaintext`): `WHERE plaintext = 1` matches
//! both `1` and `1.0` (numeric equality ignores scale), so the collision test
//! fetches `id = 1` (`1`), `id = 2` (`1.0`), `id = 3` (`2`). The `id` is the
//! 1-based insertion ordinal the driver assigns over `VALUES`.
//!
//! Gitignored output: tests/sqlx/fixtures/v3_numeric_collision.sql
//! (regenerated by `mise run fixture:generate:all`).

use anyhow::Result;
use rust_decimal::Decimal;
use std::str::FromStr;

use super::index_kind::IndexKind;
use super::spec::FixtureSpec;

/// The generated fixture name → table `fixtures.v3_numeric_collision`, script
/// `v3_numeric_collision.sql`, SQLx ref `scripts("v3_numeric_collision")`.
const NAME: &str = "v3_numeric_collision";

/// The fixture plaintexts, in insertion order. `id` is the 1-based ordinal, so
/// `1` → id 1, `1.0` → id 2, `2` → id 3. `1` and `1.0` are deliberately
/// value-equal (the collision pair); `2` is a distinct discriminator so the
/// test can prove the comparator is not a degenerate everything-collides.
fn values() -> Vec<Decimal> {
    ["1", "1.0", "2"]
        .iter()
        .map(|s| Decimal::from_str(s).expect("valid decimal literal"))
        .collect()
}

/// Generate `tests/sqlx/fixtures/v3_numeric_collision.sql`. Encrypts the
/// three decimals at numeric ORE width via the standard `.run()` driver — the
/// encryption input and the `plaintext` oracle column are the same value stream,
/// so no split (`run_with_payloads`) is needed.
pub async fn generate() -> Result<()> {
    let values = values();
    FixtureSpec::new(NAME)
        .with_index(IndexKind::Unique)
        .with_index(IndexKind::Ore)
        .with_column_type("jsonb")
        .with_values(&values)
        .run()
        .await
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_collision_pair_is_value_equal_but_distinct_in_scale() {
        let v = values();
        assert_eq!(v.len(), 3, "fixture is [1, 1.0, 2]");
        // The collision pair compares equal by value...
        assert_eq!(v[0], v[1], "1 and 1.0 must be value-equal (the collision)");
        // ...yet is two distinct textual representations (different scale), so
        // the catalog distinctness guard would reject them together.
        assert_ne!(
            v[0].scale(),
            v[1].scale(),
            "1 (scale 0) and 1.0 (scale 1) must differ in scale"
        );
        // The discriminator is genuinely larger.
        assert!(v[2] > v[0], "2 must order after 1");
    }
}
