//! The `v3_text_empty` fixture — the empty string `""` plus two non-empty
//! controls, encrypted as ordered text.
//!
//! Hand-written, non-catalog (like `v3_numeric_collision`), because the
//! catalog-driven `eql_v2_text` fixture deliberately EXCLUDES `""`: encrypting
//! the empty string yields an empty ORE term (`ob: []`), the only value that
//! does, so `eql-domains::TEXT_FIXTURES` drops it. This bespoke fixture is the
//! one place a real-ciphertext empty-`ob` payload lives — its purpose is to
//! prove the ORE-bearing `public.eql_v3_text_ord_ore` REJECTS that payload at its
//! non-empty-`ob` CHECK (issue #262, SQLSTATE `23514`), while the non-empty
//! controls cast and order cleanly. See `tests/v3_text_empty_constraint_tests.rs`.
//!
//! The empty string is an ORE-only failure mode. The same encryption yields a
//! well-formed OPE term (`op: "00"` — the bare domain-tag byte), which decodes
//! to a 1-byte `bytea` that sorts before every non-empty term. So the
//! OPE-backed `public.eql_v3_text_ord` ACCEPTS `""` and orders it first; only
//! `public.eql_v3_text_ord_ore` rejects it.
//!
//! The generated `payload` column is plain `jsonb`, so all three rows load; the
//! rejection happens when a test casts the `id = 1` row to
//! `public.eql_v3_text_ord_ore`, not at fixture load.
//!
//! Rows are addressed by `id` (1-based insertion ordinal): `"" → 1`,
//! `"frank" → 2`, `"zebra" → 3`. The two non-empty controls are strictly
//! ordered (`"frank" < "zebra"`) so ordering of real values stays unambiguous.
//!
//! Gitignored output: tests/sqlx/fixtures/v3_text_empty.sql
//! (regenerated by `mise run fixture:generate:all`).

use anyhow::Result;

use super::index_kind::IndexKind;
use super::spec::FixtureSpec;

/// The generated fixture name → table `fixtures.v3_text_empty`, script
/// `v3_text_empty.sql`, SQLx ref `scripts("v3_text_empty")`.
const NAME: &str = "v3_text_empty";

/// The fixture plaintexts, in insertion order. `id` is the 1-based ordinal, so
/// `"" → 1`, `"frank" → 2`, `"zebra" → 3`. The empty string is the value with
/// the empty ORE term (`ob: []`) that the `_ord_ore` CHECK rejects; the two
/// non-empty controls carry real ORE terms that cast and order cleanly. All
/// three carry a well-formed OPE term (`op`).
fn values() -> Vec<String> {
    ["", "frank", "zebra"]
        .iter()
        .map(|s| s.to_string())
        .collect()
}

/// Generate `tests/sqlx/fixtures/v3_text_empty.sql`. Encrypts the three strings
/// as ordered text (Unique drives the `hm` equality term, Ore drives the `ob`
/// order term — empty for `""`) via the standard `.run()` driver.
pub async fn generate() -> Result<()> {
    let values = values();
    FixtureSpec::new(NAME)
        .with_index(IndexKind::Unique)
        .with_index(IndexKind::Ore)
        .with_index(IndexKind::Ope)
        .with_values(&values)
        .run()
        .await
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn empty_is_first_and_controls_are_ordered() {
        let v = values();
        assert_eq!(v.len(), 3, "fixture is [\"\", \"frank\", \"zebra\"]");
        assert!(v[0].is_empty(), "id 1 must be the empty string");
        assert!(
            !v[1].is_empty() && !v[2].is_empty(),
            "controls are non-empty"
        );
        // The controls are strictly ordered so ordering is unambiguous.
        assert!(v[1] < v[2], "\"frank\" must order before \"zebra\"");
    }
}
