//! The `v3_text_empty_bloom` fixture — a real-ciphertext empty **bloom filter**
//! (`bf: []`) plus a non-empty control, encrypted for fuzzy match (`@@`).
//!
//! Hand-written, non-catalog (like `v3_text_empty` / `v3_numeric_collision`),
//! because `eql-domains::TEXT_FIXTURES` carries no sub-trigram value: its
//! shortest string is 3 characters (`"bob"`), which already yields one trigram
//! and so a non-empty bloom. A value shorter than the trigram floor produces an
//! empty bloom (`bf: []`) — the only value that does — so this bespoke fixture
//! is the one place a real-ciphertext empty-`bf` payload lives.
//!
//! Its purpose is to prove the empty-needle guard in `eql_v3.matches`: an empty
//! needle bloom must match only a value whose own bloom is also empty (the
//! `LIKE ''` shape), never every row. See
//! `tests/encrypted_domain/text/text_match.rs` (the `empty_bloom_*` tests).
//!
//! Rows are addressed by `id` (1-based insertion ordinal):
//!   - `"pq"       → 1` — 2 chars, below the trigram floor → real `bf: []`.
//!   - `"aardvark" → 2` — the non-empty control (shares the `aard*` n-grams
//!     used elsewhere in the match suite).
//!
//! The empty-bloom value is deliberately a real 2-character encryption rather
//! than a hand-built `{"bf": []}` blob: EQL tests must exercise real crypto, not
//! synthetic index terms. The `empty_bloom_needle_is_actually_empty` test guards
//! the premise — if a future client change stops emitting `bf: []` for a
//! sub-trigram value, that guard fails loudly rather than the behavioural tests
//! passing vacuously.
//!
//! Gitignored output: tests/sqlx/fixtures/v3_text_empty_bloom.sql
//! (regenerated by `mise run fixture:generate:all`).

use anyhow::Result;

use super::index_kind::IndexKind;
use super::spec::FixtureSpec;

/// The generated fixture name → table `fixtures.v3_text_empty_bloom`, script
/// `v3_text_empty_bloom.sql`, SQLx ref `scripts("v3_text_empty_bloom")`.
const NAME: &str = "v3_text_empty_bloom";

/// The fixture plaintexts, in insertion order. `id` is the 1-based ordinal, so
/// `"pq" → 1`, `"aardvark" → 2`. `"pq"` is sub-trigram (empty bloom); the
/// control carries a non-empty bloom.
fn values() -> Vec<String> {
    ["pq", "aardvark"].iter().map(|s| s.to_string()).collect()
}

/// Generate `tests/sqlx/fixtures/v3_text_empty_bloom.sql`. Encrypts both strings
/// for fuzzy match (the `Match` index drives the `bf` bloom term — empty for the
/// sub-trigram `"pq"`) via the standard `.run()` driver.
pub async fn generate() -> Result<()> {
    let values = values();
    FixtureSpec::new(NAME)
        .with_index(IndexKind::Match)
        .with_values(&values)
        .run()
        .await
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn sub_trigram_first_and_control_second() {
        let v = values();
        assert_eq!(v.len(), 2, "fixture is [\"pq\", \"aardvark\"]");
        assert!(
            v[0].len() < 3,
            "id 1 must be below the trigram floor (empty bloom)"
        );
        assert!(
            v[1].len() >= 3,
            "id 2 (the control) must carry a non-empty bloom"
        );
    }
}
