// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package eqldb

import (
	"github.com/cipherstash/stack/languages/golang/stackencrypt/eqlv3"
)

type User struct {
	ID    int64            `db:"id"`
	Email eqlv3.TextSearch `db:"email"`
	Age   eqlv3.IntegerOrd `db:"age"`
	Attrs eqlv3.JSONSearch `db:"attrs"`
}
