// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package eqldb

import (
	"context"

	"github.com/cipherstash/stack/languages/golang/stackencrypt/eqlv3"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (id, email, age, attrs) VALUES ($1, $2, $3, $4)
`

type CreateUserParams struct {
	ID    int64            `db:"id"`
	Email eqlv3.TextSearch `db:"email"`
	Age   eqlv3.IntegerOrd `db:"age"`
	Attrs eqlv3.JSONSearch `db:"attrs"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.Age,
		arg.Attrs,
	)
	return err
}

const findUsersByEmail = `-- name: FindUsersByEmail :many
SELECT id, email, age, attrs FROM users WHERE email = $1::eql_v3.query_text_search
`

// One cast, straight to the query domain: sqlc types a parameter by its first
// cast, so ::jsonb::eql_v3.query_text_search would generate json.RawMessage.
func (q *Queries) FindUsersByEmail(ctx context.Context, email eqlv3.QueryTextSearch) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, findUsersByEmail, email)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Age,
			&i.Attrs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersOlderThan = `-- name: ListUsersOlderThan :many
SELECT id, email, age, attrs FROM users WHERE age > $1::eql_v3.query_integer_ord ORDER BY age
`

func (q *Queries) ListUsersOlderThan(ctx context.Context, minAge eqlv3.QueryIntegerOrd) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsersOlderThan, minAge)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Age,
			&i.Attrs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUsersByEmail = `-- name: SearchUsersByEmail :many
SELECT id, email, age, attrs FROM users WHERE email @@ $1::eql_v3.query_text_search
`

func (q *Queries) SearchUsersByEmail(ctx context.Context, pattern eqlv3.QueryTextSearch) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, searchUsersByEmail, pattern)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Age,
			&i.Attrs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
