import { execFileSync } from "node:child_process";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { afterEach, beforeEach, describe, expect, it } from "vitest";

// Guards the index.d.ts normaliser that re-applies the hand-curated additions
// NAPI-RS can't emit (`AuthError`/`AuthErrorCode`/`OAuthStrategy`). If this
// script silently regresses, those types vanish from the published package
// again (the exact bug it was written to fix), so its re-inject / idempotency
// behaviour is pinned here.

const SCRIPT = fileURLToPath(
  new URL("../scripts/apply-dts-additions.mjs", import.meta.url),
);

// A stand-in for `napi build` output: the NAPI-RS header plus a regular class
// (so the appended `OAuthStrategy` alias has a referent).
const GENERATED = `/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare class DeviceSessionStrategy {
  static fromProfile(): DeviceSessionStrategy
  getToken(): Promise<TokenResult>
}
`;

const MANUAL_SYMBOLS = [
  "export type AuthErrorCode",
  "export interface AuthError extends Error",
  "export declare const OAuthStrategy",
];

describe("apply-dts-additions", () => {
  let dir: string;
  let dts: string;

  beforeEach(() => {
    dir = mkdtempSync(join(tmpdir(), "apply-dts-"));
    dts = join(dir, "index.d.ts");
  });

  afterEach(() => {
    rmSync(dir, { recursive: true, force: true });
  });

  function run() {
    execFileSync("node", [SCRIPT, dts], { encoding: "utf8" });
    return readFileSync(dts, "utf8");
  }

  it("re-injects the curated additions a build drops", () => {
    writeFileSync(dts, GENERATED);
    const out = run();
    for (const sym of MANUAL_SYMBOLS) {
      expect(out, `should re-inject ${sym}`).toContain(sym);
    }
    // The header is annotated so it's clear the file isn't pristine NAPI-RS output.
    expect(out).toContain("with manual additions");
  });

  it("preserves generated declarations", () => {
    writeFileSync(dts, GENERATED);
    const out = run();
    expect(out).toContain("export declare class DeviceSessionStrategy");
  });

  it("is idempotent — a second run is a no-op", () => {
    writeFileSync(dts, GENERATED);
    const first = run();
    const second = run();
    expect(second).toBe(first);
  });

  it("does not corrupt a file with a dangling BEGIN marker (no END)", () => {
    // Exercises stripManualBlock's defensive branch: a BEGIN marker with no
    // matching END means the file was hand-truncated mid-block. The contract is
    // "leave the existing content untouched rather than corrupt it" — a
    // regression that sliced from BEGIN to EOF would drop everything after the
    // marker. We assert the content following the dangling marker survives.
    const dangling = `/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare class DeviceSessionStrategy {}

// --- BEGIN manual additions (scripts/apply-dts-additions.mjs) ---
export declare const DANGLING_SENTINEL: string
`;
    writeFileSync(dts, dangling);
    const out = run();
    // The text after the dangling BEGIN must not be sliced away.
    expect(out).toContain("DANGLING_SENTINEL");
    // And the real declaration ahead of it is still there.
    expect(out).toContain("export declare class DeviceSessionStrategy");
  });
});
