import { execFileSync } from "node:child_process";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { afterEach, beforeEach, describe, expect, it } from "vitest";

// Guards the durable index.d.ts normaliser that keeps the published type
// surface correct across `napi build` regenerations. If this script silently
// regresses, the `AuthError`/`OAuthStrategy` types vanish from the published
// package again (the exact bug it was written to fix), so its strip /
// re-inject / idempotency behaviour is pinned here.

const SCRIPT = fileURLToPath(
  new URL("../scripts/apply-dts-additions.mjs", import.meta.url),
);

// A stand-in for a `napi build --features test-utils` output: NAPI-RS header,
// a regular class (so the appended `OAuthStrategy` alias has a referent), and
// the test-utils-only exports that must be stripped from the published surface.
const GENERATED_WITH_TEST_UTILS = `/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare class DeviceSessionStrategy {
  static fromProfile(): DeviceSessionStrategy
  getToken(): Promise<TokenResult>
}
/**
 * Variant of \`beginDeviceCodeFlow\` that targets a custom auth server URL.
 *
 * Intended for **testing only**.
 */
export declare function beginDeviceCodeFlowWithBaseUrl(region: string, clientId: string, baseUrl: string): Promise<DeviceCodeResult>
/** Testing only. */
export declare function bindClientDeviceWithProfileDir(profileDir: string): Promise<void>
/** Testing only. */
export declare function saveTestToken(profileDir: string, zerokmsBaseUrl: string): void
export declare class MockAuthServer {
  static start(): Promise<MockAuthServer>
  get baseUrl(): string
  clearMocks(): void
}
`;

const TEST_UTILS_SYMBOLS = [
  "beginDeviceCodeFlowWithBaseUrl",
  "bindClientDeviceWithProfileDir",
  "saveTestToken",
  "MockAuthServer",
];

const MANUAL_SYMBOLS = [
  "export type AuthErrorCode",
  "export interface AuthError extends Error",
  "export declare const OAuthStrategy",
];

describe("apply-dts-additions", () => {
  let dir: string;
  let dts: string;

  beforeEach(() => {
    dir = mkdtempSync(join(tmpdir(), "apply-dts-"));
    dts = join(dir, "index.d.ts");
  });

  afterEach(() => {
    rmSync(dir, { recursive: true, force: true });
  });

  function run() {
    execFileSync("node", [SCRIPT, dts], { encoding: "utf8" });
    return readFileSync(dts, "utf8");
  }

  it("re-injects the curated additions a release build drops", () => {
    writeFileSync(dts, GENERATED_WITH_TEST_UTILS);
    const out = run();
    for (const sym of MANUAL_SYMBOLS) {
      expect(out, `should re-inject ${sym}`).toContain(sym);
    }
    // The header is annotated so it's clear the file isn't pristine NAPI-RS output.
    expect(out).toContain("with manual additions");
  });

  it("strips test-utils-only exports from the published surface", () => {
    writeFileSync(dts, GENERATED_WITH_TEST_UTILS);
    const out = run();
    for (const sym of TEST_UTILS_SYMBOLS) {
      expect(out, `should strip ${sym}`).not.toContain(sym);
    }
    // The MockAuthServer class body must go too, not just its name.
    expect(out).not.toContain("static start(): Promise<MockAuthServer>");
  });

  it("preserves non-test-utils declarations", () => {
    writeFileSync(dts, GENERATED_WITH_TEST_UTILS);
    const out = run();
    expect(out).toContain("export declare class DeviceSessionStrategy");
  });

  it("is idempotent — a second run is a no-op", () => {
    writeFileSync(dts, GENERATED_WITH_TEST_UTILS);
    const first = run();
    const second = run();
    expect(second).toBe(first);
  });
});
