// @generated by eql-codegen from the eql-domains catalog — do not edit
//! The `bigint` encrypted-domain family — generated from the eql-domains catalog.
use crate::v3::terms::{Ciphertext, Hmac256, OpeCllw, OreBlock256};
use crate::v3::DomainType;
use crate::{Identifier, SchemaVersion};
use schemars::{schema_for, JsonSchema, Schema};
use serde::{Deserialize, Serialize};
use ts_rs::TS;
/// `public.eql_v3_bigint` — storage-only domain.
///
/// Operators: none. Required keys: `v` `i` `c`.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
#[ts(export, export_to = "v3/")]
#[serde(deny_unknown_fields)]
pub struct Bigint {
    pub v: SchemaVersion,
    pub i: Identifier,
    pub c: Ciphertext,
}
impl DomainType for Bigint {
    fn sql_domain_static() -> &'static str {
        "public.eql_v3_bigint"
    }
    fn sql_domain(&self) -> &'static str {
        Self::sql_domain_static()
    }
    fn term_json_keys_static() -> Option<&'static [&'static str]> {
        Some(&[])
    }
    fn term_json_keys(&self) -> Option<&'static [&'static str]> {
        Self::term_json_keys_static()
    }
    fn parse_value(&self, value: &serde_json::Value) -> Result<(), serde_json::Error> {
        Bigint::deserialize(value).map(|_| ())
    }
    fn schema(&self) -> Schema {
        schema_for!(Bigint)
    }
}
/// `public.eql_v3_bigint_eq` — equality domain.
///
/// Operators: `=` `<>`. Required keys: `v` `i` `c` `hm`.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
#[ts(export, export_to = "v3/")]
#[serde(deny_unknown_fields)]
pub struct BigintEq {
    pub v: SchemaVersion,
    pub i: Identifier,
    pub c: Ciphertext,
    pub hm: Hmac256,
}
impl DomainType for BigintEq {
    fn sql_domain_static() -> &'static str {
        "public.eql_v3_bigint_eq"
    }
    fn sql_domain(&self) -> &'static str {
        Self::sql_domain_static()
    }
    fn term_json_keys_static() -> Option<&'static [&'static str]> {
        Some(&["hm"])
    }
    fn term_json_keys(&self) -> Option<&'static [&'static str]> {
        Self::term_json_keys_static()
    }
    fn parse_value(&self, value: &serde_json::Value) -> Result<(), serde_json::Error> {
        BigintEq::deserialize(value).map(|_| ())
    }
    fn schema(&self) -> Schema {
        schema_for!(BigintEq)
    }
}
/// `public.eql_v3_bigint_ord_ore` — ordering domain.
///
/// Operators: `=` `<>` `<` `<=` `>` `>=`. Required keys: `v` `i` `c` `ob`.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
#[ts(export, export_to = "v3/")]
#[serde(deny_unknown_fields)]
pub struct BigintOrdOre {
    pub v: SchemaVersion,
    pub i: Identifier,
    pub c: Ciphertext,
    pub ob: OreBlock256,
}
impl DomainType for BigintOrdOre {
    fn sql_domain_static() -> &'static str {
        "public.eql_v3_bigint_ord_ore"
    }
    fn sql_domain(&self) -> &'static str {
        Self::sql_domain_static()
    }
    fn term_json_keys_static() -> Option<&'static [&'static str]> {
        Some(&["ob"])
    }
    fn term_json_keys(&self) -> Option<&'static [&'static str]> {
        Self::term_json_keys_static()
    }
    fn parse_value(&self, value: &serde_json::Value) -> Result<(), serde_json::Error> {
        BigintOrdOre::deserialize(value).map(|_| ())
    }
    fn schema(&self) -> Schema {
        schema_for!(BigintOrdOre)
    }
}
/// `public.eql_v3_bigint_ord` — ordering domain.
///
/// Operators: `=` `<>` `<` `<=` `>` `>=`. Required keys: `v` `i` `c` `op`.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
#[ts(export, export_to = "v3/")]
#[serde(deny_unknown_fields)]
pub struct BigintOrd {
    pub v: SchemaVersion,
    pub i: Identifier,
    pub c: Ciphertext,
    pub op: OpeCllw,
}
impl DomainType for BigintOrd {
    fn sql_domain_static() -> &'static str {
        "public.eql_v3_bigint_ord"
    }
    fn sql_domain(&self) -> &'static str {
        Self::sql_domain_static()
    }
    fn term_json_keys_static() -> Option<&'static [&'static str]> {
        Some(&["op"])
    }
    fn term_json_keys(&self) -> Option<&'static [&'static str]> {
        Self::term_json_keys_static()
    }
    fn parse_value(&self, value: &serde_json::Value) -> Result<(), serde_json::Error> {
        BigintOrd::deserialize(value).map(|_| ())
    }
    fn schema(&self) -> Schema {
        schema_for!(BigintOrd)
    }
}
/// `public.eql_v3_bigint_ord_ope` — ordering domain.
///
/// Operators: `=` `<>` `<` `<=` `>` `>=`. Required keys: `v` `i` `c` `op`.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
#[ts(export, export_to = "v3/")]
#[serde(deny_unknown_fields)]
pub struct BigintOrdOpe {
    pub v: SchemaVersion,
    pub i: Identifier,
    pub c: Ciphertext,
    pub op: OpeCllw,
}
impl DomainType for BigintOrdOpe {
    fn sql_domain_static() -> &'static str {
        "public.eql_v3_bigint_ord_ope"
    }
    fn sql_domain(&self) -> &'static str {
        Self::sql_domain_static()
    }
    fn term_json_keys_static() -> Option<&'static [&'static str]> {
        Some(&["op"])
    }
    fn term_json_keys(&self) -> Option<&'static [&'static str]> {
        Self::term_json_keys_static()
    }
    fn parse_value(&self, value: &serde_json::Value) -> Result<(), serde_json::Error> {
        BigintOrdOpe::deserialize(value).map(|_| ())
    }
    fn schema(&self) -> Schema {
        schema_for!(BigintOrdOpe)
    }
}
/// `eql_v3.query_bigint_eq` — equality domain query operand.
///
/// Operators: `=` `<>`. Required keys: `v` `i` `hm`.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
#[ts(export, export_to = "v3/")]
#[serde(deny_unknown_fields)]
pub struct BigintEqQuery {
    pub v: SchemaVersion,
    pub i: Identifier,
    pub hm: Hmac256,
}
impl DomainType for BigintEqQuery {
    fn sql_domain_static() -> &'static str {
        "eql_v3.query_bigint_eq"
    }
    fn sql_domain(&self) -> &'static str {
        Self::sql_domain_static()
    }
    fn term_json_keys_static() -> Option<&'static [&'static str]> {
        Some(&["hm"])
    }
    fn term_json_keys(&self) -> Option<&'static [&'static str]> {
        Self::term_json_keys_static()
    }
    fn parse_value(&self, value: &serde_json::Value) -> Result<(), serde_json::Error> {
        BigintEqQuery::deserialize(value).map(|_| ())
    }
    fn schema(&self) -> Schema {
        schema_for!(BigintEqQuery)
    }
}
/// `eql_v3.query_bigint_ord_ore` — ordering domain query operand.
///
/// Operators: `=` `<>` `<` `<=` `>` `>=`. Required keys: `v` `i` `ob`.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
#[ts(export, export_to = "v3/")]
#[serde(deny_unknown_fields)]
pub struct BigintOrdOreQuery {
    pub v: SchemaVersion,
    pub i: Identifier,
    pub ob: OreBlock256,
}
impl DomainType for BigintOrdOreQuery {
    fn sql_domain_static() -> &'static str {
        "eql_v3.query_bigint_ord_ore"
    }
    fn sql_domain(&self) -> &'static str {
        Self::sql_domain_static()
    }
    fn term_json_keys_static() -> Option<&'static [&'static str]> {
        Some(&["ob"])
    }
    fn term_json_keys(&self) -> Option<&'static [&'static str]> {
        Self::term_json_keys_static()
    }
    fn parse_value(&self, value: &serde_json::Value) -> Result<(), serde_json::Error> {
        BigintOrdOreQuery::deserialize(value).map(|_| ())
    }
    fn schema(&self) -> Schema {
        schema_for!(BigintOrdOreQuery)
    }
}
/// `eql_v3.query_bigint_ord` — ordering domain query operand.
///
/// Operators: `=` `<>` `<` `<=` `>` `>=`. Required keys: `v` `i` `op`.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
#[ts(export, export_to = "v3/")]
#[serde(deny_unknown_fields)]
pub struct BigintOrdQuery {
    pub v: SchemaVersion,
    pub i: Identifier,
    pub op: OpeCllw,
}
impl DomainType for BigintOrdQuery {
    fn sql_domain_static() -> &'static str {
        "eql_v3.query_bigint_ord"
    }
    fn sql_domain(&self) -> &'static str {
        Self::sql_domain_static()
    }
    fn term_json_keys_static() -> Option<&'static [&'static str]> {
        Some(&["op"])
    }
    fn term_json_keys(&self) -> Option<&'static [&'static str]> {
        Self::term_json_keys_static()
    }
    fn parse_value(&self, value: &serde_json::Value) -> Result<(), serde_json::Error> {
        BigintOrdQuery::deserialize(value).map(|_| ())
    }
    fn schema(&self) -> Schema {
        schema_for!(BigintOrdQuery)
    }
}
/// `eql_v3.query_bigint_ord_ope` — ordering domain query operand.
///
/// Operators: `=` `<>` `<` `<=` `>` `>=`. Required keys: `v` `i` `op`.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
#[ts(export, export_to = "v3/")]
#[serde(deny_unknown_fields)]
pub struct BigintOrdOpeQuery {
    pub v: SchemaVersion,
    pub i: Identifier,
    pub op: OpeCllw,
}
impl DomainType for BigintOrdOpeQuery {
    fn sql_domain_static() -> &'static str {
        "eql_v3.query_bigint_ord_ope"
    }
    fn sql_domain(&self) -> &'static str {
        Self::sql_domain_static()
    }
    fn term_json_keys_static() -> Option<&'static [&'static str]> {
        Some(&["op"])
    }
    fn term_json_keys(&self) -> Option<&'static [&'static str]> {
        Self::term_json_keys_static()
    }
    fn parse_value(&self, value: &serde_json::Value) -> Result<(), serde_json::Error> {
        BigintOrdOpeQuery::deserialize(value).map(|_| ())
    }
    fn schema(&self) -> Schema {
        schema_for!(BigintOrdOpeQuery)
    }
}
