// @generated by eql-codegen from the eql-domains catalog — do not edit
//! The `integer` encrypted-domain family — generated from the eql-domains catalog.
use crate::v3::terms::{Ciphertext, Hmac256, OpeCllw, OreBlock256};
use crate::v3::DomainType;
use crate::{Identifier, SchemaVersion};
use schemars::{schema_for, JsonSchema, Schema};
use serde::{Deserialize, Serialize};
use ts_rs::TS;
/// `public.eql_v3_integer` — storage-only domain.
///
/// Operators: none. Required keys: `v` `i` `c`.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
#[ts(export, export_to = "v3/")]
#[serde(deny_unknown_fields)]
pub struct Integer {
    pub v: SchemaVersion,
    pub i: Identifier,
    pub c: Ciphertext,
}
impl DomainType for Integer {
    fn sql_domain_static() -> &'static str {
        "public.eql_v3_integer"
    }
    fn sql_domain(&self) -> &'static str {
        Self::sql_domain_static()
    }
    fn term_json_keys_static() -> Option<&'static [&'static str]> {
        Some(&[])
    }
    fn term_json_keys(&self) -> Option<&'static [&'static str]> {
        Self::term_json_keys_static()
    }
    fn parse_value(&self, value: &serde_json::Value) -> Result<(), serde_json::Error> {
        Integer::deserialize(value).map(|_| ())
    }
    fn schema(&self) -> Schema {
        schema_for!(Integer)
    }
}
/// `public.eql_v3_integer_eq` — equality domain.
///
/// Operators: `=` `<>`. Required keys: `v` `i` `c` `hm`.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
#[ts(export, export_to = "v3/")]
#[serde(deny_unknown_fields)]
pub struct IntegerEq {
    pub v: SchemaVersion,
    pub i: Identifier,
    pub c: Ciphertext,
    pub hm: Hmac256,
}
impl DomainType for IntegerEq {
    fn sql_domain_static() -> &'static str {
        "public.eql_v3_integer_eq"
    }
    fn sql_domain(&self) -> &'static str {
        Self::sql_domain_static()
    }
    fn term_json_keys_static() -> Option<&'static [&'static str]> {
        Some(&["hm"])
    }
    fn term_json_keys(&self) -> Option<&'static [&'static str]> {
        Self::term_json_keys_static()
    }
    fn parse_value(&self, value: &serde_json::Value) -> Result<(), serde_json::Error> {
        IntegerEq::deserialize(value).map(|_| ())
    }
    fn schema(&self) -> Schema {
        schema_for!(IntegerEq)
    }
}
/// `public.eql_v3_integer_ord_ore` — ordering domain.
///
/// Operators: `=` `<>` `<` `<=` `>` `>=`. Required keys: `v` `i` `c` `ob`.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
#[ts(export, export_to = "v3/")]
#[serde(deny_unknown_fields)]
pub struct IntegerOrdOre {
    pub v: SchemaVersion,
    pub i: Identifier,
    pub c: Ciphertext,
    pub ob: OreBlock256,
}
impl DomainType for IntegerOrdOre {
    fn sql_domain_static() -> &'static str {
        "public.eql_v3_integer_ord_ore"
    }
    fn sql_domain(&self) -> &'static str {
        Self::sql_domain_static()
    }
    fn term_json_keys_static() -> Option<&'static [&'static str]> {
        Some(&["ob"])
    }
    fn term_json_keys(&self) -> Option<&'static [&'static str]> {
        Self::term_json_keys_static()
    }
    fn parse_value(&self, value: &serde_json::Value) -> Result<(), serde_json::Error> {
        IntegerOrdOre::deserialize(value).map(|_| ())
    }
    fn schema(&self) -> Schema {
        schema_for!(IntegerOrdOre)
    }
}
/// `public.eql_v3_integer_ord` — ordering domain.
///
/// Operators: `=` `<>` `<` `<=` `>` `>=`. Required keys: `v` `i` `c` `op`.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
#[ts(export, export_to = "v3/")]
#[serde(deny_unknown_fields)]
pub struct IntegerOrd {
    pub v: SchemaVersion,
    pub i: Identifier,
    pub c: Ciphertext,
    pub op: OpeCllw,
}
impl DomainType for IntegerOrd {
    fn sql_domain_static() -> &'static str {
        "public.eql_v3_integer_ord"
    }
    fn sql_domain(&self) -> &'static str {
        Self::sql_domain_static()
    }
    fn term_json_keys_static() -> Option<&'static [&'static str]> {
        Some(&["op"])
    }
    fn term_json_keys(&self) -> Option<&'static [&'static str]> {
        Self::term_json_keys_static()
    }
    fn parse_value(&self, value: &serde_json::Value) -> Result<(), serde_json::Error> {
        IntegerOrd::deserialize(value).map(|_| ())
    }
    fn schema(&self) -> Schema {
        schema_for!(IntegerOrd)
    }
}
/// `public.eql_v3_integer_ord_ope` — ordering domain.
///
/// Operators: `=` `<>` `<` `<=` `>` `>=`. Required keys: `v` `i` `c` `op`.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
#[ts(export, export_to = "v3/")]
#[serde(deny_unknown_fields)]
pub struct IntegerOrdOpe {
    pub v: SchemaVersion,
    pub i: Identifier,
    pub c: Ciphertext,
    pub op: OpeCllw,
}
impl DomainType for IntegerOrdOpe {
    fn sql_domain_static() -> &'static str {
        "public.eql_v3_integer_ord_ope"
    }
    fn sql_domain(&self) -> &'static str {
        Self::sql_domain_static()
    }
    fn term_json_keys_static() -> Option<&'static [&'static str]> {
        Some(&["op"])
    }
    fn term_json_keys(&self) -> Option<&'static [&'static str]> {
        Self::term_json_keys_static()
    }
    fn parse_value(&self, value: &serde_json::Value) -> Result<(), serde_json::Error> {
        IntegerOrdOpe::deserialize(value).map(|_| ())
    }
    fn schema(&self) -> Schema {
        schema_for!(IntegerOrdOpe)
    }
}
/// `eql_v3.query_integer_eq` — equality domain query operand.
///
/// Operators: `=` `<>`. Required keys: `v` `i` `hm`.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
#[ts(export, export_to = "v3/")]
#[serde(deny_unknown_fields)]
pub struct IntegerEqQuery {
    pub v: SchemaVersion,
    pub i: Identifier,
    pub hm: Hmac256,
}
impl DomainType for IntegerEqQuery {
    fn sql_domain_static() -> &'static str {
        "eql_v3.query_integer_eq"
    }
    fn sql_domain(&self) -> &'static str {
        Self::sql_domain_static()
    }
    fn term_json_keys_static() -> Option<&'static [&'static str]> {
        Some(&["hm"])
    }
    fn term_json_keys(&self) -> Option<&'static [&'static str]> {
        Self::term_json_keys_static()
    }
    fn parse_value(&self, value: &serde_json::Value) -> Result<(), serde_json::Error> {
        IntegerEqQuery::deserialize(value).map(|_| ())
    }
    fn schema(&self) -> Schema {
        schema_for!(IntegerEqQuery)
    }
}
/// `eql_v3.query_integer_ord_ore` — ordering domain query operand.
///
/// Operators: `=` `<>` `<` `<=` `>` `>=`. Required keys: `v` `i` `ob`.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
#[ts(export, export_to = "v3/")]
#[serde(deny_unknown_fields)]
pub struct IntegerOrdOreQuery {
    pub v: SchemaVersion,
    pub i: Identifier,
    pub ob: OreBlock256,
}
impl DomainType for IntegerOrdOreQuery {
    fn sql_domain_static() -> &'static str {
        "eql_v3.query_integer_ord_ore"
    }
    fn sql_domain(&self) -> &'static str {
        Self::sql_domain_static()
    }
    fn term_json_keys_static() -> Option<&'static [&'static str]> {
        Some(&["ob"])
    }
    fn term_json_keys(&self) -> Option<&'static [&'static str]> {
        Self::term_json_keys_static()
    }
    fn parse_value(&self, value: &serde_json::Value) -> Result<(), serde_json::Error> {
        IntegerOrdOreQuery::deserialize(value).map(|_| ())
    }
    fn schema(&self) -> Schema {
        schema_for!(IntegerOrdOreQuery)
    }
}
/// `eql_v3.query_integer_ord` — ordering domain query operand.
///
/// Operators: `=` `<>` `<` `<=` `>` `>=`. Required keys: `v` `i` `op`.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
#[ts(export, export_to = "v3/")]
#[serde(deny_unknown_fields)]
pub struct IntegerOrdQuery {
    pub v: SchemaVersion,
    pub i: Identifier,
    pub op: OpeCllw,
}
impl DomainType for IntegerOrdQuery {
    fn sql_domain_static() -> &'static str {
        "eql_v3.query_integer_ord"
    }
    fn sql_domain(&self) -> &'static str {
        Self::sql_domain_static()
    }
    fn term_json_keys_static() -> Option<&'static [&'static str]> {
        Some(&["op"])
    }
    fn term_json_keys(&self) -> Option<&'static [&'static str]> {
        Self::term_json_keys_static()
    }
    fn parse_value(&self, value: &serde_json::Value) -> Result<(), serde_json::Error> {
        IntegerOrdQuery::deserialize(value).map(|_| ())
    }
    fn schema(&self) -> Schema {
        schema_for!(IntegerOrdQuery)
    }
}
/// `eql_v3.query_integer_ord_ope` — ordering domain query operand.
///
/// Operators: `=` `<>` `<` `<=` `>` `>=`. Required keys: `v` `i` `op`.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
#[ts(export, export_to = "v3/")]
#[serde(deny_unknown_fields)]
pub struct IntegerOrdOpeQuery {
    pub v: SchemaVersion,
    pub i: Identifier,
    pub op: OpeCllw,
}
impl DomainType for IntegerOrdOpeQuery {
    fn sql_domain_static() -> &'static str {
        "eql_v3.query_integer_ord_ope"
    }
    fn sql_domain(&self) -> &'static str {
        Self::sql_domain_static()
    }
    fn term_json_keys_static() -> Option<&'static [&'static str]> {
        Some(&["op"])
    }
    fn term_json_keys(&self) -> Option<&'static [&'static str]> {
        Self::term_json_keys_static()
    }
    fn parse_value(&self, value: &serde_json::Value) -> Result<(), serde_json::Error> {
        IntegerOrdOpeQuery::deserialize(value).map(|_| ())
    }
    fn schema(&self) -> Schema {
        schema_for!(IntegerOrdOpeQuery)
    }
}
