// @generated by eql-codegen from the eql-domains catalog — do not edit
//! The generated scalar (storage) domain(s) of the `json` encrypted-domain family — generated from the eql-domains catalog. The family's SteVec domains are hand-written in `json.rs`.
use crate::v3::terms::Ciphertext;
use crate::v3::DomainType;
use crate::{Identifier, SchemaVersion};
use schemars::{schema_for, JsonSchema, Schema};
use serde::{Deserialize, Serialize};
use ts_rs::TS;
/// `public.eql_v3_json` — storage-only domain.
///
/// Operators: none. Required keys: `v` `i` `c`.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
#[ts(export, export_to = "v3/")]
#[serde(deny_unknown_fields)]
pub struct Json {
    pub v: SchemaVersion,
    pub i: Identifier,
    pub c: Ciphertext,
}
impl DomainType for Json {
    fn sql_domain_static() -> &'static str {
        "public.eql_v3_json"
    }
    fn sql_domain(&self) -> &'static str {
        Self::sql_domain_static()
    }
    fn term_json_keys_static() -> Option<&'static [&'static str]> {
        Some(&[])
    }
    fn term_json_keys(&self) -> Option<&'static [&'static str]> {
        Self::term_json_keys_static()
    }
    fn parse_value(&self, value: &serde_json::Value) -> Result<(), serde_json::Error> {
        Json::deserialize(value).map(|_| ())
    }
    fn schema(&self) -> Schema {
        schema_for!(Json)
    }
}
