// @generated by eql-codegen from the eql-domains catalog — do not edit
//! The generated `QueryPayload` enum — every v3 QUERY-operand domain in one Rust type. Generated from the catalog; the DomainType trait, the shared newtypes, and the architectural module doc stay hand-written (domain_type.rs / terms.rs / mod.rs).
use super::domain_type::DomainType;
use serde::{Deserialize, Serialize};
/// Every v3 QUERY-operand shape in one type: one variant per term-bearing
/// scalar query twin (`eql_v3.query_<name>`, the enveloped term-only
/// operand — `{v, i, <terms>}`, no `c`) plus the SteVec containment
/// needle (`eql_v3.query_json`). Generated from the catalog, so it
/// cannot drift when the catalog grows.
///
/// Serialization is exactly the inner struct's (`#[serde(untagged)]`
/// adds no tagging), so typing a query operand never changes the wire.
/// Deliberately NO `Deserialize`: cross-token operands are byte-identical
/// on the wire, so a variant is only constructible from a KNOWN domain
/// — [`QueryPayload::parse`] or [`crate::from_v2::from_v2_query_typed`] —
/// never inferred from bytes. No ts-rs/schemars: it adds no wire shape.
#[derive(Clone, Debug, PartialEq, Serialize)]
#[serde(untagged)]
pub enum QueryPayload {
    /// The `eql_v3.query_integer_eq` query operand.
    IntegerEqQuery(super::integer::IntegerEqQuery),
    /// The `eql_v3.query_integer_ord_ore` query operand.
    IntegerOrdOreQuery(super::integer::IntegerOrdOreQuery),
    /// The `eql_v3.query_integer_ord` query operand.
    IntegerOrdQuery(super::integer::IntegerOrdQuery),
    /// The `eql_v3.query_integer_ord_ope` query operand.
    IntegerOrdOpeQuery(super::integer::IntegerOrdOpeQuery),
    /// The `eql_v3.query_smallint_eq` query operand.
    SmallintEqQuery(super::smallint::SmallintEqQuery),
    /// The `eql_v3.query_smallint_ord_ore` query operand.
    SmallintOrdOreQuery(super::smallint::SmallintOrdOreQuery),
    /// The `eql_v3.query_smallint_ord` query operand.
    SmallintOrdQuery(super::smallint::SmallintOrdQuery),
    /// The `eql_v3.query_smallint_ord_ope` query operand.
    SmallintOrdOpeQuery(super::smallint::SmallintOrdOpeQuery),
    /// The `eql_v3.query_bigint_eq` query operand.
    BigintEqQuery(super::bigint::BigintEqQuery),
    /// The `eql_v3.query_bigint_ord_ore` query operand.
    BigintOrdOreQuery(super::bigint::BigintOrdOreQuery),
    /// The `eql_v3.query_bigint_ord` query operand.
    BigintOrdQuery(super::bigint::BigintOrdQuery),
    /// The `eql_v3.query_bigint_ord_ope` query operand.
    BigintOrdOpeQuery(super::bigint::BigintOrdOpeQuery),
    /// The `eql_v3.query_date_eq` query operand.
    DateEqQuery(super::date::DateEqQuery),
    /// The `eql_v3.query_date_ord_ore` query operand.
    DateOrdOreQuery(super::date::DateOrdOreQuery),
    /// The `eql_v3.query_date_ord` query operand.
    DateOrdQuery(super::date::DateOrdQuery),
    /// The `eql_v3.query_date_ord_ope` query operand.
    DateOrdOpeQuery(super::date::DateOrdOpeQuery),
    /// The `eql_v3.query_timestamp_eq` query operand.
    TimestampEqQuery(super::timestamp::TimestampEqQuery),
    /// The `eql_v3.query_timestamp_ord_ore` query operand.
    TimestampOrdOreQuery(super::timestamp::TimestampOrdOreQuery),
    /// The `eql_v3.query_timestamp_ord` query operand.
    TimestampOrdQuery(super::timestamp::TimestampOrdQuery),
    /// The `eql_v3.query_timestamp_ord_ope` query operand.
    TimestampOrdOpeQuery(super::timestamp::TimestampOrdOpeQuery),
    /// The `eql_v3.query_numeric_eq` query operand.
    NumericEqQuery(super::numeric::NumericEqQuery),
    /// The `eql_v3.query_numeric_ord_ore` query operand.
    NumericOrdOreQuery(super::numeric::NumericOrdOreQuery),
    /// The `eql_v3.query_numeric_ord` query operand.
    NumericOrdQuery(super::numeric::NumericOrdQuery),
    /// The `eql_v3.query_numeric_ord_ope` query operand.
    NumericOrdOpeQuery(super::numeric::NumericOrdOpeQuery),
    /// The `eql_v3.query_text_eq` query operand.
    TextEqQuery(super::text::TextEqQuery),
    /// The `eql_v3.query_text_match` query operand.
    TextMatchQuery(super::text::TextMatchQuery),
    /// The `eql_v3.query_text_ord_ore` query operand.
    TextOrdOreQuery(super::text::TextOrdOreQuery),
    /// The `eql_v3.query_text_ord` query operand.
    TextOrdQuery(super::text::TextOrdQuery),
    /// The `eql_v3.query_text_ord_ope` query operand.
    TextOrdOpeQuery(super::text::TextOrdOpeQuery),
    /// The `eql_v3.query_text_search_ore` query operand.
    TextSearchOreQuery(super::text::TextSearchOreQuery),
    /// The `eql_v3.query_text_search` query operand.
    TextSearchQuery(super::text::TextSearchQuery),
    /// The `eql_v3.query_real_eq` query operand.
    RealEqQuery(super::real::RealEqQuery),
    /// The `eql_v3.query_real_ord_ore` query operand.
    RealOrdOreQuery(super::real::RealOrdOreQuery),
    /// The `eql_v3.query_real_ord` query operand.
    RealOrdQuery(super::real::RealOrdQuery),
    /// The `eql_v3.query_real_ord_ope` query operand.
    RealOrdOpeQuery(super::real::RealOrdOpeQuery),
    /// The `eql_v3.query_double_eq` query operand.
    DoubleEqQuery(super::double::DoubleEqQuery),
    /// The `eql_v3.query_double_ord_ore` query operand.
    DoubleOrdOreQuery(super::double::DoubleOrdOreQuery),
    /// The `eql_v3.query_double_ord` query operand.
    DoubleOrdQuery(super::double::DoubleOrdQuery),
    /// The `eql_v3.query_double_ord_ope` query operand.
    DoubleOrdOpeQuery(super::double::DoubleOrdOpeQuery),
    /// The `eql_v3.query_json` query operand.
    SteVec(super::json::SteVecQuery),
}
impl QueryPayload {
    /// Strictly parse `value` as `domain`'s query payload, KEEPING the
    /// parsed value — the query-side counterpart of
    /// [`super::DomainPayload::parse`]. `domain` is the unqualified name
    /// (`"query_integer_eq"`, `"query_json"`, …). `None` when `domain`
    /// is not a query-operand domain; `Some(Err)` when the strict parse
    /// fails (`deny_unknown_fields` rejects a stray `c`).
    pub fn parse(
        domain: &str,
        value: &serde_json::Value,
    ) -> Option<Result<Self, serde_json::Error>> {
        match domain {
            "query_integer_eq" => {
                Some(super::integer::IntegerEqQuery::deserialize(value).map(Self::IntegerEqQuery))
            }
            "query_integer_ord_ore" => Some(
                super::integer::IntegerOrdOreQuery::deserialize(value)
                    .map(Self::IntegerOrdOreQuery),
            ),
            "query_integer_ord" => {
                Some(super::integer::IntegerOrdQuery::deserialize(value).map(Self::IntegerOrdQuery))
            }
            "query_integer_ord_ope" => Some(
                super::integer::IntegerOrdOpeQuery::deserialize(value)
                    .map(Self::IntegerOrdOpeQuery),
            ),
            "query_smallint_eq" => Some(
                super::smallint::SmallintEqQuery::deserialize(value).map(Self::SmallintEqQuery),
            ),
            "query_smallint_ord_ore" => Some(
                super::smallint::SmallintOrdOreQuery::deserialize(value)
                    .map(Self::SmallintOrdOreQuery),
            ),
            "query_smallint_ord" => Some(
                super::smallint::SmallintOrdQuery::deserialize(value).map(Self::SmallintOrdQuery),
            ),
            "query_smallint_ord_ope" => Some(
                super::smallint::SmallintOrdOpeQuery::deserialize(value)
                    .map(Self::SmallintOrdOpeQuery),
            ),
            "query_bigint_eq" => {
                Some(super::bigint::BigintEqQuery::deserialize(value).map(Self::BigintEqQuery))
            }
            "query_bigint_ord_ore" => Some(
                super::bigint::BigintOrdOreQuery::deserialize(value).map(Self::BigintOrdOreQuery),
            ),
            "query_bigint_ord" => {
                Some(super::bigint::BigintOrdQuery::deserialize(value).map(Self::BigintOrdQuery))
            }
            "query_bigint_ord_ope" => Some(
                super::bigint::BigintOrdOpeQuery::deserialize(value).map(Self::BigintOrdOpeQuery),
            ),
            "query_date_eq" => {
                Some(super::date::DateEqQuery::deserialize(value).map(Self::DateEqQuery))
            }
            "query_date_ord_ore" => {
                Some(super::date::DateOrdOreQuery::deserialize(value).map(Self::DateOrdOreQuery))
            }
            "query_date_ord" => {
                Some(super::date::DateOrdQuery::deserialize(value).map(Self::DateOrdQuery))
            }
            "query_date_ord_ope" => {
                Some(super::date::DateOrdOpeQuery::deserialize(value).map(Self::DateOrdOpeQuery))
            }
            "query_timestamp_eq" => Some(
                super::timestamp::TimestampEqQuery::deserialize(value).map(Self::TimestampEqQuery),
            ),
            "query_timestamp_ord_ore" => Some(
                super::timestamp::TimestampOrdOreQuery::deserialize(value)
                    .map(Self::TimestampOrdOreQuery),
            ),
            "query_timestamp_ord" => Some(
                super::timestamp::TimestampOrdQuery::deserialize(value)
                    .map(Self::TimestampOrdQuery),
            ),
            "query_timestamp_ord_ope" => Some(
                super::timestamp::TimestampOrdOpeQuery::deserialize(value)
                    .map(Self::TimestampOrdOpeQuery),
            ),
            "query_numeric_eq" => {
                Some(super::numeric::NumericEqQuery::deserialize(value).map(Self::NumericEqQuery))
            }
            "query_numeric_ord_ore" => Some(
                super::numeric::NumericOrdOreQuery::deserialize(value)
                    .map(Self::NumericOrdOreQuery),
            ),
            "query_numeric_ord" => {
                Some(super::numeric::NumericOrdQuery::deserialize(value).map(Self::NumericOrdQuery))
            }
            "query_numeric_ord_ope" => Some(
                super::numeric::NumericOrdOpeQuery::deserialize(value)
                    .map(Self::NumericOrdOpeQuery),
            ),
            "query_text_eq" => {
                Some(super::text::TextEqQuery::deserialize(value).map(Self::TextEqQuery))
            }
            "query_text_match" => {
                Some(super::text::TextMatchQuery::deserialize(value).map(Self::TextMatchQuery))
            }
            "query_text_ord_ore" => {
                Some(super::text::TextOrdOreQuery::deserialize(value).map(Self::TextOrdOreQuery))
            }
            "query_text_ord" => {
                Some(super::text::TextOrdQuery::deserialize(value).map(Self::TextOrdQuery))
            }
            "query_text_ord_ope" => {
                Some(super::text::TextOrdOpeQuery::deserialize(value).map(Self::TextOrdOpeQuery))
            }
            "query_text_search_ore" => Some(
                super::text::TextSearchOreQuery::deserialize(value).map(Self::TextSearchOreQuery),
            ),
            "query_text_search" => {
                Some(super::text::TextSearchQuery::deserialize(value).map(Self::TextSearchQuery))
            }
            "query_real_eq" => {
                Some(super::real::RealEqQuery::deserialize(value).map(Self::RealEqQuery))
            }
            "query_real_ord_ore" => {
                Some(super::real::RealOrdOreQuery::deserialize(value).map(Self::RealOrdOreQuery))
            }
            "query_real_ord" => {
                Some(super::real::RealOrdQuery::deserialize(value).map(Self::RealOrdQuery))
            }
            "query_real_ord_ope" => {
                Some(super::real::RealOrdOpeQuery::deserialize(value).map(Self::RealOrdOpeQuery))
            }
            "query_double_eq" => {
                Some(super::double::DoubleEqQuery::deserialize(value).map(Self::DoubleEqQuery))
            }
            "query_double_ord_ore" => Some(
                super::double::DoubleOrdOreQuery::deserialize(value).map(Self::DoubleOrdOreQuery),
            ),
            "query_double_ord" => {
                Some(super::double::DoubleOrdQuery::deserialize(value).map(Self::DoubleOrdQuery))
            }
            "query_double_ord_ope" => Some(
                super::double::DoubleOrdOpeQuery::deserialize(value).map(Self::DoubleOrdOpeQuery),
            ),
            "query_json" => Some(super::json::SteVecQuery::deserialize(value).map(Self::SteVec)),
            _ => None,
        }
    }
    /// The inner payload as a [`DomainType`] trait object.
    pub fn as_domain_type(&self) -> &dyn DomainType {
        match self {
            Self::IntegerEqQuery(payload) => payload,
            Self::IntegerOrdOreQuery(payload) => payload,
            Self::IntegerOrdQuery(payload) => payload,
            Self::IntegerOrdOpeQuery(payload) => payload,
            Self::SmallintEqQuery(payload) => payload,
            Self::SmallintOrdOreQuery(payload) => payload,
            Self::SmallintOrdQuery(payload) => payload,
            Self::SmallintOrdOpeQuery(payload) => payload,
            Self::BigintEqQuery(payload) => payload,
            Self::BigintOrdOreQuery(payload) => payload,
            Self::BigintOrdQuery(payload) => payload,
            Self::BigintOrdOpeQuery(payload) => payload,
            Self::DateEqQuery(payload) => payload,
            Self::DateOrdOreQuery(payload) => payload,
            Self::DateOrdQuery(payload) => payload,
            Self::DateOrdOpeQuery(payload) => payload,
            Self::TimestampEqQuery(payload) => payload,
            Self::TimestampOrdOreQuery(payload) => payload,
            Self::TimestampOrdQuery(payload) => payload,
            Self::TimestampOrdOpeQuery(payload) => payload,
            Self::NumericEqQuery(payload) => payload,
            Self::NumericOrdOreQuery(payload) => payload,
            Self::NumericOrdQuery(payload) => payload,
            Self::NumericOrdOpeQuery(payload) => payload,
            Self::TextEqQuery(payload) => payload,
            Self::TextMatchQuery(payload) => payload,
            Self::TextOrdOreQuery(payload) => payload,
            Self::TextOrdQuery(payload) => payload,
            Self::TextOrdOpeQuery(payload) => payload,
            Self::TextSearchOreQuery(payload) => payload,
            Self::TextSearchQuery(payload) => payload,
            Self::RealEqQuery(payload) => payload,
            Self::RealOrdOreQuery(payload) => payload,
            Self::RealOrdQuery(payload) => payload,
            Self::RealOrdOpeQuery(payload) => payload,
            Self::DoubleEqQuery(payload) => payload,
            Self::DoubleOrdOreQuery(payload) => payload,
            Self::DoubleOrdQuery(payload) => payload,
            Self::DoubleOrdOpeQuery(payload) => payload,
            Self::SteVec(payload) => payload,
        }
    }
    /// Fully-qualified SQL domain name, e.g. `"eql_v3.query_integer_eq"`.
    pub fn sql_domain(&self) -> &'static str {
        self.as_domain_type().sql_domain()
    }
    /// Unqualified SQL domain name, e.g. `"query_integer_eq"` — the name
    /// [`QueryPayload::parse`] accepts.
    pub fn domain(&self) -> &'static str {
        self.as_domain_type().domain()
    }
}
