// @generated by eql-codegen from the eql-domains catalog — do not edit
//! The `timestamp` encrypted-domain family — generated from the eql-domains catalog.
use crate::v3::terms::{Ciphertext, Hmac256, OpeCllw, OreBlock256};
use crate::v3::DomainType;
use crate::{Identifier, SchemaVersion};
use schemars::{schema_for, JsonSchema, Schema};
use serde::{Deserialize, Serialize};
use ts_rs::TS;
/// `public.eql_v3_timestamp` — storage-only domain.
///
/// Operators: none. Required keys: `v` `i` `c`.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
#[ts(export, export_to = "v3/")]
#[serde(deny_unknown_fields)]
pub struct Timestamp {
    pub v: SchemaVersion,
    pub i: Identifier,
    pub c: Ciphertext,
}
impl DomainType for Timestamp {
    fn sql_domain_static() -> &'static str {
        "public.eql_v3_timestamp"
    }
    fn sql_domain(&self) -> &'static str {
        Self::sql_domain_static()
    }
    fn term_json_keys_static() -> Option<&'static [&'static str]> {
        Some(&[])
    }
    fn term_json_keys(&self) -> Option<&'static [&'static str]> {
        Self::term_json_keys_static()
    }
    fn parse_value(&self, value: &serde_json::Value) -> Result<(), serde_json::Error> {
        Timestamp::deserialize(value).map(|_| ())
    }
    fn schema(&self) -> Schema {
        schema_for!(Timestamp)
    }
}
/// `public.eql_v3_timestamp_eq` — equality domain.
///
/// Operators: `=` `<>`. Required keys: `v` `i` `c` `hm`.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
#[ts(export, export_to = "v3/")]
#[serde(deny_unknown_fields)]
pub struct TimestampEq {
    pub v: SchemaVersion,
    pub i: Identifier,
    pub c: Ciphertext,
    pub hm: Hmac256,
}
impl DomainType for TimestampEq {
    fn sql_domain_static() -> &'static str {
        "public.eql_v3_timestamp_eq"
    }
    fn sql_domain(&self) -> &'static str {
        Self::sql_domain_static()
    }
    fn term_json_keys_static() -> Option<&'static [&'static str]> {
        Some(&["hm"])
    }
    fn term_json_keys(&self) -> Option<&'static [&'static str]> {
        Self::term_json_keys_static()
    }
    fn parse_value(&self, value: &serde_json::Value) -> Result<(), serde_json::Error> {
        TimestampEq::deserialize(value).map(|_| ())
    }
    fn schema(&self) -> Schema {
        schema_for!(TimestampEq)
    }
}
/// `public.eql_v3_timestamp_ord_ore` — ordering domain.
///
/// Operators: `=` `<>` `<` `<=` `>` `>=`. Required keys: `v` `i` `c` `ob`.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
#[ts(export, export_to = "v3/")]
#[serde(deny_unknown_fields)]
pub struct TimestampOrdOre {
    pub v: SchemaVersion,
    pub i: Identifier,
    pub c: Ciphertext,
    pub ob: OreBlock256,
}
impl DomainType for TimestampOrdOre {
    fn sql_domain_static() -> &'static str {
        "public.eql_v3_timestamp_ord_ore"
    }
    fn sql_domain(&self) -> &'static str {
        Self::sql_domain_static()
    }
    fn term_json_keys_static() -> Option<&'static [&'static str]> {
        Some(&["ob"])
    }
    fn term_json_keys(&self) -> Option<&'static [&'static str]> {
        Self::term_json_keys_static()
    }
    fn parse_value(&self, value: &serde_json::Value) -> Result<(), serde_json::Error> {
        TimestampOrdOre::deserialize(value).map(|_| ())
    }
    fn schema(&self) -> Schema {
        schema_for!(TimestampOrdOre)
    }
}
/// `public.eql_v3_timestamp_ord` — ordering domain.
///
/// Operators: `=` `<>` `<` `<=` `>` `>=`. Required keys: `v` `i` `c` `op`.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
#[ts(export, export_to = "v3/")]
#[serde(deny_unknown_fields)]
pub struct TimestampOrd {
    pub v: SchemaVersion,
    pub i: Identifier,
    pub c: Ciphertext,
    pub op: OpeCllw,
}
impl DomainType for TimestampOrd {
    fn sql_domain_static() -> &'static str {
        "public.eql_v3_timestamp_ord"
    }
    fn sql_domain(&self) -> &'static str {
        Self::sql_domain_static()
    }
    fn term_json_keys_static() -> Option<&'static [&'static str]> {
        Some(&["op"])
    }
    fn term_json_keys(&self) -> Option<&'static [&'static str]> {
        Self::term_json_keys_static()
    }
    fn parse_value(&self, value: &serde_json::Value) -> Result<(), serde_json::Error> {
        TimestampOrd::deserialize(value).map(|_| ())
    }
    fn schema(&self) -> Schema {
        schema_for!(TimestampOrd)
    }
}
/// `public.eql_v3_timestamp_ord_ope` — ordering domain.
///
/// Operators: `=` `<>` `<` `<=` `>` `>=`. Required keys: `v` `i` `c` `op`.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
#[ts(export, export_to = "v3/")]
#[serde(deny_unknown_fields)]
pub struct TimestampOrdOpe {
    pub v: SchemaVersion,
    pub i: Identifier,
    pub c: Ciphertext,
    pub op: OpeCllw,
}
impl DomainType for TimestampOrdOpe {
    fn sql_domain_static() -> &'static str {
        "public.eql_v3_timestamp_ord_ope"
    }
    fn sql_domain(&self) -> &'static str {
        Self::sql_domain_static()
    }
    fn term_json_keys_static() -> Option<&'static [&'static str]> {
        Some(&["op"])
    }
    fn term_json_keys(&self) -> Option<&'static [&'static str]> {
        Self::term_json_keys_static()
    }
    fn parse_value(&self, value: &serde_json::Value) -> Result<(), serde_json::Error> {
        TimestampOrdOpe::deserialize(value).map(|_| ())
    }
    fn schema(&self) -> Schema {
        schema_for!(TimestampOrdOpe)
    }
}
/// `eql_v3.query_timestamp_eq` — equality domain query operand.
///
/// Operators: `=` `<>`. Required keys: `v` `i` `hm`.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
#[ts(export, export_to = "v3/")]
#[serde(deny_unknown_fields)]
pub struct TimestampEqQuery {
    pub v: SchemaVersion,
    pub i: Identifier,
    pub hm: Hmac256,
}
impl DomainType for TimestampEqQuery {
    fn sql_domain_static() -> &'static str {
        "eql_v3.query_timestamp_eq"
    }
    fn sql_domain(&self) -> &'static str {
        Self::sql_domain_static()
    }
    fn term_json_keys_static() -> Option<&'static [&'static str]> {
        Some(&["hm"])
    }
    fn term_json_keys(&self) -> Option<&'static [&'static str]> {
        Self::term_json_keys_static()
    }
    fn parse_value(&self, value: &serde_json::Value) -> Result<(), serde_json::Error> {
        TimestampEqQuery::deserialize(value).map(|_| ())
    }
    fn schema(&self) -> Schema {
        schema_for!(TimestampEqQuery)
    }
}
/// `eql_v3.query_timestamp_ord_ore` — ordering domain query operand.
///
/// Operators: `=` `<>` `<` `<=` `>` `>=`. Required keys: `v` `i` `ob`.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
#[ts(export, export_to = "v3/")]
#[serde(deny_unknown_fields)]
pub struct TimestampOrdOreQuery {
    pub v: SchemaVersion,
    pub i: Identifier,
    pub ob: OreBlock256,
}
impl DomainType for TimestampOrdOreQuery {
    fn sql_domain_static() -> &'static str {
        "eql_v3.query_timestamp_ord_ore"
    }
    fn sql_domain(&self) -> &'static str {
        Self::sql_domain_static()
    }
    fn term_json_keys_static() -> Option<&'static [&'static str]> {
        Some(&["ob"])
    }
    fn term_json_keys(&self) -> Option<&'static [&'static str]> {
        Self::term_json_keys_static()
    }
    fn parse_value(&self, value: &serde_json::Value) -> Result<(), serde_json::Error> {
        TimestampOrdOreQuery::deserialize(value).map(|_| ())
    }
    fn schema(&self) -> Schema {
        schema_for!(TimestampOrdOreQuery)
    }
}
/// `eql_v3.query_timestamp_ord` — ordering domain query operand.
///
/// Operators: `=` `<>` `<` `<=` `>` `>=`. Required keys: `v` `i` `op`.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
#[ts(export, export_to = "v3/")]
#[serde(deny_unknown_fields)]
pub struct TimestampOrdQuery {
    pub v: SchemaVersion,
    pub i: Identifier,
    pub op: OpeCllw,
}
impl DomainType for TimestampOrdQuery {
    fn sql_domain_static() -> &'static str {
        "eql_v3.query_timestamp_ord"
    }
    fn sql_domain(&self) -> &'static str {
        Self::sql_domain_static()
    }
    fn term_json_keys_static() -> Option<&'static [&'static str]> {
        Some(&["op"])
    }
    fn term_json_keys(&self) -> Option<&'static [&'static str]> {
        Self::term_json_keys_static()
    }
    fn parse_value(&self, value: &serde_json::Value) -> Result<(), serde_json::Error> {
        TimestampOrdQuery::deserialize(value).map(|_| ())
    }
    fn schema(&self) -> Schema {
        schema_for!(TimestampOrdQuery)
    }
}
/// `eql_v3.query_timestamp_ord_ope` — ordering domain query operand.
///
/// Operators: `=` `<>` `<` `<=` `>` `>=`. Required keys: `v` `i` `op`.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
#[ts(export, export_to = "v3/")]
#[serde(deny_unknown_fields)]
pub struct TimestampOrdOpeQuery {
    pub v: SchemaVersion,
    pub i: Identifier,
    pub op: OpeCllw,
}
impl DomainType for TimestampOrdOpeQuery {
    fn sql_domain_static() -> &'static str {
        "eql_v3.query_timestamp_ord_ope"
    }
    fn sql_domain(&self) -> &'static str {
        Self::sql_domain_static()
    }
    fn term_json_keys_static() -> Option<&'static [&'static str]> {
        Some(&["op"])
    }
    fn term_json_keys(&self) -> Option<&'static [&'static str]> {
        Self::term_json_keys_static()
    }
    fn parse_value(&self, value: &serde_json::Value) -> Result<(), serde_json::Error> {
        TimestampOrdOpeQuery::deserialize(value).map(|_| ())
    }
    fn schema(&self) -> Schema {
        schema_for!(TimestampOrdOpeQuery)
    }
}
