// Code generated by stashgen. DO NOT EDIT.

package testpolicy

import (
	"context"
	"log/slog"

	"github.com/cipherstash/stack/languages/golang/encrypt"
	"github.com/cipherstash/stack/languages/golang/encrypt/gensupport"
	"github.com/cipherstash/stack/languages/golang/encrypt/internal/testmember"
)

// Stops compiling when the library does not accept this version of generated file.
const _ = gensupport.GeneratedVersion1

// testmember.Member prints its sealed fields in the clear, and stashgen cannot
// add print methods to a type from another package.

type EncryptedMember struct {
	ID    int64
	Age   EncryptedMemberAge
	Email EncryptedMemberEmail
	Notes EncryptedMemberNotes
}

type EncryptedMemberAge struct {
	Ciphertext encrypt.Ciphertext
	Equality   encrypt.EqualityTerm
	Ore        encrypt.OreTerm
}

type EncryptedMemberEmail struct {
	Ciphertext encrypt.Ciphertext
	Equality   encrypt.EqualityTerm
	Match      encrypt.MatchTerm
}

type EncryptedMemberNotes struct {
	Ciphertext encrypt.Ciphertext
}

func (e EncryptedMember) String() string {
	return gensupport.Redacted("EncryptedMember", map[string]any{"ID": e.ID}, "Age", "Email", "Notes")
}

func (e EncryptedMember) LogValue() slog.Value {
	return gensupport.RedactedLog(map[string]any{"ID": e.ID}, "Age", "Email", "Notes")
}

// Stops compiling when testmember.Member gains, loses, reorders or retypes a field.
var _ = memberShape(testmember.Member{})

type memberShape struct {
	ID    int64
	Age   uint32
	Email string
	Notes string
}

var declaration = gensupport.Declare("users").
	Passthrough("id").
	EncryptIndex("age", gensupport.Uint32, encrypt.Equality, encrypt.Ore).
	EncryptIndex("email", gensupport.String, encrypt.Equality, encrypt.Match()).
	Encrypt("notes", gensupport.String)

var codec = gensupport.New(gensupport.Generated[testmember.Member, EncryptedMember]{
	TypeName:        "testmember.Member",
	Declaration:     declaration,
	PrintsPlaintext: true,
	Source: func(v testmember.Member) gensupport.Values {
		return gensupport.Values{
			"id":    v.ID,
			"age":   v.Age,
			"email": v.Email,
			"notes": v.Notes,
		}
	},
	Seal: func(rec gensupport.Record) (EncryptedMember, error) {
		var e EncryptedMember
		var err error
		if e.ID, err = gensupport.Passthrough[int64](rec, "id"); err != nil {
			return EncryptedMember{}, err
		}
		e.Age = EncryptedMemberAge{
			Ciphertext: rec["age"].Ciphertext,
			Equality:   rec["age"].Equality,
			Ore:        rec["age"].Ore,
		}
		e.Email = EncryptedMemberEmail{
			Ciphertext: rec["email"].Ciphertext,
			Equality:   rec["email"].Equality,
			Match:      rec["email"].Match,
		}
		e.Notes = EncryptedMemberNotes{Ciphertext: rec["notes"].Ciphertext}
		return e, nil
	},
	Open: func(e EncryptedMember) gensupport.Record {
		return gensupport.Record{
			"id":    {Value: e.ID},
			"age":   {Ciphertext: e.Age.Ciphertext, Equality: e.Age.Equality, Ore: e.Age.Ore},
			"email": {Ciphertext: e.Email.Ciphertext, Equality: e.Email.Equality, Match: e.Email.Match},
			"notes": {Ciphertext: e.Notes.Ciphertext},
		}
	},
	Value: func(e EncryptedMember, vals gensupport.Values) (testmember.Member, error) {
		var v testmember.Member
		var err error
		if v.ID, err = gensupport.Get[int64](vals, "id"); err != nil {
			return testmember.Member{}, err
		}
		if v.Age, err = gensupport.Get[uint32](vals, "age"); err != nil {
			return testmember.Member{}, err
		}
		if v.Email, err = gensupport.Get[string](vals, "email"); err != nil {
			return testmember.Member{}, err
		}
		if v.Notes, err = gensupport.Get[string](vals, "notes"); err != nil {
			return testmember.Member{}, err
		}
		return v, nil
	},
})

// Encrypt seals each testmember.Member, with one ZeroKMS request for each 500
// sealed values, plus one the first time a keyset is used. The result has one
// element for each input, in the same order.
func Encrypt(ctx context.Context, cipher *encrypt.Cipher, testpolicy []testmember.Member) ([]EncryptedMember, error) {
	return codec.Encrypt(ctx, cipher, testpolicy)
}

// Decrypt opens each EncryptedMember, with one ZeroKMS request for each 500
// sealed values, plus one the first time a keyset is used.
func Decrypt(ctx context.Context, d encrypt.Decrypter, encrypted []EncryptedMember) ([]testmember.Member, error) {
	return codec.Decrypt(ctx, d, encrypted)
}

var Fields = struct {
	Age   AgeField
	Email EmailField
	Notes NotesField
}{
	Age:   AgeField{gensupport.NewField[uint32](declaration, "age")},
	Email: EmailField{gensupport.NewField[string](declaration, "email")},
	Notes: NotesField{gensupport.NewField[string](declaration, "notes")},
}

type AgeField struct {
	field gensupport.Field[uint32]
}

func (f AgeField) Encrypt(ctx context.Context, c *encrypt.Cipher, v uint32) (EncryptedMemberAge, error) {
	out, err := f.field.Encrypt(ctx, c, v)
	if err != nil {
		return EncryptedMemberAge{}, err
	}
	return EncryptedMemberAge{Ciphertext: out.Ciphertext, Equality: out.Equality, Ore: out.Ore}, nil
}

func (f AgeField) Equality(ctx context.Context, c *encrypt.Cipher, v uint32) (encrypt.EqualityTerm, error) {
	return f.field.Equality(ctx, c, v)
}

func (f AgeField) Ore(ctx context.Context, c *encrypt.Cipher, v uint32) (encrypt.OreTerm, error) {
	return f.field.Ore(ctx, c, v)
}

type EmailField struct {
	field gensupport.Field[string]
}

func (f EmailField) Encrypt(ctx context.Context, c *encrypt.Cipher, v string) (EncryptedMemberEmail, error) {
	out, err := f.field.Encrypt(ctx, c, v)
	if err != nil {
		return EncryptedMemberEmail{}, err
	}
	return EncryptedMemberEmail{Ciphertext: out.Ciphertext, Equality: out.Equality, Match: out.Match}, nil
}

func (f EmailField) Equality(ctx context.Context, c *encrypt.Cipher, v string) (encrypt.EqualityTerm, error) {
	return f.field.Equality(ctx, c, v)
}

func (f EmailField) Match(ctx context.Context, c *encrypt.Cipher, v string) (encrypt.MatchTerm, error) {
	return f.field.Match(ctx, c, v)
}

type NotesField struct {
	field gensupport.Field[string]
}

func (f NotesField) Encrypt(ctx context.Context, c *encrypt.Cipher, v string) (EncryptedMemberNotes, error) {
	out, err := f.field.Encrypt(ctx, c, v)
	return EncryptedMemberNotes{Ciphertext: out.Ciphertext}, err
}
