// Code generated by stashgen. DO NOT EDIT.

package testusers

import (
	"context"
	"database/sql"
	"log/slog"
	"time"

	"github.com/cipherstash/stack/languages/golang/encrypt"
	"github.com/cipherstash/stack/languages/golang/encrypt/gensupport"
)

// Stops compiling when the library does not accept this version of generated file.
const _ = gensupport.GeneratedVersion1

// Account prints its sealed fields in the clear: it has no String or LogValue
// method. Write them, or run stashgen with -redact.

type EncryptedAccount struct {
	ID        uint
	CreatedAt time.Time
	DeletedAt sql.NullTime
	Email     EncryptedAccountEmail
}

type EncryptedAccountEmail struct {
	Ciphertext encrypt.Ciphertext
	Equality   encrypt.EqualityTerm
}

func (e EncryptedAccount) String() string {
	return gensupport.Redacted("EncryptedAccount", map[string]any{"ID": e.ID, "CreatedAt": e.CreatedAt, "DeletedAt": e.DeletedAt}, "Email")
}

func (e EncryptedAccount) LogValue() slog.Value {
	return gensupport.RedactedLog(map[string]any{"ID": e.ID, "CreatedAt": e.CreatedAt, "DeletedAt": e.DeletedAt}, "Email")
}

// Stops compiling when Account gains, loses, reorders or retypes a field.
var _ = accountShape(Account{})

type accountShape struct {
	_         struct{}
	ID        uint
	CreatedAt time.Time
	DeletedAt sql.NullTime
	Email     string
}

var accountDeclaration = gensupport.Declare("accounts").
	Passthrough("id").
	Passthrough("created_at").
	Passthrough("deleted_at").
	EncryptIndex("email", gensupport.String, encrypt.Equality)

var accountCodec = gensupport.New(gensupport.Generated[Account, EncryptedAccount]{
	TypeName:        "Account",
	Declaration:     accountDeclaration,
	PrintsPlaintext: true,
	Source: func(v Account) gensupport.Values {
		return gensupport.Values{
			"id":         v.ID,
			"created_at": v.CreatedAt,
			"deleted_at": v.DeletedAt,
			"email":      v.Email,
		}
	},
	Seal: func(rec gensupport.Record) (EncryptedAccount, error) {
		var e EncryptedAccount
		var err error
		if e.ID, err = gensupport.Passthrough[uint](rec, "id"); err != nil {
			return EncryptedAccount{}, err
		}
		if e.CreatedAt, err = gensupport.Passthrough[time.Time](rec, "created_at"); err != nil {
			return EncryptedAccount{}, err
		}
		if e.DeletedAt, err = gensupport.Passthrough[sql.NullTime](rec, "deleted_at"); err != nil {
			return EncryptedAccount{}, err
		}
		e.Email = EncryptedAccountEmail{
			Ciphertext: rec["email"].Ciphertext,
			Equality:   rec["email"].Equality,
		}
		return e, nil
	},
	Open: func(e EncryptedAccount) gensupport.Record {
		return gensupport.Record{
			"id":         {Value: e.ID},
			"created_at": {Value: e.CreatedAt},
			"deleted_at": {Value: e.DeletedAt},
			"email":      {Ciphertext: e.Email.Ciphertext, Equality: e.Email.Equality},
		}
	},
	Value: func(e EncryptedAccount, vals gensupport.Values) (Account, error) {
		var v Account
		var err error
		if v.ID, err = gensupport.Get[uint](vals, "id"); err != nil {
			return Account{}, err
		}
		if v.CreatedAt, err = gensupport.Get[time.Time](vals, "created_at"); err != nil {
			return Account{}, err
		}
		if v.DeletedAt, err = gensupport.Get[sql.NullTime](vals, "deleted_at"); err != nil {
			return Account{}, err
		}
		if v.Email, err = gensupport.Get[string](vals, "email"); err != nil {
			return Account{}, err
		}
		return v, nil
	},
})

// EncryptAccount seals each Account in one ZeroKMS request. The result has one
// element for each input, in the same order.
func EncryptAccount(ctx context.Context, cipher *encrypt.Cipher, values []Account) ([]EncryptedAccount, error) {
	return accountCodec.Encrypt(ctx, cipher, values)
}

// DecryptAccount opens each EncryptedAccount in one ZeroKMS request.
func DecryptAccount(ctx context.Context, d encrypt.Decrypter, encrypted []EncryptedAccount) ([]Account, error) {
	return accountCodec.Decrypt(ctx, d, encrypted)
}

var AccountFields = struct {
	Email AccountEmailField
}{
	Email: AccountEmailField{gensupport.NewField[string](accountDeclaration, "email")},
}

type AccountEmailField struct {
	field gensupport.Field[string]
}

func (f AccountEmailField) Encrypt(ctx context.Context, c *encrypt.Cipher, v string) (EncryptedAccountEmail, error) {
	out, err := f.field.Encrypt(ctx, c, v)
	if err != nil {
		return EncryptedAccountEmail{}, err
	}
	return EncryptedAccountEmail{Ciphertext: out.Ciphertext, Equality: out.Equality}, nil
}

func (f AccountEmailField) Equality(ctx context.Context, c *encrypt.Cipher, v string) (encrypt.EqualityTerm, error) {
	return f.field.Equality(ctx, c, v)
}
