// Code generated by stashgen. DO NOT EDIT.

package testusers

import (
	"context"
	"database/sql"
	"log/slog"
	"time"

	"github.com/cipherstash/stack/languages/golang/encrypt"
	"github.com/cipherstash/stack/languages/golang/encrypt/gensupport"
)

// Stops compiling when the library does not accept this version of generated file.
const _ = gensupport.GeneratedVersion1

// Everything prints its sealed fields in the clear: it has no String or
// LogValue method. Write them, or run stashgen with -redact.

type EncryptedEverything struct {
	Sealed encrypt.Ciphertext
}

func (e EncryptedEverything) String() string {
	return gensupport.Redacted("EncryptedEverything", nil, "Sealed")
}

func (e EncryptedEverything) LogValue() slog.Value {
	return gensupport.RedactedLog(nil, "Sealed")
}

// Stops compiling when Everything gains, loses, reorders or retypes a field.
var _ = everythingShape(Everything{})

type everythingShape struct {
	_      struct{}
	S      string
	E      Email
	Bo     bool
	I8     int8
	I      int
	U64    uint64
	F32    float32
	F64    float64
	By     []byte
	Bl     Blob
	Sc     Score
	Tags   []string
	Ints   []int
	F32s   []float32
	St     Status
	D      time.Duration
	Emails []Email
	Counts map[string]int
	Labels map[string]string
	ByKey  map[int]string
	In     Inner
	Ins    []Inner
	P      *string
	PI     *Inner
	T      time.Time
	N      sql.NullTime
	Nested [][]byte
	Arr    [2]uint8
}

// The opaque value as it crosses the binding: one JSON document of the
// struct's fields, by their declared names.
type everythingOpaque struct {
	S      string            `json:"s"`
	E      Email             `json:"e"`
	Bo     bool              `json:"bo"`
	I8     int8              `json:"i8"`
	I      int               `json:"i"`
	U64    uint64            `json:"u64"`
	F32    float32           `json:"f32"`
	F64    float64           `json:"f64"`
	By     []byte            `json:"by"`
	Bl     Blob              `json:"bl"`
	Sc     Score             `json:"sc"`
	Tags   []string          `json:"tags"`
	Ints   []int             `json:"ints"`
	F32s   []float32         `json:"f32s"`
	St     Status            `json:"st"`
	D      time.Duration     `json:"d"`
	Emails []Email           `json:"emails"`
	Counts map[string]int    `json:"counts"`
	Labels map[string]string `json:"labels"`
	ByKey  map[int]string    `json:"by_key"`
	In     Inner             `json:"in"`
	Ins    []Inner           `json:"ins"`
	P      *string           `json:"p"`
	PI     *Inner            `json:"pi"`
	T      time.Time         `json:"t"`
	N      sql.NullTime      `json:"n"`
	Nested [][]byte          `json:"nested"`
	Arr    [2]uint8          `json:"arr"`
}

var everythingDeclaration = gensupport.DeclareOpaque("everything")

var everythingCodec = gensupport.New(gensupport.Generated[Everything, EncryptedEverything]{
	TypeName:        "Everything",
	Declaration:     everythingDeclaration,
	PrintsPlaintext: true,
	Source: func(v Everything) gensupport.Values {
		return gensupport.Values{gensupport.OpaqueField: everythingOpaque{
			S:      v.S,
			E:      v.E,
			Bo:     v.Bo,
			I8:     v.I8,
			I:      v.I,
			U64:    v.U64,
			F32:    v.F32,
			F64:    v.F64,
			By:     v.By,
			Bl:     v.Bl,
			Sc:     v.Sc,
			Tags:   v.Tags,
			Ints:   v.Ints,
			F32s:   v.F32s,
			St:     v.St,
			D:      v.D,
			Emails: v.Emails,
			Counts: v.Counts,
			Labels: v.Labels,
			ByKey:  v.ByKey,
			In:     v.In,
			Ins:    v.Ins,
			P:      v.P,
			PI:     v.PI,
			T:      v.T,
			N:      v.N,
			Nested: v.Nested,
			Arr:    v.Arr,
		}}
	},
	Seal: func(rec gensupport.Record) (EncryptedEverything, error) {
		return EncryptedEverything{Sealed: rec[gensupport.OpaqueField].Ciphertext}, nil
	},
	Open: func(e EncryptedEverything) gensupport.Record {
		return gensupport.Record{gensupport.OpaqueField: {Ciphertext: e.Sealed}}
	},
	Value: func(e EncryptedEverything, vals gensupport.Values) (Everything, error) {
		var o everythingOpaque
		if err := gensupport.Opaque(vals, &o); err != nil {
			return Everything{}, err
		}
		var v Everything
		v.S = o.S
		v.E = o.E
		v.Bo = o.Bo
		v.I8 = o.I8
		v.I = o.I
		v.U64 = o.U64
		v.F32 = o.F32
		v.F64 = o.F64
		v.By = o.By
		v.Bl = o.Bl
		v.Sc = o.Sc
		v.Tags = o.Tags
		v.Ints = o.Ints
		v.F32s = o.F32s
		v.St = o.St
		v.D = o.D
		v.Emails = o.Emails
		v.Counts = o.Counts
		v.Labels = o.Labels
		v.ByKey = o.ByKey
		v.In = o.In
		v.Ins = o.Ins
		v.P = o.P
		v.PI = o.PI
		v.T = o.T
		v.N = o.N
		v.Nested = o.Nested
		v.Arr = o.Arr
		return v, nil
	},
})

// EncryptEverything seals each Everything, with one ZeroKMS request for each
// 500 sealed values, plus one the first time a keyset is used. The result has
// one element for each input, in the same order.
func EncryptEverything(ctx context.Context, cipher *encrypt.Cipher, values []Everything) ([]EncryptedEverything, error) {
	return everythingCodec.Encrypt(ctx, cipher, values)
}

// DecryptEverything opens each EncryptedEverything, with one ZeroKMS request
// for each 500 sealed values, plus one the first time a keyset is used.
func DecryptEverything(ctx context.Context, d encrypt.Decrypter, encrypted []EncryptedEverything) ([]Everything, error) {
	return everythingCodec.Decrypt(ctx, d, encrypted)
}
