// Code generated by stashgen. DO NOT EDIT.

package testusers

import (
	"context"
	"log/slog"

	"github.com/cipherstash/stack/languages/golang/encrypt"
	"github.com/cipherstash/stack/languages/golang/encrypt/gensupport"
)

// Stops compiling when the library does not accept this version of generated file.
const _ = gensupport.GeneratedVersion1

// Note prints its sealed fields in the clear: it has no String or LogValue
// method. Write them, or run stashgen with -redact.

type EncryptedNote struct {
	Tenant string
	Text   EncryptedNoteText
	ID     uint32
}

type EncryptedNoteText struct {
	Ciphertext encrypt.Ciphertext
	Equality   encrypt.EqualityTerm
}

func (e EncryptedNote) String() string {
	return gensupport.Redacted("EncryptedNote", map[string]any{"Tenant": e.Tenant, "ID": e.ID}, "Text")
}

func (e EncryptedNote) LogValue() slog.Value {
	return gensupport.RedactedLog(map[string]any{"Tenant": e.Tenant, "ID": e.ID}, "Text")
}

// Stops compiling when Note gains, loses, reorders or retypes a field.
var _ = noteShape(Note{})

type noteShape struct {
	Tenant string
	Text   string
	ID     uint32
}

var noteDeclaration = gensupport.DeclareContextField("tenant").
	EncryptIndex("text", gensupport.String, encrypt.Equality).
	Passthrough("id")

var noteCodec = gensupport.New(gensupport.Generated[Note, EncryptedNote]{
	TypeName:        "Note",
	Declaration:     noteDeclaration,
	PrintsPlaintext: true,
	Source: func(v Note) gensupport.Values {
		return gensupport.Values{
			"tenant": v.Tenant,
			"text":   v.Text,
			"id":     v.ID,
		}
	},
	Seal: func(rec gensupport.Record) (EncryptedNote, error) {
		var e EncryptedNote
		var err error
		if e.Tenant, err = gensupport.Passthrough[string](rec, "tenant"); err != nil {
			return EncryptedNote{}, err
		}
		if e.ID, err = gensupport.Passthrough[uint32](rec, "id"); err != nil {
			return EncryptedNote{}, err
		}
		e.Text = EncryptedNoteText{
			Ciphertext: rec["text"].Ciphertext,
			Equality:   rec["text"].Equality,
		}
		return e, nil
	},
	Open: func(e EncryptedNote) gensupport.Record {
		return gensupport.Record{
			"tenant": {Value: e.Tenant},
			"text":   {Ciphertext: e.Text.Ciphertext, Equality: e.Text.Equality},
			"id":     {Value: e.ID},
		}
	},
	Value: func(e EncryptedNote, vals gensupport.Values) (Note, error) {
		var v Note
		var err error
		if v.Tenant, err = gensupport.Get[string](vals, "tenant"); err != nil {
			return Note{}, err
		}
		if v.Text, err = gensupport.Get[string](vals, "text"); err != nil {
			return Note{}, err
		}
		if v.ID, err = gensupport.Get[uint32](vals, "id"); err != nil {
			return Note{}, err
		}
		return v, nil
	},
})

// EncryptNote seals each Note, with one ZeroKMS request for each 500 sealed
// values, plus one the first time a keyset is used. The result has one element
// for each input, in the same order.
func EncryptNote(ctx context.Context, cipher *encrypt.Cipher, values []Note) ([]EncryptedNote, error) {
	return noteCodec.Encrypt(ctx, cipher, values)
}

// DecryptNote opens each EncryptedNote, with one ZeroKMS request for each 500
// sealed values, plus one the first time a keyset is used.
func DecryptNote(ctx context.Context, d encrypt.Decrypter, encrypted []EncryptedNote) ([]Note, error) {
	return noteCodec.Decrypt(ctx, d, encrypted)
}

var NoteFields = struct {
	Text NoteTextField
}{
	Text: NoteTextField{gensupport.NewField[string](noteDeclaration, "text")},
}

type NoteTextField struct {
	field gensupport.Field[string]
}

func (f NoteTextField) Encrypt(ctx context.Context, c *encrypt.Cipher, v string) (EncryptedNoteText, error) {
	out, err := f.field.Encrypt(ctx, c, v)
	if err != nil {
		return EncryptedNoteText{}, err
	}
	return EncryptedNoteText{Ciphertext: out.Ciphertext, Equality: out.Equality}, nil
}

func (f NoteTextField) Equality(ctx context.Context, c *encrypt.Cipher, v string) (encrypt.EqualityTerm, error) {
	return f.field.Equality(ctx, c, v)
}
