// Code generated by stashgen. DO NOT EDIT.

package testusers

import (
	"context"
	"log/slog"

	"github.com/cipherstash/stack/languages/golang/encrypt"
	"github.com/cipherstash/stack/languages/golang/encrypt/gensupport"
)

// Stops compiling when the library does not accept this version of generated file.
const _ = gensupport.GeneratedVersion1

// Probe prints its sealed fields in the clear: it has no String or LogValue
// method. Write them, or run stashgen with -redact.

type EncryptedProbe struct {
	U32 EncryptedProbeU32
	U64 EncryptedProbeU64
	I64 EncryptedProbeI64
	S   EncryptedProbeS
	B   EncryptedProbeB
}

type EncryptedProbeU32 struct {
	Ciphertext encrypt.Ciphertext
	Ore        encrypt.OreTerm
	Ope        encrypt.OpeTerm
}

type EncryptedProbeU64 struct {
	Ciphertext encrypt.Ciphertext
	Ore        encrypt.OreTerm
	Ope        encrypt.OpeTerm
}

type EncryptedProbeI64 struct {
	Ciphertext encrypt.Ciphertext
	Ore        encrypt.OreTerm
	Ope        encrypt.OpeTerm
}

type EncryptedProbeS struct {
	Ciphertext encrypt.Ciphertext
	Ore        encrypt.OreTerm
	Ope        encrypt.OpeTerm
}

type EncryptedProbeB struct {
	Ciphertext encrypt.Ciphertext
	Ore        encrypt.OreTerm
	Ope        encrypt.OpeTerm
}

func (e EncryptedProbe) String() string {
	return gensupport.Redacted("EncryptedProbe", nil, "U32", "U64", "I64", "S", "B")
}

func (e EncryptedProbe) LogValue() slog.Value {
	return gensupport.RedactedLog(nil, "U32", "U64", "I64", "S", "B")
}

// Stops compiling when Probe gains, loses, reorders or retypes a field.
var _ = probeShape(Probe{})

type probeShape struct {
	_   struct{}
	U32 uint32
	U64 uint64
	I64 int64
	S   string
	B   []byte
}

var probeDeclaration = gensupport.Declare("prop").
	EncryptIndex("u32", gensupport.UInt32, encrypt.Ore, encrypt.Ope).
	EncryptIndex("u64", gensupport.UInt64, encrypt.Ore, encrypt.Ope).
	EncryptIndex("i64", gensupport.Int64, encrypt.Ore, encrypt.Ope).
	EncryptIndex("s", gensupport.String, encrypt.Ore, encrypt.Ope).
	EncryptIndex("b", gensupport.Bytes, encrypt.Ore, encrypt.Ope)

var probeCodec = gensupport.New(gensupport.Generated[Probe, EncryptedProbe]{
	TypeName:        "Probe",
	Declaration:     probeDeclaration,
	PrintsPlaintext: true,
	Source: func(v Probe) gensupport.Values {
		return gensupport.Values{
			"u32": v.U32,
			"u64": v.U64,
			"i64": v.I64,
			"s":   v.S,
			"b":   v.B,
		}
	},
	Seal: func(rec gensupport.Record) (EncryptedProbe, error) {
		var e EncryptedProbe
		e.U32 = EncryptedProbeU32{
			Ciphertext: rec["u32"].Ciphertext,
			Ore:        rec["u32"].Ore,
			Ope:        rec["u32"].Ope,
		}
		e.U64 = EncryptedProbeU64{
			Ciphertext: rec["u64"].Ciphertext,
			Ore:        rec["u64"].Ore,
			Ope:        rec["u64"].Ope,
		}
		e.I64 = EncryptedProbeI64{
			Ciphertext: rec["i64"].Ciphertext,
			Ore:        rec["i64"].Ore,
			Ope:        rec["i64"].Ope,
		}
		e.S = EncryptedProbeS{
			Ciphertext: rec["s"].Ciphertext,
			Ore:        rec["s"].Ore,
			Ope:        rec["s"].Ope,
		}
		e.B = EncryptedProbeB{
			Ciphertext: rec["b"].Ciphertext,
			Ore:        rec["b"].Ore,
			Ope:        rec["b"].Ope,
		}
		return e, nil
	},
	Open: func(e EncryptedProbe) gensupport.Record {
		return gensupport.Record{
			"u32": {Ciphertext: e.U32.Ciphertext, Ore: e.U32.Ore, Ope: e.U32.Ope},
			"u64": {Ciphertext: e.U64.Ciphertext, Ore: e.U64.Ore, Ope: e.U64.Ope},
			"i64": {Ciphertext: e.I64.Ciphertext, Ore: e.I64.Ore, Ope: e.I64.Ope},
			"s":   {Ciphertext: e.S.Ciphertext, Ore: e.S.Ore, Ope: e.S.Ope},
			"b":   {Ciphertext: e.B.Ciphertext, Ore: e.B.Ore, Ope: e.B.Ope},
		}
	},
	Value: func(e EncryptedProbe, vals gensupport.Values) (Probe, error) {
		var v Probe
		var err error
		if v.U32, err = gensupport.Get[uint32](vals, "u32"); err != nil {
			return Probe{}, err
		}
		if v.U64, err = gensupport.Get[uint64](vals, "u64"); err != nil {
			return Probe{}, err
		}
		if v.I64, err = gensupport.Get[int64](vals, "i64"); err != nil {
			return Probe{}, err
		}
		if v.S, err = gensupport.Get[string](vals, "s"); err != nil {
			return Probe{}, err
		}
		if v.B, err = gensupport.Get[[]byte](vals, "b"); err != nil {
			return Probe{}, err
		}
		return v, nil
	},
})

// EncryptProbe seals each Probe, with one ZeroKMS request for each 500 sealed
// values. The result has one element for each input, in the same order.
func EncryptProbe(ctx context.Context, cipher *encrypt.Cipher, values []Probe) ([]EncryptedProbe, error) {
	return probeCodec.Encrypt(ctx, cipher, values)
}

// DecryptProbe opens each EncryptedProbe, with one ZeroKMS request for each 500
// sealed values.
func DecryptProbe(ctx context.Context, d encrypt.Decrypter, encrypted []EncryptedProbe) ([]Probe, error) {
	return probeCodec.Decrypt(ctx, d, encrypted)
}

var ProbeFields = struct {
	U32 ProbeU32Field
	U64 ProbeU64Field
	I64 ProbeI64Field
	S   ProbeSField
	B   ProbeBField
}{
	U32: ProbeU32Field{gensupport.NewField[uint32](probeDeclaration, "u32")},
	U64: ProbeU64Field{gensupport.NewField[uint64](probeDeclaration, "u64")},
	I64: ProbeI64Field{gensupport.NewField[int64](probeDeclaration, "i64")},
	S:   ProbeSField{gensupport.NewField[string](probeDeclaration, "s")},
	B:   ProbeBField{gensupport.NewField[[]byte](probeDeclaration, "b")},
}

type ProbeU32Field struct {
	field gensupport.Field[uint32]
}

func (f ProbeU32Field) Encrypt(ctx context.Context, c *encrypt.Cipher, v uint32) (EncryptedProbeU32, error) {
	out, err := f.field.Encrypt(ctx, c, v)
	if err != nil {
		return EncryptedProbeU32{}, err
	}
	return EncryptedProbeU32{Ciphertext: out.Ciphertext, Ore: out.Ore, Ope: out.Ope}, nil
}

func (f ProbeU32Field) Ore(ctx context.Context, c *encrypt.Cipher, v uint32) (encrypt.OreTerm, error) {
	return f.field.Ore(ctx, c, v)
}

func (f ProbeU32Field) Ope(ctx context.Context, c *encrypt.Cipher, v uint32) (encrypt.OpeTerm, error) {
	return f.field.Ope(ctx, c, v)
}

type ProbeU64Field struct {
	field gensupport.Field[uint64]
}

func (f ProbeU64Field) Encrypt(ctx context.Context, c *encrypt.Cipher, v uint64) (EncryptedProbeU64, error) {
	out, err := f.field.Encrypt(ctx, c, v)
	if err != nil {
		return EncryptedProbeU64{}, err
	}
	return EncryptedProbeU64{Ciphertext: out.Ciphertext, Ore: out.Ore, Ope: out.Ope}, nil
}

func (f ProbeU64Field) Ore(ctx context.Context, c *encrypt.Cipher, v uint64) (encrypt.OreTerm, error) {
	return f.field.Ore(ctx, c, v)
}

func (f ProbeU64Field) Ope(ctx context.Context, c *encrypt.Cipher, v uint64) (encrypt.OpeTerm, error) {
	return f.field.Ope(ctx, c, v)
}

type ProbeI64Field struct {
	field gensupport.Field[int64]
}

func (f ProbeI64Field) Encrypt(ctx context.Context, c *encrypt.Cipher, v int64) (EncryptedProbeI64, error) {
	out, err := f.field.Encrypt(ctx, c, v)
	if err != nil {
		return EncryptedProbeI64{}, err
	}
	return EncryptedProbeI64{Ciphertext: out.Ciphertext, Ore: out.Ore, Ope: out.Ope}, nil
}

func (f ProbeI64Field) Ore(ctx context.Context, c *encrypt.Cipher, v int64) (encrypt.OreTerm, error) {
	return f.field.Ore(ctx, c, v)
}

func (f ProbeI64Field) Ope(ctx context.Context, c *encrypt.Cipher, v int64) (encrypt.OpeTerm, error) {
	return f.field.Ope(ctx, c, v)
}

type ProbeSField struct {
	field gensupport.Field[string]
}

func (f ProbeSField) Encrypt(ctx context.Context, c *encrypt.Cipher, v string) (EncryptedProbeS, error) {
	out, err := f.field.Encrypt(ctx, c, v)
	if err != nil {
		return EncryptedProbeS{}, err
	}
	return EncryptedProbeS{Ciphertext: out.Ciphertext, Ore: out.Ore, Ope: out.Ope}, nil
}

func (f ProbeSField) Ore(ctx context.Context, c *encrypt.Cipher, v string) (encrypt.OreTerm, error) {
	return f.field.Ore(ctx, c, v)
}

func (f ProbeSField) Ope(ctx context.Context, c *encrypt.Cipher, v string) (encrypt.OpeTerm, error) {
	return f.field.Ope(ctx, c, v)
}

type ProbeBField struct {
	field gensupport.Field[[]byte]
}

func (f ProbeBField) Encrypt(ctx context.Context, c *encrypt.Cipher, v []byte) (EncryptedProbeB, error) {
	out, err := f.field.Encrypt(ctx, c, v)
	if err != nil {
		return EncryptedProbeB{}, err
	}
	return EncryptedProbeB{Ciphertext: out.Ciphertext, Ore: out.Ore, Ope: out.Ope}, nil
}

func (f ProbeBField) Ore(ctx context.Context, c *encrypt.Cipher, v []byte) (encrypt.OreTerm, error) {
	return f.field.Ore(ctx, c, v)
}

func (f ProbeBField) Ope(ctx context.Context, c *encrypt.Cipher, v []byte) (encrypt.OpeTerm, error) {
	return f.field.Ope(ctx, c, v)
}
