// Code generated by stashgen. DO NOT EDIT.

package testusers

import (
	"context"
	"log/slog"

	"github.com/cipherstash/stack/languages/golang/encrypt"
	"github.com/cipherstash/stack/languages/golang/encrypt/gensupport"
)

// Stops compiling when the library does not accept this version of generated file.
const _ = gensupport.GeneratedVersion1

// User prints its sealed fields in the clear: it has no String or LogValue
// method. Write them, or run stashgen with -redact.

type EncryptedUser struct {
	ID    int64
	Age   EncryptedUserAge
	Email EncryptedUserEmail
	Notes EncryptedUserNotes
}

type EncryptedUserAge struct {
	Ciphertext encrypt.Ciphertext
	Equality   encrypt.EqualityTerm
	Ore        encrypt.OreTerm
}

type EncryptedUserEmail struct {
	Ciphertext encrypt.Ciphertext
	Equality   encrypt.EqualityTerm
	Match      encrypt.MatchTerm
}

type EncryptedUserNotes struct {
	Ciphertext encrypt.Ciphertext
}

func (e EncryptedUser) String() string {
	return gensupport.Redacted("EncryptedUser", map[string]any{"ID": e.ID}, "Age", "Email", "Notes")
}

func (e EncryptedUser) LogValue() slog.Value {
	return gensupport.RedactedLog(map[string]any{"ID": e.ID}, "Age", "Email", "Notes")
}

// Stops compiling when User gains, loses, reorders or retypes a field.
var _ = userShape(User{})

type userShape struct {
	_        struct{}
	ID       int64
	Age      uint32
	Email    string
	Notes    string
	Internal string
}

var declaration = gensupport.Declare("users").
	Passthrough("id").
	EncryptIndex("age", gensupport.UInt32, encrypt.Equality, encrypt.Ore).
	EncryptIndex("email", gensupport.String, encrypt.Equality, encrypt.Match()).
	Encrypt("notes", gensupport.String).
	Omit("internal")

var codec = gensupport.New(gensupport.Generated[User, EncryptedUser]{
	TypeName:        "User",
	Declaration:     declaration,
	PrintsPlaintext: true,
	Source: func(v User) gensupport.Values {
		return gensupport.Values{
			"id":    v.ID,
			"age":   v.Age,
			"email": v.Email,
			"notes": v.Notes,
		}
	},
	Seal: func(rec gensupport.Record) (EncryptedUser, error) {
		var e EncryptedUser
		var err error
		if e.ID, err = gensupport.Passthrough[int64](rec, "id"); err != nil {
			return EncryptedUser{}, err
		}
		e.Age = EncryptedUserAge{
			Ciphertext: rec["age"].Ciphertext,
			Equality:   rec["age"].Equality,
			Ore:        rec["age"].Ore,
		}
		e.Email = EncryptedUserEmail{
			Ciphertext: rec["email"].Ciphertext,
			Equality:   rec["email"].Equality,
			Match:      rec["email"].Match,
		}
		e.Notes = EncryptedUserNotes{Ciphertext: rec["notes"].Ciphertext}
		return e, nil
	},
	Open: func(e EncryptedUser) gensupport.Record {
		return gensupport.Record{
			"id":    {Value: e.ID},
			"age":   {Ciphertext: e.Age.Ciphertext, Equality: e.Age.Equality, Ore: e.Age.Ore},
			"email": {Ciphertext: e.Email.Ciphertext, Equality: e.Email.Equality, Match: e.Email.Match},
			"notes": {Ciphertext: e.Notes.Ciphertext},
		}
	},
	Value: func(e EncryptedUser, vals gensupport.Values) (User, error) {
		var v User
		var err error
		if v.ID, err = gensupport.Get[int64](vals, "id"); err != nil {
			return User{}, err
		}
		if v.Age, err = gensupport.Get[uint32](vals, "age"); err != nil {
			return User{}, err
		}
		if v.Email, err = gensupport.Get[string](vals, "email"); err != nil {
			return User{}, err
		}
		if v.Notes, err = gensupport.Get[string](vals, "notes"); err != nil {
			return User{}, err
		}
		return v, nil
	},
})

// Encrypt seals each User, with one ZeroKMS request for each 500 sealed values.
// The result has one element for each input, in the same order.
func Encrypt(ctx context.Context, cipher *encrypt.Cipher, testusers []User) ([]EncryptedUser, error) {
	return codec.Encrypt(ctx, cipher, testusers)
}

// Decrypt opens each EncryptedUser, with one ZeroKMS request for each 500
// sealed values.
func Decrypt(ctx context.Context, d encrypt.Decrypter, encrypted []EncryptedUser) ([]User, error) {
	return codec.Decrypt(ctx, d, encrypted)
}

var Fields = struct {
	Age   AgeField
	Email EmailField
	Notes NotesField
}{
	Age:   AgeField{gensupport.NewField[uint32](declaration, "age")},
	Email: EmailField{gensupport.NewField[string](declaration, "email")},
	Notes: NotesField{gensupport.NewField[string](declaration, "notes")},
}

type AgeField struct {
	field gensupport.Field[uint32]
}

func (f AgeField) Encrypt(ctx context.Context, c *encrypt.Cipher, v uint32) (EncryptedUserAge, error) {
	out, err := f.field.Encrypt(ctx, c, v)
	if err != nil {
		return EncryptedUserAge{}, err
	}
	return EncryptedUserAge{Ciphertext: out.Ciphertext, Equality: out.Equality, Ore: out.Ore}, nil
}

func (f AgeField) Equality(ctx context.Context, c *encrypt.Cipher, v uint32) (encrypt.EqualityTerm, error) {
	return f.field.Equality(ctx, c, v)
}

func (f AgeField) Ore(ctx context.Context, c *encrypt.Cipher, v uint32) (encrypt.OreTerm, error) {
	return f.field.Ore(ctx, c, v)
}

type EmailField struct {
	field gensupport.Field[string]
}

func (f EmailField) Encrypt(ctx context.Context, c *encrypt.Cipher, v string) (EncryptedUserEmail, error) {
	out, err := f.field.Encrypt(ctx, c, v)
	if err != nil {
		return EncryptedUserEmail{}, err
	}
	return EncryptedUserEmail{Ciphertext: out.Ciphertext, Equality: out.Equality, Match: out.Match}, nil
}

func (f EmailField) Equality(ctx context.Context, c *encrypt.Cipher, v string) (encrypt.EqualityTerm, error) {
	return f.field.Equality(ctx, c, v)
}

func (f EmailField) Match(ctx context.Context, c *encrypt.Cipher, v string) (encrypt.MatchTerm, error) {
	return f.field.Match(ctx, c, v)
}

type NotesField struct {
	field gensupport.Field[string]
}

func (f NotesField) Encrypt(ctx context.Context, c *encrypt.Cipher, v string) (EncryptedUserNotes, error) {
	out, err := f.field.Encrypt(ctx, c, v)
	return EncryptedUserNotes{Ciphertext: out.Ciphertext}, err
}

// The -model flag: UserRow converts to and from its shape only while the
// two have the same fields, with the same types, in the same order.
type rowsShape struct {
	ID         int64
	Age        encrypt.Ciphertext
	AgeEq      encrypt.EqualityTerm
	AgeOre     encrypt.OreTerm
	Email      encrypt.Ciphertext
	EmailEq    encrypt.EqualityTerm
	EmailMatch encrypt.MatchTerm
	Notes      encrypt.Ciphertext
}

var rowsCodec = gensupport.Records(codec,
	func(e EncryptedUser) UserRow {
		return UserRow(rowsShape{
			ID:         e.ID,
			Age:        e.Age.Ciphertext,
			AgeEq:      e.Age.Equality,
			AgeOre:     e.Age.Ore,
			Email:      e.Email.Ciphertext,
			EmailEq:    e.Email.Equality,
			EmailMatch: e.Email.Match,
			Notes:      e.Notes.Ciphertext,
		})
	},
	func(r UserRow) EncryptedUser {
		s := rowsShape(r)
		return EncryptedUser{
			ID:    s.ID,
			Age:   EncryptedUserAge{Ciphertext: s.Age, Equality: s.AgeEq, Ore: s.AgeOre},
			Email: EncryptedUserEmail{Ciphertext: s.Email, Equality: s.EmailEq, Match: s.EmailMatch},
			Notes: EncryptedUserNotes{Ciphertext: s.Notes},
		}
	},
)

func EncryptRows(ctx context.Context, cipher *encrypt.Cipher, testusers []User) ([]UserRow, error) {
	return rowsCodec.Encrypt(ctx, cipher, testusers)
}

func DecryptRows(ctx context.Context, d encrypt.Decrypter, rows []UserRow) ([]User, error) {
	return rowsCodec.Decrypt(ctx, d, rows)
}
