name: "Run stack-profile tests"
on:
  push:
    branches:
      - main
    paths:
      - packages/stack-profile/**
      - .github/workflows/test-stack-profile.yml
      # Ordering matters, this needs to stay at the end if we want to include the above, but exclude all .md files.
      - "!**.md"
      - "!**.example"

  pull_request:
    paths:
      - packages/stack-profile/**
      - .github/workflows/test-stack-profile.yml
      # Ordering matters, this needs to stay at the end if we want to include the above, but exclude all .md files.
      - "!**.md"
      - "!**.example"

  workflow_dispatch:

defaults:
  run:
    shell: bash

env:
  RUSTFLAGS: "-D warnings"
  RUST_BACKTRACE: full
  CARGO_TERM_COLOR: always
  CARGO_NET_GIT_FETCH_WITH_CLI: true
  NEXTEST_PROFILE: ci

jobs:
  test-stack-profile:
    runs-on: blacksmith-8vcpu-ubuntu-2404

    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-rust

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Fix permissions on target directory
        run: |
          mkdir -p ./target
          sudo chown -R "$(id -u):$(id -g)" ./target

      - name: test-unit
        run: mise x --env test -- cargo nextest run -p stack-profile

      - name: test-integration-stack-profile
        run: mise run test:integration:stack-profile

      - uses: ./.github/actions/send-slack-notification
        with:
          channel: engineering
          webhook_url: ${{ secrets.SLACK_NOTIFICATION_WEBHOOK_URL }}
