// Code generated by stashgen. DO NOT EDIT.

package users

import (
	"context"

	"example.com/app/internal/userdb"
	"github.com/cipherstash/stack/languages/golang/stackencrypt"
	"github.com/cipherstash/stack/languages/golang/stackencrypt/gensupport"
)

// Stops compiling when the library does not accept this version of generated file.
const _ = gensupport.GeneratedVersion1

type EncryptedUser struct {
	ID    int64
	Email EncryptedUserEmail
	Age   EncryptedUserAge
	Attrs stackencrypt.JSONDocument
	Notes stackencrypt.Ciphertext
}

type EncryptedUserEmail struct {
	Ciphertext stackencrypt.Ciphertext
	Equality   stackencrypt.EqualityTerm
	Match      stackencrypt.MatchTerm
}

type EncryptedUserAge struct {
	Ciphertext stackencrypt.Ciphertext
	Equality   stackencrypt.EqualityTerm
	Ore        stackencrypt.OreTerm
}

// Stops compiling when User gains, loses, reorders or retypes a field.
var _ = userShape(User{})

type userShape struct {
	_        struct{}
	ID       int64
	Email    string
	Age      uint32
	Attrs    map[string]any
	Notes    string
	Internal string
}

var userSpec = gensupport.NewPlan("users").
	EncryptIndex("email", stackencrypt.Equality, stackencrypt.Match()).
	EncryptIndex("age", stackencrypt.Equality, stackencrypt.Ore).
	Index("attrs", stackencrypt.JSON()).
	Encrypt("notes")

var userPlan = gensupport.New(gensupport.Generated[User, EncryptedUser]{
	Plan: userSpec,
	Source: func(v User) gensupport.Values {
		return gensupport.Values{"email": v.Email, "age": v.Age, "attrs": v.Attrs, "notes": v.Notes}
	},
	Seal: func(v User, rec gensupport.Record) EncryptedUser {
		email, age := rec["email"], rec["age"]
		return EncryptedUser{
			ID:    v.ID,
			Email: EncryptedUserEmail{Ciphertext: email.Ciphertext, Equality: email.Equality, Match: email.Match},
			Age:   EncryptedUserAge{Ciphertext: age.Ciphertext, Equality: age.Equality, Ore: age.Ore},
			Attrs: rec["attrs"].JSON,
			Notes: rec["notes"].Ciphertext,
		}
	},
	Open: func(e EncryptedUser) gensupport.Record {
		return gensupport.Record{
			"email": {Ciphertext: e.Email.Ciphertext, Equality: e.Email.Equality, Match: e.Email.Match},
			"age":   {Ciphertext: e.Age.Ciphertext, Equality: e.Age.Equality, Ore: e.Age.Ore},
			"attrs": {JSON: e.Attrs},
			"notes": {Ciphertext: e.Notes},
		}
	},
	Value: func(e EncryptedUser, vals gensupport.Values) (User, error) {
		v := User{ID: e.ID}
		var err error
		if v.Email, err = gensupport.Get[string](vals, "email"); err != nil {
			return User{}, err
		}
		if v.Age, err = gensupport.Get[uint32](vals, "age"); err != nil {
			return User{}, err
		}
		if v.Attrs, err = gensupport.Get[map[string]any](vals, "attrs"); err != nil {
			return User{}, err
		}
		if v.Notes, err = gensupport.Get[string](vals, "notes"); err != nil {
			return User{}, err
		}
		return v, nil
	},
})

func (User) StashPlan() *stackencrypt.RowPlan[User, EncryptedUser] { return userPlan }

func (EncryptedUser) StashPlan() *stackencrypt.RowPlan[User, EncryptedUser] { return userPlan }

var UserFields = struct {
	Email UserEmailField
	Age   UserAgeField
	Attrs UserAttrsField
	Notes UserNotesField
}{
	Email: UserEmailField{gensupport.NewField[string](userSpec, "email")},
	Age:   UserAgeField{gensupport.NewField[uint32](userSpec, "age")},
	Attrs: UserAttrsField{gensupport.NewField[map[string]any](userSpec, "attrs")},
	Notes: UserNotesField{gensupport.NewField[string](userSpec, "notes")},
}

type UserEmailField struct {
	plan gensupport.Field[string]
}

func (f UserEmailField) Encrypt(ctx context.Context, c *stackencrypt.Cipher, v string, opts ...stackencrypt.Option) (EncryptedUserEmail, error) {
	out, err := f.plan.Encrypt(ctx, c, v, opts...)
	if err != nil {
		return EncryptedUserEmail{}, err
	}
	return EncryptedUserEmail{Ciphertext: out.Ciphertext, Equality: out.Equality, Match: out.Match}, nil
}

func (f UserEmailField) Equality(ctx context.Context, c *stackencrypt.Cipher, v string, opts ...stackencrypt.Option) (stackencrypt.EqualityTerm, error) {
	return f.plan.Equality(ctx, c, v, opts...)
}

func (f UserEmailField) Match(ctx context.Context, c *stackencrypt.Cipher, v string, opts ...stackencrypt.Option) (stackencrypt.MatchTerm, error) {
	return f.plan.Match(ctx, c, v, opts...)
}

type UserAgeField struct {
	plan gensupport.Field[uint32]
}

func (f UserAgeField) Encrypt(ctx context.Context, c *stackencrypt.Cipher, v uint32, opts ...stackencrypt.Option) (EncryptedUserAge, error) {
	out, err := f.plan.Encrypt(ctx, c, v, opts...)
	if err != nil {
		return EncryptedUserAge{}, err
	}
	return EncryptedUserAge{Ciphertext: out.Ciphertext, Equality: out.Equality, Ore: out.Ore}, nil
}

func (f UserAgeField) Equality(ctx context.Context, c *stackencrypt.Cipher, v uint32, opts ...stackencrypt.Option) (stackencrypt.EqualityTerm, error) {
	return f.plan.Equality(ctx, c, v, opts...)
}

func (f UserAgeField) Ore(ctx context.Context, c *stackencrypt.Cipher, v uint32, opts ...stackencrypt.Option) (stackencrypt.OreTerm, error) {
	return f.plan.Ore(ctx, c, v, opts...)
}

type UserAttrsField struct {
	plan gensupport.Field[map[string]any]
}

func (f UserAttrsField) Encrypt(ctx context.Context, c *stackencrypt.Cipher, v map[string]any, opts ...stackencrypt.Option) (stackencrypt.JSONDocument, error) {
	out, err := f.plan.Encrypt(ctx, c, v, opts...)
	return out.JSON, err
}

func (f UserAttrsField) Contains(ctx context.Context, c *stackencrypt.Cipher, v map[string]any, opts ...stackencrypt.Option) (stackencrypt.JSONQuery, error) {
	return f.plan.Contains(ctx, c, v, opts...)
}

func (f UserAttrsField) Selector(ctx context.Context, c *stackencrypt.Cipher, path stackencrypt.JSONPath, opts ...stackencrypt.Option) (stackencrypt.JSONSelector, error) {
	return f.plan.Selector(ctx, c, path, opts...)
}

func (f UserAttrsField) EqualAt(ctx context.Context, c *stackencrypt.Cipher, path stackencrypt.JSONPath, v any, opts ...stackencrypt.Option) (stackencrypt.JSONQuery, error) {
	return f.plan.EqualAt(ctx, c, path, v, opts...)
}

type UserNotesField struct {
	plan gensupport.Field[string]
}

func (f UserNotesField) Encrypt(ctx context.Context, c *stackencrypt.Cipher, v string, opts ...stackencrypt.Option) (stackencrypt.Ciphertext, error) {
	out, err := f.plan.Encrypt(ctx, c, v, opts...)
	return out.Ciphertext, err
}

// A row struct converts to and from its shape only while the two have the same
// fields, with the same types, in the same order. A change to the row struct
// stops this file compiling.
type userRowShape struct {
	ID         int64
	Email      stackencrypt.Ciphertext
	EmailEq    stackencrypt.EqualityTerm
	EmailMatch stackencrypt.MatchTerm
	Age        stackencrypt.Ciphertext
	AgeEq      stackencrypt.EqualityTerm
	AgeOre     stackencrypt.OreTerm
	Attrs      stackencrypt.JSONDocument
	Notes      stackencrypt.Ciphertext
}

func userRowShapeOf(e EncryptedUser) userRowShape {
	return userRowShape{
		ID:         e.ID,
		Email:      e.Email.Ciphertext,
		EmailEq:    e.Email.Equality,
		EmailMatch: e.Email.Match,
		Age:        e.Age.Ciphertext,
		AgeEq:      e.Age.Equality,
		AgeOre:     e.Age.Ore,
		Attrs:      e.Attrs,
		Notes:      e.Notes,
	}
}

func (s userRowShape) encrypted() EncryptedUser {
	return EncryptedUser{
		ID:    s.ID,
		Email: EncryptedUserEmail{Ciphertext: s.Email, Equality: s.EmailEq, Match: s.EmailMatch},
		Age:   EncryptedUserAge{Ciphertext: s.Age, Equality: s.AgeEq, Ore: s.AgeOre},
		Attrs: s.Attrs,
		Notes: s.Notes,
	}
}

var UserRows = gensupport.Rows(userPlan,
	func(e EncryptedUser) UserRow { return UserRow(userRowShapeOf(e)) },
	func(r UserRow) EncryptedUser { return userRowShape(r).encrypted() },
)

var SQLCUsers = gensupport.Rows(userPlan,
	func(e EncryptedUser) userdb.User { return userdb.User(userRowShapeOf(e)) },
	func(r userdb.User) EncryptedUser { return userRowShape(r).encrypted() },
)
