// Code generated by stashgen. DO NOT EDIT.

package users

import (
	"context"
	"log/slog"

	"github.com/cipherstash/stack/languages/golang/encrypt"
	"github.com/cipherstash/stack/languages/golang/encrypt/eql"
	"github.com/cipherstash/stack/languages/golang/encrypt/gensupport"
)

// Stops compiling when the library does not accept this version of generated file.
const _ = gensupport.GeneratedVersion1

// User prints its sealed fields in the clear: it has no String or LogValue
// method. Write them, or run stashgen with -redact.

type EncryptedUser struct {
	ID    int64      `db:"id" gorm:"primaryKey"`
	Email eql.TextEq `db:"email"`
	Name  eql.TextEq `db:"name"`
}

func (e EncryptedUser) String() string {
	return gensupport.Redacted("EncryptedUser", map[string]any{"ID": e.ID}, "Email", "Name")
}

func (e EncryptedUser) LogValue() slog.Value {
	return gensupport.RedactedLog(map[string]any{"ID": e.ID}, "Email", "Name")
}

// Stops compiling when User gains, loses, reorders or retypes a field.
var _ = userShape(User{})

type userShape struct {
	_        struct{}
	ID       int64
	Email    string
	Name     string
	Internal string
}

var declaration = gensupport.Declare("users").
	Passthrough("id").
	EncryptInto("email", "TextEq").
	EncryptInto("name", "TextEq").
	Omit("internal")

var codec = gensupport.New(gensupport.Generated[User, EncryptedUser]{
	TypeName:        "User",
	Declaration:     declaration,
	PrintsPlaintext: true,
	Source: func(v User) gensupport.Values {
		return gensupport.Values{"id": v.ID, "email": v.Email, "name": v.Name}
	},
	Seal: func(rec gensupport.Record) (EncryptedUser, error) {
		id, err := gensupport.Passthrough[int64](rec, "id")
		if err != nil {
			return EncryptedUser{}, err
		}
		return EncryptedUser{
			ID:    id,
			Email: eql.TextEq(rec["email"].EQL),
			Name:  eql.TextEq(rec["name"].EQL),
		}, nil
	},
	Open: func(e EncryptedUser) gensupport.Record {
		return gensupport.Record{"id": {Value: e.ID}, "email": {EQL: e.Email}, "name": {EQL: e.Name}}
	},
	Value: func(e EncryptedUser, vals gensupport.Values) (User, error) {
		var v User
		var err error
		if v.ID, err = gensupport.Get[int64](vals, "id"); err != nil {
			return User{}, err
		}
		if v.Email, err = gensupport.Get[string](vals, "email"); err != nil {
			return User{}, err
		}
		if v.Name, err = gensupport.Get[string](vals, "name"); err != nil {
			return User{}, err
		}
		return v, nil
	},
})

// Encrypt seals every user in one ZeroKMS request. The result has one element
// for each user, in the same order.
func Encrypt(ctx context.Context, cipher *encrypt.Cipher, users []User) ([]EncryptedUser, error) {
	return codec.Encrypt(ctx, cipher, users)
}

// Decrypt opens every value in one ZeroKMS request.
func Decrypt(ctx context.Context, d encrypt.Decrypter, encrypted []EncryptedUser) ([]User, error) {
	return codec.Decrypt(ctx, d, encrypted)
}

var Fields = struct {
	Email EmailField
	Name  NameField
}{
	Email: EmailField{gensupport.NewField[string](declaration, "email")},
	Name:  NameField{gensupport.NewField[string](declaration, "name")},
}

type EmailField struct {
	field gensupport.Field[string]
}

func (f EmailField) Encrypt(ctx context.Context, c *encrypt.Cipher, v string) (eql.TextEq, error) {
	out, err := f.field.Encrypt(ctx, c, v)
	return eql.TextEq(out.EQL), err
}

func (f EmailField) Query(ctx context.Context, c *encrypt.Cipher, v string) (eql.TextEqQuery, error) {
	out, err := f.field.Query(ctx, c, v)
	return eql.TextEqQuery(out.EQL), err
}

type NameField struct {
	field gensupport.Field[string]
}

func (f NameField) Encrypt(ctx context.Context, c *encrypt.Cipher, v string) (eql.TextEq, error) {
	out, err := f.field.Encrypt(ctx, c, v)
	return eql.TextEq(out.EQL), err
}

func (f NameField) Query(ctx context.Context, c *encrypt.Cipher, v string) (eql.TextEqQuery, error) {
	out, err := f.field.Query(ctx, c, v)
	return eql.TextEqQuery(out.EQL), err
}
