// Code generated by stashgen. DO NOT EDIT.

package users

import (
	"context"
	"log/slog"

	"github.com/cipherstash/stack/languages/golang/stackencrypt"
	"github.com/cipherstash/stack/languages/golang/stackencrypt/eql"
	"github.com/cipherstash/stack/languages/golang/stackencrypt/gensupport"
)

// Stops compiling when the library does not accept this version of generated file.
const _ = gensupport.GeneratedVersion1

// User prints its sealed fields in the clear: it has no String or LogValue
// method. Write them, or run stashgen with -redact.

type EncryptedUser struct {
	ID    int64          `db:"id" gorm:"primaryKey"`
	Email eql.TextSearch `db:"email"`
	Age   eql.IntegerOrd `db:"age"`
	Attrs eql.JSON       `db:"attrs"`
	Notes eql.Text       `db:"notes"`
}

func (e EncryptedUser) String() string {
	return gensupport.Redacted("EncryptedUser", map[string]any{"ID": e.ID}, "Email", "Age", "Attrs", "Notes")
}

func (e EncryptedUser) LogValue() slog.Value {
	return gensupport.RedactedLog(map[string]any{"ID": e.ID}, "Email", "Age", "Attrs", "Notes")
}

// Stops compiling when User gains, loses, reorders or retypes a field.
var _ = userShape(User{})

type userShape struct {
	_        struct{}
	ID       int64
	Email    string
	Age      int32
	Attrs    map[string]any
	Notes    string
	Internal string
}

var declaration = gensupport.Declare("users").
	Passthrough("id").
	EncryptIndex("email", stackencrypt.Equality, stackencrypt.Ore, stackencrypt.Match()).
	EncryptIndex("age", stackencrypt.Equality, stackencrypt.Ore).
	Index("attrs", stackencrypt.JSON()).
	Encrypt("notes").
	Omit("internal")

var codec = gensupport.New(gensupport.Generated[User, EncryptedUser]{
	TypeName:        "User",
	Declaration:     declaration,
	PrintsPlaintext: true,
	Source: func(v User) gensupport.Values {
		return gensupport.Values{"email": v.Email, "age": v.Age, "attrs": v.Attrs, "notes": v.Notes}
	},
	Seal: func(v User, rec gensupport.Record) EncryptedUser {
		return EncryptedUser{
			ID:    v.ID,
			Email: eql.NewTextSearch(rec["email"]),
			Age:   eql.NewIntegerOrd(rec["age"]),
			Attrs: eql.NewJSON(rec["attrs"]),
			Notes: eql.NewText(rec["notes"]),
		}
	},
	Open: func(e EncryptedUser) gensupport.Record {
		return gensupport.Record{
			"email": e.Email.Outputs(),
			"age":   e.Age.Outputs(),
			"attrs": e.Attrs.Outputs(),
			"notes": e.Notes.Outputs(),
		}
	},
	Value: func(e EncryptedUser, vals gensupport.Values) (User, error) {
		v := User{ID: e.ID}
		var err error
		if v.Email, err = gensupport.Get[string](vals, "email"); err != nil {
			return User{}, err
		}
		if v.Age, err = gensupport.Get[int32](vals, "age"); err != nil {
			return User{}, err
		}
		if v.Attrs, err = gensupport.Get[map[string]any](vals, "attrs"); err != nil {
			return User{}, err
		}
		if v.Notes, err = gensupport.Get[string](vals, "notes"); err != nil {
			return User{}, err
		}
		return v, nil
	},
})

// Encrypt seals every user in one ZeroKMS request. The result has one element
// for each user, in the same order.
func Encrypt(ctx context.Context, cipher *stackencrypt.Cipher, users []User) ([]EncryptedUser, error) {
	return codec.Encrypt(ctx, cipher, users)
}

// Decrypt opens every value in one ZeroKMS request.
func Decrypt(ctx context.Context, d stackencrypt.Decrypter, encrypted []EncryptedUser) ([]User, error) {
	return codec.Decrypt(ctx, d, encrypted)
}

// Encryption and Decryption describe the same work without running it, for
// stackencrypt.Batch2 and Batch3.
func Encryption(users []User) stackencrypt.Operation[[]EncryptedUser] {
	return codec.Encryption(users)
}

func Decryption(encrypted []EncryptedUser) stackencrypt.Operation[[]User] {
	return codec.Decryption(encrypted)
}

var Fields = struct {
	Email EmailField
	Age   AgeField
	Attrs AttrsField
	Notes NotesField
}{
	Email: EmailField{gensupport.NewField[string](declaration, "email")},
	Age:   AgeField{gensupport.NewField[int32](declaration, "age")},
	Attrs: AttrsField{gensupport.NewField[map[string]any](declaration, "attrs")},
	Notes: NotesField{gensupport.NewField[string](declaration, "notes")},
}

type EmailField struct {
	field gensupport.Field[string]
}

func (f EmailField) Encrypt(ctx context.Context, c *stackencrypt.Cipher, v string) (eql.TextSearch, error) {
	out, err := f.field.Encrypt(ctx, c, v)
	return eql.NewTextSearch(out), err
}

func (f EmailField) Query(ctx context.Context, c *stackencrypt.Cipher, v string) (eql.TextSearchQuery, error) {
	out, err := f.field.Query(ctx, c, v)
	return eql.NewTextSearchQuery(out), err
}

type AgeField struct {
	field gensupport.Field[int32]
}

func (f AgeField) Encrypt(ctx context.Context, c *stackencrypt.Cipher, v int32) (eql.IntegerOrd, error) {
	out, err := f.field.Encrypt(ctx, c, v)
	return eql.NewIntegerOrd(out), err
}

func (f AgeField) Query(ctx context.Context, c *stackencrypt.Cipher, v int32) (eql.IntegerOrdQuery, error) {
	out, err := f.field.Query(ctx, c, v)
	return eql.NewIntegerOrdQuery(out), err
}

type AttrsField struct {
	field gensupport.Field[map[string]any]
}

func (f AttrsField) Encrypt(ctx context.Context, c *stackencrypt.Cipher, v map[string]any) (eql.JSON, error) {
	out, err := f.field.Encrypt(ctx, c, v)
	return eql.NewJSON(out), err
}

func (f AttrsField) Contains(ctx context.Context, c *stackencrypt.Cipher, v map[string]any) (eql.JSONQuery, error) {
	out, err := f.field.Contains(ctx, c, v)
	return eql.JSONQuery(out.JSON), err
}

type NotesField struct {
	field gensupport.Field[string]
}

func (f NotesField) Encrypt(ctx context.Context, c *stackencrypt.Cipher, v string) (eql.Text, error) {
	out, err := f.field.Encrypt(ctx, c, v)
	return eql.NewText(out), err
}
