package main

import (
	"bytes"
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/cipherstash/stack/languages/golang/encrypt"
	"github.com/cipherstash/stack/languages/golang/stashgen"
	"github.com/cipherstash/stack/languages/golang/stashgen/enginetest"
)

func fake(context.Context) (stashgen.Engine, error) { return enginetest.Static{}, nil }

// writeModule writes a module that resolves the SDK to the generator's stub.
func writeModule(t *testing.T, files map[string]string) string {
	t.Helper()
	stubs, err := filepath.Abs(filepath.Join("..", "..", "stashgen", "testdata"))
	if err != nil {
		t.Fatal(err)
	}
	dir := t.TempDir()
	gomod := "module example.com/app\n\ngo 1.26\n\nrequire github.com/cipherstash/stack/languages/golang v0.0.0\n\nreplace github.com/cipherstash/stack/languages/golang => " + filepath.Join(stubs, "stubsdk") + "\n"
	if err := os.WriteFile(filepath.Join(dir, "go.mod"), []byte(gomod), 0o600); err != nil {
		t.Fatal(err)
	}
	for name, src := range files {
		if err := os.WriteFile(filepath.Join(dir, name), []byte(src), 0o600); err != nil {
			t.Fatal(err)
		}
	}
	return dir
}

const userSource = `package users

type User struct {
	_     struct{} ` + "`stash:\"context=users\"`" + `
	ID    int64    ` + "`stash:\"id,passthrough\"`" + `
	Email string   ` + "`stash:\"email,encrypt_into=TextEq\"`" + `
	cache string
}
`

func TestRunWritesTheFileAndPrintsTheNotices(t *testing.T) {
	dir := writeModule(t, map[string]string{"model.go": userSource})
	var stdout, stderr bytes.Buffer
	if code := run([]string{"-type", "User"}, dir, &stdout, &stderr, fake); code != 0 {
		t.Fatalf("exit %d\n%s", code, stderr.String())
	}
	out, err := os.ReadFile(filepath.Join(dir, "user_stash.go"))
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.HasPrefix(out, []byte("// Code generated by stashgen. DO NOT EDIT.\n")) {
		t.Fatalf("output starts with %q", out[:40])
	}
	for _, want := range []string{
		`stashgen: User: not encrypted and not stored: the unexported field "cache". Tag it ` + "`stash:\"-\"`" + ` to confirm that.`,
		"stashgen: User prints its sealed fields in the clear: it has no String or LogValue method. Write them, or run stashgen with -redact.",
	} {
		if !strings.Contains(stderr.String(), want) {
			t.Errorf("stderr lacks %q:\n%s", want, stderr.String())
		}
	}
	if stdout.Len() != 0 {
		t.Errorf("stdout = %q, want nothing", stdout.String())
	}

	// A second run over the stale file writes the same bytes.
	stderr.Reset()
	if code := run([]string{"-type", "User", "-redact"}, dir, &stdout, &stderr, fake); code != 0 {
		t.Fatalf("second run: exit %d\n%s", code, stderr.String())
	}
	again, err := os.ReadFile(filepath.Join(dir, "user_stash.go"))
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Contains(again, []byte("func (u User) String() string")) {
		t.Fatal("-redact did not write String on User")
	}
	if strings.Contains(stderr.String(), "prints its sealed fields") {
		t.Errorf("-redact still warns about printing:\n%s", stderr.String())
	}
}

func TestRunFlags(t *testing.T) {
	dir := writeModule(t, map[string]string{"model.go": userSource})
	cases := []struct {
		args []string
		code int
		want string
	}{
		{nil, 2, "-type is required"},
		{[]string{"-type"}, 2, "flag needs an argument"},
		{[]string{"-type", "User", "extra"}, 2, `unexpected argument "extra"`},
		{[]string{"-type", "User", "-model", "Rows"}, 2, "is not Name=R or Name=R:D"},
		{[]string{"-type", "User", "-model", "rows=R"}, 2, "must be an exported Go name"},
		{[]string{"-type", "Nobody"}, 1, "has no type Nobody"},
		{[]string{"-type", "User", "-output", "custom_stash.go"}, 0, ""},
		{[]string{"-h"}, 2, "usage: stashgen"},
	}
	for _, c := range cases {
		var stdout, stderr bytes.Buffer
		code := run(c.args, dir, &stdout, &stderr, fake)
		if code != c.code {
			t.Errorf("%v: exit %d, want %d\n%s", c.args, code, c.code, stderr.String())
		}
		if !strings.Contains(stderr.String(), c.want) {
			t.Errorf("%v: stderr %q lacks %q", c.args, stderr.String(), c.want)
		}
	}
	if _, err := os.Stat(filepath.Join(dir, "custom_stash.go")); err != nil {
		t.Errorf("-output: %v", err)
	}
}

// The real engine: the embedded guest, which the command links with the EQL
// types, so a struct with encrypt_into=TextEq generates, and a type the
// engine cannot produce yet is refused with nothing written. Skips when the
// guest is not built.
func TestRunAsksTheEmbeddedEngine(t *testing.T) {
	checker, err := encrypt.NewChecker(context.Background())
	if err != nil {
		t.Skip(err)
	}
	_ = checker.Close()
	dir := writeModule(t, map[string]string{"model.go": userSource})
	var stdout, stderr bytes.Buffer
	if code := run([]string{"-type", "User"}, dir, &stdout, &stderr, stashgen.GuestEngine); code != 0 {
		t.Fatalf("exit %d, want 0\n%s", code, stderr.String())
	}
	written, err := os.ReadFile(filepath.Join(dir, "user_stash.go"))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(written), "eql.TextEq") || !strings.Contains(string(written), `EncryptInto("email", gensupport.String, "TextEq")`) {
		t.Fatalf("the generated file does not name the EQL type:\n%s", written)
	}
	// A type the engine cannot produce yet: refused by name, nothing written.
	unproducible := strings.Replace(userSource, "encrypt_into=TextEq", "encrypt_into=TextMatch", 1)
	dir = writeModule(t, map[string]string{"model.go": unproducible})
	stderr.Reset()
	if code := run([]string{"-type", "User"}, dir, &stdout, &stderr, stashgen.GuestEngine); code != 1 {
		t.Fatalf("exit %d, want 1\n%s", code, stderr.String())
	}
	// Refused by the generator with the engine's reason, before the engine
	// is asked: se_targets lists the type as not producible.
	if !strings.Contains(stderr.String(), "cannot produce the EQL type TextMatch yet") {
		t.Fatalf("stderr = %q", stderr.String())
	}
	if _, err := os.Stat(filepath.Join(dir, "user_stash.go")); !os.IsNotExist(err) {
		t.Fatal("a file was written after the engine refused")
	}
	// A context of two segments leaves an EQL field no column: refused by
	// name, before the engine is asked, and nothing written.
	deep := strings.Replace(userSource, "context=users", "context=app/users", 1)
	dir = writeModule(t, map[string]string{"model.go": deep})
	stderr.Reset()
	if code := run([]string{"-type", "User"}, dir, &stdout, &stderr, stashgen.GuestEngine); code != 1 {
		t.Fatalf("exit %d, want 1\n%s", code, stderr.String())
	}
	if !strings.Contains(stderr.String(), "User.Email") || !strings.Contains(stderr.String(), `"app/users" has 2 segments`) {
		t.Fatalf("stderr = %q", stderr.String())
	}
	if _, err := os.Stat(filepath.Join(dir, "user_stash.go")); !os.IsNotExist(err) {
		t.Fatal("a file was written after the refusal")
	}
	// Separate columns, as before.
	columns := strings.Replace(userSource, "encrypt_into=TextEq", "encrypt,index=equality;match", 1)
	dir = writeModule(t, map[string]string{"model.go": columns})
	stderr.Reset()
	if code := run([]string{"-type", "User"}, dir, &stdout, &stderr, stashgen.GuestEngine); code != 0 {
		t.Fatalf("exit %d\n%s", code, stderr.String())
	}
}

func TestModelFlagsRepeat(t *testing.T) {
	var m modelFlags
	for _, s := range []string{"Rows=ContactRow", "Legacy=userdb.Contact:contactRow"} {
		if err := m.Set(s); err != nil {
			t.Fatal(err)
		}
	}
	if got := m.String(); got != "Rows=ContactRow Legacy=userdb.Contact:contactRow" {
		t.Fatalf("String = %q", got)
	}
}
