// Code generated by stashgen. DO NOT EDIT.

package blocklist

import (
	"context"

	"github.com/cipherstash/stack/languages/golang/stackencrypt"
	"github.com/cipherstash/stack/languages/golang/stackencrypt/gensupport"
)

// Stops compiling when the library does not accept this version of generated file.
const _ = gensupport.GeneratedVersion1

type EncryptedBlocked struct {
	Email EncryptedBlockedEmail
}

type EncryptedBlockedEmail struct {
	Ciphertext stackencrypt.Ciphertext
	Equality   stackencrypt.EqualityTerm
}

// Stops compiling when Blocked gains, loses, reorders or retypes a field.
var _ = blockedShape(Blocked{})

type blockedShape struct {
	_     struct{}
	Email string
}

var blockedSpec = gensupport.NewPlan("blocked_emails").
	EncryptIndex("email", stackencrypt.Equality)

var blockedPlan = gensupport.New(gensupport.Generated[Blocked, EncryptedBlocked]{
	Plan: blockedSpec,
	Source: func(v Blocked) gensupport.Values {
		return gensupport.Values{"email": v.Email}
	},
	Seal: func(v Blocked, rec gensupport.Record) EncryptedBlocked {
		email := rec["email"]
		return EncryptedBlocked{Email: EncryptedBlockedEmail{Ciphertext: email.Ciphertext, Equality: email.Equality}}
	},
	Open: func(e EncryptedBlocked) gensupport.Record {
		return gensupport.Record{
			"email": {Ciphertext: e.Email.Ciphertext, Equality: e.Email.Equality},
		}
	},
	Value: func(e EncryptedBlocked, vals gensupport.Values) (Blocked, error) {
		email, err := gensupport.Get[string](vals, "email")
		if err != nil {
			return Blocked{}, err
		}
		return Blocked{Email: email}, nil
	},
})

func (Blocked) StashPlan() *stackencrypt.RowPlan[Blocked, EncryptedBlocked] { return blockedPlan }

func (EncryptedBlocked) StashPlan() *stackencrypt.RowPlan[Blocked, EncryptedBlocked] {
	return blockedPlan
}

var BlockedFields = struct {
	Email BlockedEmailField
}{
	Email: BlockedEmailField{gensupport.NewField[string](blockedSpec, "email")},
}

type BlockedEmailField struct {
	plan gensupport.Field[string]
}

func (f BlockedEmailField) Encrypt(ctx context.Context, c *stackencrypt.Cipher, v string, opts ...stackencrypt.Option) (EncryptedBlockedEmail, error) {
	out, err := f.plan.Encrypt(ctx, c, v, opts...)
	if err != nil {
		return EncryptedBlockedEmail{}, err
	}
	return EncryptedBlockedEmail{Ciphertext: out.Ciphertext, Equality: out.Equality}, nil
}

func (f BlockedEmailField) Equality(ctx context.Context, c *stackencrypt.Cipher, v string, opts ...stackencrypt.Option) (stackencrypt.EqualityTerm, error) {
	return f.plan.Equality(ctx, c, v, opts...)
}
