// Code generated by stashgen. DO NOT EDIT.

package blocklist

import (
	"context"

	"github.com/cipherstash/stack/languages/golang/stackencrypt"
)

type EncryptedBlocked struct {
	Email EncryptedBlockedEmail
}

type EncryptedBlockedEmail struct {
	Ciphertext stackencrypt.Ciphertext
	Equality   stackencrypt.EqualityTerm
}

// Stops compiling when Blocked gains, loses, reorders or retypes a field.
var _ = blockedShape(Blocked{})

type blockedShape struct {
	_     struct{}
	Email string
}

var blockedPlan = stackencrypt.MustGenerate(stackencrypt.Generated[Blocked, EncryptedBlocked]{
	Plan: stackencrypt.NewPlan("blocked_emails").
		EncryptIndex("email", stackencrypt.Equality).
		MustBuild(),
	Source: func(v Blocked) stackencrypt.Values {
		return stackencrypt.Values{"email": v.Email}
	},
	Seal: func(v Blocked, rec stackencrypt.EncryptedRecord) EncryptedBlocked {
		email := rec.MustField("email")
		return EncryptedBlocked{Email: EncryptedBlockedEmail{Ciphertext: email.Ciphertext, Equality: email.Equality}}
	},
	Open: func(e EncryptedBlocked) stackencrypt.EncryptedRecord {
		return stackencrypt.RecordOf(map[string]stackencrypt.EncryptedField{
			"email": {Ciphertext: e.Email.Ciphertext, Equality: e.Email.Equality},
		})
	},
	Value: func(e EncryptedBlocked, vals stackencrypt.Values) (Blocked, error) {
		email, err := stackencrypt.Get[string](vals, "email")
		if err != nil {
			return Blocked{}, err
		}
		return Blocked{Email: email}, nil
	},
})

func (Blocked) StashPlan() *stackencrypt.RowPlan[Blocked, EncryptedBlocked] { return blockedPlan }

func (EncryptedBlocked) StashPlan() *stackencrypt.RowPlan[Blocked, EncryptedBlocked] {
	return blockedPlan
}

var BlockedFields = struct {
	Email BlockedEmailField
}{
	Email: BlockedEmailField{stackencrypt.MustField[string](blockedPlan.Plan(), "email")},
}

type BlockedEmailField struct {
	plan *stackencrypt.ValuePlan[string]
}

func (f BlockedEmailField) Encrypt(ctx context.Context, c *stackencrypt.Cipher, v string, opts ...stackencrypt.Option) (EncryptedBlockedEmail, error) {
	out, err := f.plan.Encrypt(ctx, c, v, opts...)
	if err != nil {
		return EncryptedBlockedEmail{}, err
	}
	return EncryptedBlockedEmail{Ciphertext: out.Ciphertext, Equality: out.Equality}, nil
}

func (f BlockedEmailField) Equality(ctx context.Context, c *stackencrypt.Cipher, v string, opts ...stackencrypt.Option) (stackencrypt.EqualityTerm, error) {
	return f.plan.Equality(ctx, c, v, opts...)
}
