//! Per-scalar matrix suites, generated by the `scalar_types!(matrix_suites)`
//! invocation below — one module per scalar type, each holding its
//! `scalar_matrix!` suite.
//!
//! The modules are generated from the single harness list in
//! `tests/sqlx/src/scalar_types.rs` — adding a type there adds its suite here
//! automatically. The old per-type `scalars/<token>.rs` files are gone.

eql_tests::scalar_types!(matrix_suites);

// NOTE: the `text_match` / `text_smoke` behavioural suites live in the sibling
// `encrypted_domain/text/` module tree, NOT here. The matrix-inventory gate
// discovers scalar types from every `scalars::<X>::` test-name prefix
// (`tasks`/`mise.toml`), so a `scalars::text_smoke::` module would be
// mis-discovered as a scalar type `text_smoke` and pollute the snapshot /
// catalog cross-check. Keeping them out of `scalars::` avoids that.
