import fs from 'node:fs'
import path from 'node:path'
import { loadStashConfig } from '@/config/index.js'
import { appendEvent, progress } from '@cipherstash/migrate'
import * as p from '@clack/prompts'
import pg from 'pg'

/**
 * Options accepted by `stash encrypt drop`. Generates a migration file
 * that drops the now-unused plaintext column (renamed to `<col>_plaintext`
 * by cutover). Does *not* apply the migration — the user runs their usual
 * migration tool (drizzle-kit, prisma, psql) to actually execute it.
 */
export interface DropCommandOptions {
  /** Physical table name, e.g. `users`. */
  table: string
  /**
   * Physical column — the original plaintext name. The generated migration
   * drops `<column>_plaintext` (the name the column has *after* cutover).
   */
  column: string
  /**
   * Directory to write the generated `.sql` migration into, relative to
   * the current working directory. Default: `./drizzle`. Use `./migrations`
   * (or similar) for Prisma / manual psql workflows.
   */
  migrationsDir?: string
}

/**
 * CLI handler for `stash encrypt drop`. Requires the column to be in
 * phase `cut-over`; otherwise errors out. Writes a timestamped
 * `ALTER TABLE … DROP COLUMN <col>_plaintext` statement, appends a
 * `dropped` event, and prints instructions for applying the migration.
 */
export async function dropCommand(options: DropCommandOptions) {
  p.intro('npx @cipherstash/cli encrypt drop')

  const config = await loadStashConfig()
  const client = new pg.Client({ connectionString: config.databaseUrl })

  try {
    await client.connect()

    const state = await progress(client, options.table, options.column)
    if (state?.phase !== 'cut-over') {
      p.log.error(
        `Cannot generate drop migration: ${options.table}.${options.column} is in phase '${state?.phase ?? '—'}'. Must be 'cut-over'.`,
      )
      process.exit(1)
    }

    const migrationsDir = path.resolve(
      process.cwd(),
      options.migrationsDir ?? 'drizzle',
    )
    fs.mkdirSync(migrationsDir, { recursive: true })

    const ts = new Date()
      .toISOString()
      .replace(/[-:.TZ]/g, '')
      .slice(0, 14)
    const fileName = `${ts}_drop_${options.table}_${options.column}_plaintext.sql`
    const filePath = path.join(migrationsDir, fileName)

    const sql = `-- Generated by @cipherstash/cli encrypt drop\n-- Drops the plaintext column now that ${options.table}.${options.column} is encrypted.\n\nALTER TABLE "${options.table}" DROP COLUMN "${options.column}_plaintext";\n`
    fs.writeFileSync(filePath, sql, 'utf-8')

    await appendEvent(client, {
      tableName: options.table,
      columnName: options.column,
      event: 'dropped',
      phase: 'dropped',
      details: { migrationFile: filePath },
    })

    p.log.success(`Migration written to ${filePath}`)
    p.note(
      `Review the migration, then apply it with your migration tool:\n  - drizzle-kit migrate\n  - prisma migrate deploy\n  - psql -f ${fileName}`,
      'Next',
    )
    p.outro('Drop migration generated.')
  } catch (error) {
    p.log.error(
      error instanceof Error ? error.message : 'Drop generation failed.',
    )
    process.exit(1)
  } finally {
    await client.end()
  }
}
