import fs from 'node:fs'
import path from 'node:path'
import {
  appendEvent,
  progress,
  setManifestTargetPhase,
} from '@cipherstash/migrate'
import * as p from '@clack/prompts'
import pg from 'pg'
import { detectDrizzle } from '@/commands/db/detect.js'
import { detectPackageManager, runnerCommand } from '@/commands/init/utils.js'
import { loadStashConfig } from '@/config/index.js'
import { scaffoldDrizzleMigration } from './drizzle-helper.js'

/**
 * Options accepted by `stash encrypt drop`. Generates a migration file
 * that drops the now-unused plaintext column (renamed to `<col>_plaintext`
 * by cutover). Does *not* apply the migration — the user runs their usual
 * migration tool (drizzle-kit, prisma, psql) to actually execute it.
 */
export interface DropCommandOptions {
  /** Physical table name, e.g. `users`. */
  table: string
  /**
   * Physical column — the original plaintext name. The generated migration
   * drops `<column>_plaintext` (the name the column has *after* cutover).
   */
  column: string
  /**
   * Directory to write the generated `.sql` migration into, relative to
   * the current working directory. Default: `./drizzle`. Use `./migrations`
   * (or similar) for Prisma / manual psql workflows.
   */
  migrationsDir?: string
}

/**
 * CLI handler for `stash encrypt drop`. Requires the column to be in
 * phase `cut-over`; otherwise errors out.
 *
 * For Drizzle projects, scaffolds the migration via `drizzle-kit generate
 * --custom` so the file lands with the correct sequential prefix and a
 * journal/snapshot entry — which is what `drizzle-kit migrate` actually
 * picks up. Hand-rolling the file (the prior behaviour) wrote a
 * timestamped `<ts>_drop_*.sql` that Drizzle ignored.
 *
 * For non-Drizzle projects, falls back to the self-named file behaviour
 * — a clearly named SQL file the user reviews and applies with their own
 * tooling (Prisma migrate, psql, etc.).
 */
export async function dropCommand(options: DropCommandOptions) {
  p.intro(runnerCommand(detectPackageManager(), 'stash encrypt drop'))

  const config = await loadStashConfig()
  const client = new pg.Client({ connectionString: config.databaseUrl })
  let exitCode = 0

  try {
    await client.connect()

    const state = await progress(client, options.table, options.column)
    if (state?.phase !== 'cut-over') {
      p.log.error(
        `Cannot generate drop migration: ${options.table}.${options.column} is in phase '${state?.phase ?? '—'}'. Must be 'cut-over'.`,
      )
      exitCode = 1
      return
    }

    const dot = options.table.indexOf('.')
    const qualifiedTable =
      dot >= 0
        ? `"${options.table.slice(0, dot)}"."${options.table.slice(dot + 1)}"`
        : `"${options.table}"`
    const dropSql = `-- Generated by stash encrypt drop\n-- Drops the plaintext column now that ${options.table}.${options.column} is encrypted.\n\nALTER TABLE ${qualifiedTable} DROP COLUMN "${options.column}_plaintext";\n`

    const cwd = process.cwd()
    const migrationsDir = options.migrationsDir ?? 'drizzle'
    const isDrizzle = detectDrizzle(cwd)
    let filePath: string
    let nextStep: string

    if (isDrizzle) {
      // Scaffold via drizzle-kit so the migration is journaled + snapshotted.
      // Without this, the file ships but `drizzle-kit migrate` never picks it
      // up because the journal doesn't reference it.
      const result = await scaffoldDrizzleMigration({
        name: `drop_${options.table}_${options.column}_plaintext`,
        outDir: migrationsDir,
        sql: dropSql,
      })
      filePath = result.path
      nextStep = `Apply with your usual Drizzle migrate command:\n  ${runnerCommand(detectPackageManager(), 'drizzle-kit migrate')}`
    } else {
      // Non-Drizzle fallback: emit a timestamped SQL file the user
      // applies with whichever migration tool they're running.
      const dirAbs = path.resolve(cwd, migrationsDir)
      fs.mkdirSync(dirAbs, { recursive: true })
      const ts = new Date()
        .toISOString()
        .replace(/[-:.TZ]/g, '')
        .slice(0, 14)
      const fileName = `${ts}_drop_${options.table}_${options.column}_plaintext.sql`
      filePath = path.join(dirAbs, fileName)
      fs.writeFileSync(filePath, dropSql, 'utf-8')
      nextStep = `Review the migration, then apply with your migration tool:\n  - prisma migrate deploy\n  - psql -f ${fileName}`
    }

    await appendEvent(client, {
      tableName: options.table,
      columnName: options.column,
      event: 'dropped',
      phase: 'dropped',
      details: { migrationFile: filePath, drizzleScaffolded: isDrizzle },
    })

    // Bump the manifest's target phase so `encrypt plan` reflects the
    // user's commitment to fully removing the plaintext column. No-op
    // when the column wasn't tracked in the manifest yet.
    await setManifestTargetPhase(options.table, options.column, 'dropped')

    p.log.success(`Migration written to ${filePath}`)
    p.note(nextStep, 'Next')
    p.outro('Drop migration generated.')
  } catch (error) {
    p.log.error(
      error instanceof Error ? error.message : 'Drop generation failed.',
    )
    exitCode = 1
  } finally {
    await client.end()
  }
  if (exitCode) process.exit(exitCode)
}
