// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package userdb

import (
	"github.com/cipherstash/stack/languages/golang/stackencrypt"
)

type User struct {
	ID         int64                     `db:"id" stash:"id"`
	Email      stackencrypt.Ciphertext   `db:"email" stash:"email"`
	EmailEq    stackencrypt.EqualityTerm `db:"email_eq" stash:"email,equality"`
	EmailMatch stackencrypt.MatchTerm    `db:"email_match" stash:"email,match"`
	Age        stackencrypt.Ciphertext   `db:"age" stash:"age"`
	AgeEq      stackencrypt.EqualityTerm `db:"age_eq" stash:"age,equality"`
	AgeOre     stackencrypt.OreTerm      `db:"age_ore" stash:"age,ore"`
	Attrs      stackencrypt.JSONDocument `db:"attrs" stash:"attrs,json"`
	Notes      stackencrypt.Ciphertext   `db:"notes" stash:"notes"`
}
