// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package userdb

import (
	"github.com/cipherstash/stack/languages/golang/stackencrypt/eql"
)

type User struct {
	ID    int64
	Email eql.TextSearch
	Age   eql.IntegerOrd
	Attrs eql.JSON
	Notes eql.Text
}
