// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package userdb

import (
	"context"

	"github.com/cipherstash/stack/languages/golang/stackencrypt"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (id, email, email_eq, email_match, age, age_eq, age_ore, attrs, notes)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateUserParams struct {
	ID         int64                     `db:"id" stash:"id"`
	Email      stackencrypt.Ciphertext   `db:"email" stash:"email"`
	EmailEq    stackencrypt.EqualityTerm `db:"email_eq" stash:"email,equality"`
	EmailMatch stackencrypt.MatchTerm    `db:"email_match" stash:"email,match"`
	Age        stackencrypt.Ciphertext   `db:"age" stash:"age"`
	AgeEq      stackencrypt.EqualityTerm `db:"age_eq" stash:"age,equality"`
	AgeOre     stackencrypt.OreTerm      `db:"age_ore" stash:"age,ore"`
	Attrs      stackencrypt.JSONDocument `db:"attrs" stash:"attrs,json"`
	Notes      stackencrypt.Ciphertext   `db:"notes" stash:"notes"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.EmailEq,
		arg.EmailMatch,
		arg.Age,
		arg.AgeEq,
		arg.AgeOre,
		arg.Attrs,
		arg.Notes,
	)
	return err
}

const findUsersByEmail = `-- name: FindUsersByEmail :many
SELECT id, email, email_eq, email_match, age, age_eq, age_ore, attrs, notes FROM users WHERE email_eq = $1
`

func (q *Queries) FindUsersByEmail(ctx context.Context, emailEq stackencrypt.EqualityTerm) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, findUsersByEmail, emailEq)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.EmailEq,
			&i.EmailMatch,
			&i.Age,
			&i.AgeEq,
			&i.AgeOre,
			&i.Attrs,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUser = `-- name: GetUser :one
SELECT id, email, email_eq, email_match, age, age_eq, age_ore, attrs, notes FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailEq,
		&i.EmailMatch,
		&i.Age,
		&i.AgeEq,
		&i.AgeOre,
		&i.Attrs,
		&i.Notes,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, email_eq, email_match, age, age_eq, age_ore, attrs, notes FROM users ORDER BY id
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.EmailEq,
			&i.EmailMatch,
			&i.Age,
			&i.AgeEq,
			&i.AgeOre,
			&i.Attrs,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserEmail = `-- name: UpdateUserEmail :exec
UPDATE users SET email = $2, email_eq = $3, email_match = $4 WHERE id = $1
`

type UpdateUserEmailParams struct {
	ID         int64                     `db:"id" stash:"id"`
	Email      stackencrypt.Ciphertext   `db:"email" stash:"email"`
	EmailEq    stackencrypt.EqualityTerm `db:"email_eq" stash:"email,equality"`
	EmailMatch stackencrypt.MatchTerm    `db:"email_match" stash:"email,match"`
}

func (q *Queries) UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) error {
	_, err := q.db.ExecContext(ctx, updateUserEmail,
		arg.ID,
		arg.Email,
		arg.EmailEq,
		arg.EmailMatch,
	)
	return err
}
