// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package userdb

import (
	"context"

	"github.com/cipherstash/stack/languages/golang/encrypt/eql"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (id, email, name) VALUES ($1, $2, $3)
`

type CreateUserParams struct {
	ID    int64
	Email eql.TextEq
	Name  eql.TextEq
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser, arg.ID, arg.Email, arg.Name)
	return err
}

const findUsersByEmail = `-- name: FindUsersByEmail :many
SELECT id, email, name FROM users WHERE email = $1::eql_v3.query_text_eq
`

// One cast, straight to the query domain: sqlc types a parameter by its first
// cast, so ::jsonb::eql_v3.query_text_eq would generate json.RawMessage.
func (q *Queries) FindUsersByEmail(ctx context.Context, email eql.TextEqQuery) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, findUsersByEmail, email)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(&i.ID, &i.Email, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUser = `-- name: GetUser :one
SELECT id, email, name FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(&i.ID, &i.Email, &i.Name)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, name FROM users ORDER BY id
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(&i.ID, &i.Email, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
