// Code generated by stashgen. DO NOT EDIT.

package accounts

import (
	"context"
	"log/slog"

	"github.com/cipherstash/stack/languages/golang/encrypt"
	"github.com/cipherstash/stack/languages/golang/encrypt/eql"
	"github.com/cipherstash/stack/languages/golang/encrypt/gensupport"
	"gorm.io/gorm"
)

// Stops compiling when the library does not accept this version of generated file.
const _ = gensupport.GeneratedVersion1

// Not encrypted and not stored: the unexported field "cache". Tag it
// `stash:"-"` to confirm that.

type EncryptedAccount struct {
	gorm.Model
	Email eql.TextEq `gorm:"uniqueIndex" json:"email"`
}

func (e EncryptedAccount) String() string {
	return gensupport.Redacted("EncryptedAccount", map[string]any{"Model": e.Model}, "Email")
}

func (e EncryptedAccount) LogValue() slog.Value {
	return gensupport.RedactedLog(map[string]any{"Model": e.Model}, "Email")
}

// Written because of -redact: Account no longer prints its sealed fields.
func (a Account) String() string {
	return gensupport.Redacted("Account", map[string]any{"Model": a.Model}, "Email")
}

func (a Account) LogValue() slog.Value {
	return gensupport.RedactedLog(map[string]any{"Model": a.Model}, "Email")
}

// Stops compiling when Account gains, loses, reorders or retypes a field.
var _ = accountShape(Account{})

type accountShape struct {
	_ struct{}
	gorm.Model
	Email string
	cache string
	token string
}

var declaration = gensupport.Declare("accounts").
	Passthrough("id").
	Passthrough("created_at").
	Passthrough("updated_at").
	Passthrough("deleted_at").
	EncryptIndex("email", encrypt.Equality).
	Omit("token")

var codec = gensupport.New(gensupport.Generated[Account, EncryptedAccount]{
	TypeName:    "Account",
	Declaration: declaration,
	Unexported:  []string{"cache"},
	Source: func(v Account) gensupport.Values {
		return gensupport.Values{"email": v.Email}
	},
	Seal: func(v Account, rec gensupport.Record) EncryptedAccount {
		return EncryptedAccount{Model: v.Model, Email: eql.NewTextEq(rec["email"])}
	},
	Open: func(e EncryptedAccount) gensupport.Record {
		return gensupport.Record{"email": e.Email.Outputs()}
	},
	Value: func(e EncryptedAccount, vals gensupport.Values) (Account, error) {
		email, err := gensupport.Get[string](vals, "email")
		if err != nil {
			return Account{}, err
		}
		return Account{Model: e.Model, Email: email}, nil
	},
})

func Encrypt(ctx context.Context, cipher *encrypt.Cipher, accounts []Account) ([]EncryptedAccount, error) {
	return codec.Encrypt(ctx, cipher, accounts)
}

func Decrypt(ctx context.Context, d encrypt.Decrypter, encrypted []EncryptedAccount) ([]Account, error) {
	return codec.Decrypt(ctx, d, encrypted)
}

func EncryptInto(dst *[]EncryptedAccount, accounts []Account) encrypt.Operation {
	return codec.EncryptInto(dst, accounts)
}

func DecryptInto(dst *[]Account, encrypted []EncryptedAccount) encrypt.Operation {
	return codec.DecryptInto(dst, encrypted)
}

var Fields = struct {
	Email EmailField
}{
	Email: EmailField{gensupport.NewField[string](declaration, "email")},
}

type EmailField struct {
	field gensupport.Field[string]
}

func (f EmailField) Encrypt(ctx context.Context, c *encrypt.Cipher, v string) (eql.TextEq, error) {
	out, err := f.field.Encrypt(ctx, c, v)
	return eql.NewTextEq(out), err
}

func (f EmailField) Query(ctx context.Context, c *encrypt.Cipher, v string) (eql.TextEqQuery, error) {
	out, err := f.field.Query(ctx, c, v)
	return eql.NewTextEqQuery(out), err
}
