// Code generated by stashgen. DO NOT EDIT.

//go:build !stashgen

package individuals

import (
	"context"

	"github.com/cipherstash/stack/languages/golang/stackencrypt"
	"github.com/cipherstash/stack/languages/golang/stackencrypt/gensupport"
)

// Stops compiling when the library does not accept this version of generated file.
const _ = gensupport.GeneratedVersion1

type EncryptedIndividual struct {
	ID         int64
	Name       stackencrypt.Ciphertext
	Email      EncryptedIndividualEmail
	MedicareNo EncryptedIndividualMedicareNo
	Nickname   string
}

type EncryptedIndividualEmail struct {
	Ciphertext stackencrypt.Ciphertext
	Equality   stackencrypt.EqualityTerm
	Match      stackencrypt.MatchTerm
}

type EncryptedIndividualMedicareNo struct {
	Ciphertext stackencrypt.Ciphertext
	Equality   stackencrypt.EqualityTerm
}

// Stops compiling when Individual gains, loses, reorders or retypes a field.
var _ = individualShape(Individual{})

type individualShape struct {
	ID         int64
	Name       string
	Email      string
	MedicareNo string
	Nickname   string
}

var individualSpec = gensupport.NewPlan("individuals").
	Encrypt("name").
	EncryptIndex("email", stackencrypt.Equality, stackencrypt.Match()).
	EncryptIndex("medicare_number", stackencrypt.Equality)

var individualPlan = gensupport.New(gensupport.Generated[Individual, EncryptedIndividual]{
	Plan: individualSpec,
	Source: func(v Individual) gensupport.Values {
		return gensupport.Values{"name": v.Name, "email": v.Email, "medicare_number": v.MedicareNo}
	},
	Seal: func(v Individual, rec gensupport.Record) EncryptedIndividual {
		email, medicare := rec["email"], rec["medicare_number"]
		return EncryptedIndividual{
			ID:         v.ID,
			Name:       rec["name"].Ciphertext,
			Email:      EncryptedIndividualEmail{Ciphertext: email.Ciphertext, Equality: email.Equality, Match: email.Match},
			MedicareNo: EncryptedIndividualMedicareNo{Ciphertext: medicare.Ciphertext, Equality: medicare.Equality},
			Nickname:   v.Nickname,
		}
	},
	Open: func(e EncryptedIndividual) gensupport.Record {
		return gensupport.Record{
			"name":            {Ciphertext: e.Name},
			"email":           {Ciphertext: e.Email.Ciphertext, Equality: e.Email.Equality, Match: e.Email.Match},
			"medicare_number": {Ciphertext: e.MedicareNo.Ciphertext, Equality: e.MedicareNo.Equality},
		}
	},
	Value: func(e EncryptedIndividual, vals gensupport.Values) (Individual, error) {
		v := Individual{ID: e.ID, Nickname: e.Nickname}
		var err error
		if v.Name, err = gensupport.Get[string](vals, "name"); err != nil {
			return Individual{}, err
		}
		if v.Email, err = gensupport.Get[string](vals, "email"); err != nil {
			return Individual{}, err
		}
		if v.MedicareNo, err = gensupport.Get[string](vals, "medicare_number"); err != nil {
			return Individual{}, err
		}
		return v, nil
	},
})

func (Individual) StashPlan() *stackencrypt.RowPlan[Individual, EncryptedIndividual] {
	return individualPlan
}

func (EncryptedIndividual) StashPlan() *stackencrypt.RowPlan[Individual, EncryptedIndividual] {
	return individualPlan
}

var IndividualFields = struct {
	Name       IndividualNameField
	Email      IndividualEmailField
	MedicareNo IndividualMedicareNoField
}{
	Name:       IndividualNameField{gensupport.NewField[string](individualSpec, "name")},
	Email:      IndividualEmailField{gensupport.NewField[string](individualSpec, "email")},
	MedicareNo: IndividualMedicareNoField{gensupport.NewField[string](individualSpec, "medicare_number")},
}

type IndividualNameField struct {
	plan gensupport.Field[string]
}

func (f IndividualNameField) Encrypt(ctx context.Context, c *stackencrypt.Cipher, v string, opts ...stackencrypt.Option) (stackencrypt.Ciphertext, error) {
	out, err := f.plan.Encrypt(ctx, c, v, opts...)
	return out.Ciphertext, err
}

type IndividualEmailField struct {
	plan gensupport.Field[string]
}

func (f IndividualEmailField) Encrypt(ctx context.Context, c *stackencrypt.Cipher, v string, opts ...stackencrypt.Option) (EncryptedIndividualEmail, error) {
	out, err := f.plan.Encrypt(ctx, c, v, opts...)
	if err != nil {
		return EncryptedIndividualEmail{}, err
	}
	return EncryptedIndividualEmail{Ciphertext: out.Ciphertext, Equality: out.Equality, Match: out.Match}, nil
}

func (f IndividualEmailField) Equality(ctx context.Context, c *stackencrypt.Cipher, v string, opts ...stackencrypt.Option) (stackencrypt.EqualityTerm, error) {
	return f.plan.Equality(ctx, c, v, opts...)
}

func (f IndividualEmailField) Match(ctx context.Context, c *stackencrypt.Cipher, v string, opts ...stackencrypt.Option) (stackencrypt.MatchTerm, error) {
	return f.plan.Match(ctx, c, v, opts...)
}

type IndividualMedicareNoField struct {
	plan gensupport.Field[string]
}

func (f IndividualMedicareNoField) Encrypt(ctx context.Context, c *stackencrypt.Cipher, v string, opts ...stackencrypt.Option) (EncryptedIndividualMedicareNo, error) {
	out, err := f.plan.Encrypt(ctx, c, v, opts...)
	if err != nil {
		return EncryptedIndividualMedicareNo{}, err
	}
	return EncryptedIndividualMedicareNo{Ciphertext: out.Ciphertext, Equality: out.Equality}, nil
}

func (f IndividualMedicareNoField) Equality(ctx context.Context, c *stackencrypt.Cipher, v string, opts ...stackencrypt.Option) (stackencrypt.EqualityTerm, error) {
	return f.plan.Equality(ctx, c, v, opts...)
}
