// Code generated by stashgen. DO NOT EDIT.

//go:build !stashgen

package individuals

import (
	"context"
	"log/slog"

	"github.com/cipherstash/stack/languages/golang/encrypt"
	"github.com/cipherstash/stack/languages/golang/encrypt/gensupport"
)

// Stops compiling when the library does not accept this version of generated file.
const _ = gensupport.GeneratedVersion1

// Individual prints its sealed fields in the clear: it has no String or
// LogValue method. Write them, or run stashgen with -redact.

type EncryptedIndividual struct {
	ID         int64
	Name       EncryptedIndividualName
	Email      EncryptedIndividualEmail
	MedicareNo EncryptedIndividualMedicareNo
	Nickname   string
}

type EncryptedIndividualName struct {
	Ciphertext encrypt.Ciphertext
}

type EncryptedIndividualEmail struct {
	Ciphertext encrypt.Ciphertext
	Equality   encrypt.EqualityTerm
	Match      encrypt.MatchTerm
}

type EncryptedIndividualMedicareNo struct {
	Ciphertext encrypt.Ciphertext
	Equality   encrypt.EqualityTerm
}

func (e EncryptedIndividual) String() string {
	return gensupport.Redacted("EncryptedIndividual", map[string]any{"ID": e.ID, "Nickname": e.Nickname}, "Name", "Email", "MedicareNo")
}

func (e EncryptedIndividual) LogValue() slog.Value {
	return gensupport.RedactedLog(map[string]any{"ID": e.ID, "Nickname": e.Nickname}, "Name", "Email", "MedicareNo")
}

// Stops compiling when Individual gains, loses, reorders or retypes a field.
var _ = individualShape(Individual{})

type individualShape struct {
	ID         int64
	Name       string
	Email      string
	MedicareNo string
	Nickname   string
}

var declaration = gensupport.Declare("individuals").
	Passthrough("id").
	Encrypt("name").
	EncryptIndex("email", encrypt.Equality, encrypt.Match()).
	EncryptIndex("medicare_number", encrypt.Equality).
	Passthrough("nickname")

var codec = gensupport.New(gensupport.Generated[Individual, EncryptedIndividual]{
	TypeName:        "Individual",
	Declaration:     declaration,
	PrintsPlaintext: true,
	Source: func(v Individual) gensupport.Values {
		return gensupport.Values{"name": v.Name, "email": v.Email, "medicare_number": v.MedicareNo}
	},
	Seal: func(v Individual, rec gensupport.Record) EncryptedIndividual {
		email, medicare := rec["email"], rec["medicare_number"]
		return EncryptedIndividual{
			ID:         v.ID,
			Name:       EncryptedIndividualName{Ciphertext: rec["name"].Ciphertext},
			Email:      EncryptedIndividualEmail{Ciphertext: email.Ciphertext, Equality: email.Equality, Match: email.Match},
			MedicareNo: EncryptedIndividualMedicareNo{Ciphertext: medicare.Ciphertext, Equality: medicare.Equality},
			Nickname:   v.Nickname,
		}
	},
	Open: func(e EncryptedIndividual) gensupport.Record {
		return gensupport.Record{
			"name":            {Ciphertext: e.Name.Ciphertext},
			"email":           {Ciphertext: e.Email.Ciphertext, Equality: e.Email.Equality, Match: e.Email.Match},
			"medicare_number": {Ciphertext: e.MedicareNo.Ciphertext, Equality: e.MedicareNo.Equality},
		}
	},
	Value: func(e EncryptedIndividual, vals gensupport.Values) (Individual, error) {
		v := Individual{ID: e.ID, Nickname: e.Nickname}
		var err error
		if v.Name, err = gensupport.Get[string](vals, "name"); err != nil {
			return Individual{}, err
		}
		if v.Email, err = gensupport.Get[string](vals, "email"); err != nil {
			return Individual{}, err
		}
		if v.MedicareNo, err = gensupport.Get[string](vals, "medicare_number"); err != nil {
			return Individual{}, err
		}
		return v, nil
	},
})

func Encrypt(ctx context.Context, cipher *encrypt.Cipher, individuals []Individual) ([]EncryptedIndividual, error) {
	return codec.Encrypt(ctx, cipher, individuals)
}

func Decrypt(ctx context.Context, d encrypt.Decrypter, encrypted []EncryptedIndividual) ([]Individual, error) {
	return codec.Decrypt(ctx, d, encrypted)
}

func EncryptInto(dst *[]EncryptedIndividual, individuals []Individual) encrypt.Operation {
	return codec.EncryptInto(dst, individuals)
}

func DecryptInto(dst *[]Individual, encrypted []EncryptedIndividual) encrypt.Operation {
	return codec.DecryptInto(dst, encrypted)
}

var Fields = struct {
	MedicareNo MedicareNoField
}{
	MedicareNo: MedicareNoField{gensupport.NewField[string](declaration, "medicare_number")},
}

type MedicareNoField struct {
	field gensupport.Field[string]
}

func (f MedicareNoField) Encrypt(ctx context.Context, c *encrypt.Cipher, v string) (EncryptedIndividualMedicareNo, error) {
	out, err := f.field.Encrypt(ctx, c, v)
	if err != nil {
		return EncryptedIndividualMedicareNo{}, err
	}
	return EncryptedIndividualMedicareNo{Ciphertext: out.Ciphertext, Equality: out.Equality}, nil
}

func (f MedicareNoField) Equality(ctx context.Context, c *encrypt.Cipher, v string) (encrypt.EqualityTerm, error) {
	return f.field.Equality(ctx, c, v)
}
